"use client";

import { FormEvent, useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { api } from "@/lib/api";
import { MobileAppShell } from "@/components/MobileAppShell";
type Dashboard = Record<string, number>;
type Rider = { id: string; name: string; email: string; riderProfile: { approval: string; subscriptions: { status: string }[] } };
type Client = { id: string; name: string; email: string; status: string };
type Trip = { id: string; status: string; originAddress: string; destinationAddress: string; currency: string; estimatedPrice: string; client: { name: string }; rider?: { name: string } | null };
type Ad = { id: string; title: string; description?: string | null; imageUrl?: string | null; actionLabel?: string | null; actionUrl?: string | null; backgroundColor: string; textColor: string; displayOrder: number; active: boolean };
type Draft = Omit<Ad, "id">;
const empty: Draft = { title: "", description: "", imageUrl: "", actionLabel: "", actionUrl: "", backgroundColor: "#f97316", textColor: "#ffffff", displayOrder: 0, active: true };
const nullable = (value?: string | null) => value?.trim() || null;

export default function AdminPage() {
  const [dashboard, setDashboard] = useState<Dashboard>({}); const [riders, setRiders] = useState<Rider[]>([]); const [clients, setClients] = useState<Client[]>([]); const [trips, setTrips] = useState<Trip[]>([]); const [settings, setSettings] = useState<Record<string, string>>({}); const [ads, setAds] = useState<Ad[]>([]); const [draft, setDraft] = useState<Draft>(empty); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState("");
  const load = () => Promise.all([api<Dashboard>("/admin/dashboard"), api<Rider[]>("/admin/riders"), api<Client[]>("/admin/clients"), api<Trip[]>("/admin/trips"), api<Record<string, string>>("/admin/settings"), api<Ad[]>("/advertisements/manage")]).then(([d, r, c, t, s, a]) => { setDashboard(d); setRiders(r); setClients(c); setTrips(t); setSettings(s); setAds(a); }).catch((error) => setMessage(error.message));
  useEffect(() => { load(); }, []);
  const approve = async (id: string) => { await api(`/admin/riders/${id}/status`, { method: "PATCH", body: JSON.stringify({ approval: "APPROVED" }) }); load(); };
  const activate = async (id: string) => { await api(`/admin/riders/${id}/subscriptions`, { method: "POST", body: JSON.stringify({ expiresAt: new Date(Date.now() + 30 * 864e5).toISOString() }) }); load(); };
  const saveSettings = async () => { await api("/admin/settings", { method: "PATCH", body: JSON.stringify(settings) }); setMessage("Tarifas guardadas."); };
  const saveAd = async (event: FormEvent) => { event.preventDefault(); const body = { ...draft, description: nullable(draft.description), imageUrl: nullable(draft.imageUrl), actionLabel: nullable(draft.actionLabel), actionUrl: nullable(draft.actionUrl) }; await api(editing ? `/advertisements/${editing}` : "/advertisements", { method: editing ? "PATCH" : "POST", body: JSON.stringify(body) }); setDraft(empty); setEditing(null); setMessage("Publicidad guardada."); load(); };
  return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><section className="mt-3"><p className="text-sm font-bold text-orange-500">MOTOYA ADMIN</p><h1 className="text-2xl font-bold">Operación</h1></section><nav className="mt-4 flex gap-2 overflow-x-auto text-sm"><a className="border" href="#resumen">Resumen</a><a className="border" href="#viajes">Viajes</a><a className="border" href="#riders">Riders</a><a className="border" href="#clientes">Clientes</a><a className="border" href="#publicidad">Publicidad</a><a className="border" href="#tarifas">Tarifas</a></nav>
    <section id="resumen" className="mt-5 grid scroll-mt-4 grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(dashboard).map(([key, value]) => <div className="card" key={key}><p className="muted">{key}</p><b className="text-xl">{value}</b></div>)}</section>
    <section id="viajes" className="card mt-5 scroll-mt-4"><h2 className="font-bold">Viajes recientes</h2>{trips.slice(0, 8).map((trip) => <article className="mt-2 rounded-xl border p-3" key={trip.id}><div className="flex justify-between"><b>{trip.status}</b><span>{trip.currency} {trip.estimatedPrice}</span></div><p>{trip.originAddress} → {trip.destinationAddress}</p><p className="muted">{trip.client.name} · {trip.rider?.name || "Sin rider"}</p></article>)}{trips.length === 0 && <p className="muted mt-2">No hay viajes aún.</p>}</section>
    <section id="riders" className="mt-5 scroll-mt-4"><h2 className="font-bold">Riders</h2>{riders.map((rider) => <article className="card mt-2 flex flex-col gap-2 md:flex-row md:items-center md:justify-between" key={rider.id}><div><b>{rider.name}</b><p className="muted">{rider.email} · {rider.riderProfile.approval} · {rider.riderProfile.subscriptions[0]?.status || "Sin suscripción"}</p></div><div className="flex gap-2"><button className="border" onClick={() => approve(rider.id)}>Aprobar</button><button className="primary" onClick={() => activate(rider.id)}>Activar 30 días</button></div></article>)}</section>
    <section id="clientes" className="card mt-5 scroll-mt-4"><h2 className="font-bold">Clientes</h2>{clients.slice(0, 12).map((client) => <article className="mt-2 flex justify-between rounded-xl border p-3" key={client.id}><div><b>{client.name}</b><p className="muted">{client.email}</p></div><span>{client.status}</span></article>)}</section>
    <section id="publicidad" className="card mt-5 scroll-mt-4"><h2 className="font-bold">Publicidad</h2><form className="mt-3 grid gap-2 md:grid-cols-2" onSubmit={saveAd}><label>Título<input required value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label><label>Texto<input value={draft.description || ""} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label><label>Imagen URL<input value={draft.imageUrl || ""} onChange={(e) => setDraft({ ...draft, imageUrl: e.target.value })} /></label><label>Orden<input type="number" value={draft.displayOrder} onChange={(e) => setDraft({ ...draft, displayOrder: Number(e.target.value) })} /></label><label>Fondo<input type="color" value={draft.backgroundColor} onChange={(e) => setDraft({ ...draft, backgroundColor: e.target.value })} /></label><label className="flex items-center gap-2"><input className="w-auto" type="checkbox" checked={draft.active} onChange={(e) => setDraft({ ...draft, active: e.target.checked })} /> Activo</label><div><button className="primary" type="submit">{editing ? "Actualizar" : "Crear anuncio"}</button>{editing && <button className="border ml-2" type="button" onClick={() => { setEditing(null); setDraft(empty); }}>Cancelar</button>}</div></form>{ads.map((ad) => <article className="mt-2 flex justify-between rounded-xl border p-3" key={ad.id}><div><b>{ad.title}</b><p className="muted">{ad.active ? "Activo" : "Oculto"} · Orden {ad.displayOrder}</p></div><div><button className="border" onClick={() => { const { id, ...next } = ad; setDraft(next); setEditing(id); }}>Editar</button><button className="ml-2 text-red-600" onClick={async () => { await api(`/advertisements/${ad.id}`, { method: "DELETE" }); load(); }}>Eliminar</button></div></article>)}</section>
    <section id="tarifas" className="card mt-5 scroll-mt-4"><h2 className="font-bold">Tarifas y operación</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{Object.entries(settings).map(([key, value]) => <label key={key}>{key}<input value={value} onChange={(e) => setSettings({ ...settings, [key]: e.target.value })} /></label>)}</div><button className="primary mt-3" onClick={saveSettings}>Guardar cambios</button></section>{message && <p className="mt-3 text-sm" role="status">{message}</p>}
  </MobileAppShell></Guard>;
}
