"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Ad = { id: string; title: string; description?: string | null; imageUrl?: string | null; actionLabel?: string | null; actionUrl?: string | null; backgroundColor: string; textColor: string; displayOrder: number; active: boolean };
type Draft = Omit<Ad, "id">;
const blank: Draft = { title: "", description: "", imageUrl: "", actionLabel: "", actionUrl: "", backgroundColor: "#f97316", textColor: "#ffffff", displayOrder: 1, active: true };
const clean = (value?: string | null) => value?.trim() || null;

export default function AdminAdsPage() {
  const [ads, setAds] = useState<Ad[]>([]); const [draft, setDraft] = useState<Draft>(blank); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState("");
  const load = () => api<Ad[]>("/advertisements/manage").then(setAds).catch((error) => setMessage(error.message));
  useEffect(() => { load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { ...draft, title: draft.title.trim(), description: clean(draft.description), imageUrl: clean(draft.imageUrl), actionLabel: clean(draft.actionLabel), actionUrl: clean(draft.actionUrl), displayOrder: Number(draft.displayOrder) || 1 }; await api(editing ? `/advertisements/${editing}` : "/advertisements", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); setDraft(blank); setEditing(null); setMessage(editing ? "Anuncio actualizado." : "Anuncio creado y listo para el carrusel."); await load(); } catch (error) { setMessage((error as Error).message); } };
  const edit = (ad: Ad) => { const { id, ...next } = ad; setDraft(next); setEditing(id); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const toggle = async (ad: Ad) => { try { await api(`/advertisements/${ad.id}`, { method: "PATCH", body: JSON.stringify({ active: !ad.active }) }); setMessage(ad.active ? "Anuncio ocultado." : "Anuncio activado."); await load(); } catch (error) { setMessage((error as Error).message); } };
  const keepTestThree = async () => { const keep = ads.find((ad) => ad.title.trim().toLowerCase() === "test 3"); if (!keep) { setMessage("No existe un anuncio llamado test 3 para conservar."); return; } if (!window.confirm("Se eliminarán los demás anuncios y se conservará únicamente test 3.")) return; try { await Promise.all(ads.filter((ad) => ad.id !== keep.id).map((ad) => api(`/advertisements/${ad.id}`, { method: "DELETE" }))); await api(`/advertisements/${keep.id}`, { method: "PATCH", body: JSON.stringify({ active: true, displayOrder: 1 }) }); setMessage("Carrusel limpiado: solo queda test 3."); await load(); } catch (error) { setMessage((error as Error).message); } };
  return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><section className="mt-4 flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[.16em] text-orange-500">COMUNICACIÓN</p><h1 className="text-2xl font-black">Carrusel de anuncios</h1><p className="muted">Contenido visible para los clientes en la pantalla principal.</p></div><Link className="mt-2 text-sm font-bold text-orange-600" href="/admin/configuration">Configuración</Link></section>
    <form className="card mt-4 space-y-3" onSubmit={submit}><div className="flex items-center justify-between"><div><h2 className="font-black">{editing ? "Editar anuncio" : "Nuevo anuncio"}</h2><p className="muted">La vista previa usa tus colores.</p></div>{editing ? <button type="button" className="border px-3 py-2 text-sm" onClick={() => { setEditing(null); setDraft(blank); }}>Cancelar</button> : null}</div><input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Título del anuncio" /><textarea value={draft.description || ""} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Mensaje breve (opcional)" /><input value={draft.imageUrl || ""} onChange={(event) => setDraft({ ...draft, imageUrl: event.target.value })} placeholder="URL de imagen (opcional)" /><div className="grid grid-cols-2 gap-2"><input value={draft.actionLabel || ""} onChange={(event) => setDraft({ ...draft, actionLabel: event.target.value })} placeholder="Texto de acción" /><input type="number" min="1" value={draft.displayOrder} onChange={(event) => setDraft({ ...draft, displayOrder: Number(event.target.value) })} placeholder="Orden" /></div><input value={draft.actionUrl || ""} onChange={(event) => setDraft({ ...draft, actionUrl: event.target.value })} placeholder="Enlace de acción (opcional)" /><div className="grid grid-cols-2 gap-2"><label className="text-sm font-semibold">Fondo<input className="mt-1 h-11 p-1" type="color" value={draft.backgroundColor} onChange={(event) => setDraft({ ...draft, backgroundColor: event.target.value })} /></label><label className="text-sm font-semibold">Texto<input className="mt-1 h-11 p-1" type="color" value={draft.textColor} onChange={(event) => setDraft({ ...draft, textColor: event.target.value })} /></label></div><article className="overflow-hidden rounded-2xl p-4 shadow-inner" style={{ backgroundColor: draft.backgroundColor, color: draft.textColor }}><p className="text-xs font-bold opacity-75">VISTA PREVIA · #{draft.displayOrder}</p><b className="mt-2 block text-xl">{draft.title || "Tu anuncio"}</b><p className="mt-1 text-sm opacity-90">{draft.description || "Añade una descripción breve para el carrusel."}</p>{draft.actionLabel ? <span className="mt-3 inline-block rounded-lg bg-black/15 px-3 py-2 text-sm font-bold">{draft.actionLabel}</span> : null}</article><button className="primary w-full" type="submit">{editing ? "Guardar cambios" : "Publicar anuncio"}</button></form>
    <section className="mt-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">Anuncios configurados</h2><p className="muted">El orden menor aparece primero en el carrusel.</p></div><button className="border border-red-200 px-3 py-2 text-xs text-red-600" onClick={keepTestThree}>Conservar test 3</button></div><div className="mt-3 space-y-3">{ads.map((ad) => <article className="card overflow-hidden p-0" key={ad.id}><div className="p-4" style={{ backgroundColor: ad.backgroundColor, color: ad.textColor }}><div className="flex justify-between gap-3"><div><p className="text-xs font-bold opacity-75">ORDEN #{ad.displayOrder}</p><b className="mt-1 block text-lg">{ad.title}</b><p className="mt-1 text-sm opacity-90">{ad.description || "Sin descripción"}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${ad.active ? "bg-emerald-950/25" : "bg-black/20"}`}>{ad.active ? "ACTIVO" : "OCULTO"}</span></div></div><div className="flex gap-2 p-3"><button className="border flex-1 py-2 text-sm" onClick={() => edit(ad)}>Editar</button><button className="primary flex-1 py-2 text-sm" onClick={() => toggle(ad)}>{ad.active ? "Ocultar" : "Activar"}</button></div></article>)}{!ads.length ? <p className="card">Aún no hay anuncios configurados.</p> : null}</div></section>{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>;
}
