"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Plan = { id: string; code: string; name: string; price: string; durationDays: number; isActive: boolean };
export default function AdminPlansPage() { const [plans, setPlans] = useState<Plan[]>([]); const [message, setMessage] = useState(""); const load = () => api<Plan[]>("/subscriptions/admin/plans").then(setPlans).catch((error) => setMessage(error.message)); useEffect(() => { load(); }, []); const save = async (plan: Plan, update: Partial<Plan>) => { try { await api(`/subscriptions/admin/plans/${plan.id}`, { method: "PATCH", body: JSON.stringify({ price: Number(plan.price), isActive: plan.isActive, ...update }) }); setMessage("Plan actualizado."); await load(); } catch (error) { setMessage((error as Error).message); } }; return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><section className="mt-4 flex items-start justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-orange-500">SUSCRIPCIONES</p><h1 className="text-2xl font-black">Planes mensuales</h1><p className="muted">Los pedidos creados conservan su precio original.</p></div><Link className="mt-2 text-sm font-bold text-orange-600" href="/admin/configuration">Configuración</Link></section>{plans.map((plan) => <article className="card mt-3" key={plan.id}><div className="flex justify-between gap-3"><div><b>{plan.name}</b><p className="muted">{plan.durationDays} días de vigencia</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${plan.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{plan.isActive ? "ACTIVO" : "OCULTO"}</span></div><label className="mt-3 block text-sm font-bold">Precio en córdobas<input className="mt-1" min="1" type="number" value={plan.price} onChange={(event) => setPlans((all) => all.map((item) => item.id === plan.id ? { ...item, price: event.target.value } : item))} /></label><div className="mt-3 flex gap-2"><button className="primary flex-1" onClick={() => save(plan, {})}>Guardar NIO</button><button className="border flex-1" onClick={() => save(plan, { isActive: !plan.isActive })}>{plan.isActive ? "Ocultar" : "Activar"}</button></div></article>)}{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>; }
