"use client";

import { FormEvent, useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api, getSession } from "@/lib/api";

type DocumentType = "NATIONAL_ID" | "DRIVER_LICENSE" | "VEHICLE_REGISTRATION";
type RiderDocument = { type: DocumentType; status: string; frontImage?: string | null; backImage?: string | null; rejectionReason?: string | null };
type Activation = { status: string; profileComplete: boolean; documents: RiderDocument[]; documentsSubmittedAt?: string | null; workZoneConfigured: boolean; workZoneDepartment?: string | null; nextAction: string };
type Profile = { nationalId?: string | null; driverLicense?: string | null; vehiclePlate?: string | null; vehicleModel?: string | null };
type Pictures = Partial<Record<DocumentType, { frontImage?: string; backImage?: string }>>;
const documentTypes: DocumentType[] = ["NATIONAL_ID", "DRIVER_LICENSE", "VEHICLE_REGISTRATION"];
const documentNames: Record<DocumentType, string> = { NATIONAL_ID: "Cedula de identidad", DRIVER_LICENSE: "Licencia de conducir", VEHICLE_REGISTRATION: "Documento del vehiculo" };

async function readImage(file: File) {
  return await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
}

export default function RiderAccount() {
  const [activation, setActivation] = useState<Activation | null>(null);
  const [profile, setProfile] = useState<Profile>({});
  const [pictures, setPictures] = useState<Pictures>({});
  const [editing, setEditing] = useState(false);
  const [message, setMessage] = useState("");
  const [detectedZone, setDetectedZone] = useState<{ department: string; lat: number; lng: number } | null>(null);

  const load = () => Promise.all([api<Activation>("/riders/me/activation"), api<Profile>("/riders/me")]).then(([nextActivation, nextProfile]) => {
    setActivation(nextActivation); setProfile(nextProfile);
    setPictures(Object.fromEntries(nextActivation.documents.map((document) => [document.type, { frontImage: document.frontImage || undefined, backImage: document.backImage || undefined }])));
  }).catch((cause) => setMessage(cause.message));
  useEffect(() => { load(); }, []);

  const approved = documentTypes.every((type) => activation?.documents.find((document) => document.type === type)?.status === "APPROVED");
  async function saveProfile(event: FormEvent) { event.preventDefault(); await api("/riders/me/onboarding/profile", { method: "PATCH", body: JSON.stringify(profile) }); setEditing(false); setMessage("Perfil actualizado."); load(); }
  async function pickDocument(type: DocumentType, side: "frontImage" | "backImage", file?: File) { if (!file) return; const image = await readImage(file); if (image.length > 700000) { setMessage("La imagen es demasiado grande. Usa una foto mas liviana."); return; } setPictures((current) => ({ ...current, [type]: { ...current[type], [side]: image } })); }
  async function submitDocuments() { const documents = documentTypes.map((type) => ({ type, ...pictures[type] })); if (documents.some((document) => !document.frontImage || !document.backImage)) { setMessage("Carga el frente y reverso de todos los documentos."); return; } await api("/riders/me/documents/submit", { method: "POST", body: JSON.stringify({ documents }) }); setMessage("Expediente enviado a validacion."); load(); }
  function detectZone() { if (!navigator.geolocation) { setMessage("Tu navegador no permite detectar ubicacion."); return; } navigator.geolocation.getCurrentPosition(async (position) => { try { setDetectedZone(await api("/riders/me/work-zone/detect", { method: "POST", body: JSON.stringify({ lat: position.coords.latitude, lng: position.coords.longitude }) })); } catch (cause) { setMessage((cause as Error).message); } }, () => setMessage("Activa el permiso de ubicacion para actualizar tu zona."), { enableHighAccuracy: true, timeout: 15000 }); }
  async function confirmZone() { if (!detectedZone) return; await api("/riders/me/work-zone", { method: "PATCH", body: JSON.stringify({ ...detectedZone, reason: activation?.workZoneConfigured ? "MANUAL_CHANGE" : "INITIAL" }) }); setDetectedZone(null); setMessage("Zona de trabajo actualizada."); load(); }

  return <Guard roles={["RIDER"]}><MobileAppShell role="RIDER">
    <h1 className="mt-4 text-2xl font-black tracking-tight">Mi cuenta rider</h1><p className="muted">{activation?.nextAction || "Cargando activacion..."}</p>
    <section className="mt-3 rounded-3xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-400">Estado operativo</p><b className="mt-1 block text-xl">{activation?.status?.replaceAll("_", " ") || "PENDIENTE"}</b><p className="mt-2 text-sm text-slate-300">Completa los pasos necesarios para trabajar con MotoYa.</p></section>
    <section className="card mt-3"><div className="flex justify-between"><div><b>Perfil y vehiculo</b><p className="muted">Tu tarjeta de presentacion</p></div>{activation?.profileComplete && !editing ? <button className="border py-2 text-sm" onClick={() => setEditing(true)}>Editar</button> : null}</div>
      {activation?.profileComplete && !editing ? <div className="moto-card mt-3 rounded-2xl p-4 text-white"><span className="moto-wheel">M</span><p className="text-xs font-bold uppercase text-orange-300">Moto registrada</p><b className="block text-xl">{profile.vehicleModel}</b><p className="mt-1 text-sm text-slate-200">Placa {profile.vehiclePlate} - Cedula {(profile.nationalId || "").slice(0, 4)}••••{(profile.nationalId || "").slice(-3)}</p><p className="text-sm text-slate-300">Licencia ••••{(profile.driverLicense || "").slice(-4)}</p></div> : <form className="mt-3 space-y-2" onSubmit={saveProfile}><input value={profile.nationalId || ""} onChange={(event) => setProfile({ ...profile, nationalId: event.target.value })} placeholder="Numero de cedula" required /><input value={profile.driverLicense || ""} onChange={(event) => setProfile({ ...profile, driverLicense: event.target.value })} placeholder="Numero de licencia" required /><input value={profile.vehiclePlate || ""} onChange={(event) => setProfile({ ...profile, vehiclePlate: event.target.value })} placeholder="Placa" required /><input value={profile.vehicleModel || ""} onChange={(event) => setProfile({ ...profile, vehicleModel: event.target.value })} placeholder="Marca y modelo" required /><button className="primary w-full">Guardar perfil</button></form>}
    </section>
    {approved ? <section className="card mt-3"><b>Documentacion aprobada</b><p className="muted mt-1">Tu expediente fue validado. No necesitas enviarlo nuevamente.</p><div className="mt-3 rounded-xl bg-emerald-50 p-3 font-semibold text-emerald-700">Expediente completo y protegido</div></section> : <section className="card mt-3"><b>Expediente documental</b><p className="muted mt-1">Carga frente y reverso de cada documento y envialos juntos.</p>{documentTypes.map((type) => { const document = activation?.documents.find((item) => item.type === type); const locked = Boolean(activation?.documentsSubmittedAt) && activation?.status === "UNDER_REVIEW"; return <div className="mt-3 rounded-xl border p-3" key={type}><div className="flex justify-between gap-2"><b>{documentNames[type]}</b><span className="text-xs">{document?.status || "PENDIENTE"}</span></div>{document?.rejectionReason ? <p className="text-sm text-red-700">{document.rejectionReason}</p> : null}<div className="mt-2 grid grid-cols-2 gap-2">{(["frontImage", "backImage"] as const).map((side) => <label className="relative grid h-24 place-items-center overflow-hidden rounded-xl border border-dashed text-center text-xs" key={side}>{pictures[type]?.[side] ? <img className="h-full w-full object-cover" src={pictures[type]?.[side]} alt={side} /> : <span>{side === "frontImage" ? "Frente" : "Reverso"}<br />Camara o galeria</span>}{!locked ? <input className="absolute inset-0 opacity-0" type="file" accept="image/*" capture="environment" onChange={(event) => pickDocument(type, side, event.target.files?.[0])} /> : null}</label>)}</div></div>; })}{activation?.documentsSubmittedAt && activation.status === "UNDER_REVIEW" ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Pendiente de validacion. El expediente no se puede modificar.</p> : <button className="primary mt-4 w-full" onClick={submitDocuments}>Enviar expediente a validacion</button>}</section>}
    <section className="work-zone-card mt-3 overflow-hidden rounded-3xl p-5 text-white"><div className="relative z-10 flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-300">Zona de trabajo</p><b className="mt-2 block text-2xl">{activation?.workZoneDepartment || "Sin zona confirmada"}</b><p className="mt-1 text-sm text-slate-300">{activation?.workZoneConfigured ? "Tu zona esta confirmada para recibir solicitudes." : "Detecta tu ubicacion para definir donde trabajas."}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${activation?.workZoneConfigured ? "bg-emerald-400/15 text-emerald-200" : "bg-white/10 text-slate-200"}`}>{activation?.workZoneConfigured ? "CONFIRMADA" : "PENDIENTE"}</span></div><div className="relative z-10 mt-5 grid grid-cols-2 gap-2"><button className="border border-white/20 bg-white/10 text-sm text-white" onClick={detectZone}>Detectar</button><button className="border border-orange-300/30 bg-orange-500 text-sm text-white" onClick={detectZone}>{activation?.workZoneConfigured ? "Cambiar zona" : "Usar ubicacion"}</button></div>{detectedZone ? <div className="relative z-10 mt-4 rounded-2xl border border-orange-300/20 bg-slate-950/45 p-4"><p className="text-xs text-slate-300">Ubicacion detectada</p><b className="mt-1 block text-lg">{detectedZone.department}</b><p className="mt-1 text-xs text-slate-400">Revisa el departamento antes de confirmarlo.</p><button className="primary mt-3 w-full" onClick={confirmZone}>Confirmar esta zona</button></div> : null}</section>
    {message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}<p className="muted mt-5 text-center">{getSession()?.user.email}</p>
  </MobileAppShell></Guard>;
}
