"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api, getSession } from "@/lib/api";

type DocumentType = "NATIONAL_ID" | "DRIVER_LICENSE" | "VEHICLE_REGISTRATION";
type Document = { type: DocumentType; status: string; frontImage?: string | null; backImage?: string | null; rejectionReason?: string | null };
type Activation = { status: string; profileComplete: boolean; documents: Document[]; documentsSubmittedAt?: string | null; workZoneConfigured: boolean; workZoneDepartment?: string | null; subscriptionActive: boolean; nextAction: string };
type Profile = { nationalId?: string | null; driverLicense?: string | null; vehiclePlate?: string | null; vehicleModel?: string | null };
type Images = Partial<Record<DocumentType, { frontImage?: string; backImage?: string }>>;
const types: DocumentType[] = ["NATIONAL_ID", "DRIVER_LICENSE", "VEHICLE_REGISTRATION"];
const documentNames: Record<DocumentType, string> = { NATIONAL_ID: "Cedula de identidad", DRIVER_LICENSE: "Licencia de conducir", VEHICLE_REGISTRATION: "Documento del vehiculo" };
const statusNames: Record<string, string> = { PROFILE_INCOMPLETE: "Completa tu perfil", DOCUMENTS_PENDING: "Documentos pendientes", UNDER_REVIEW: "En revision", REQUIRES_CORRECTION: "Requiere correccion", REJECTED: "Solicitud rechazada", SUBSCRIPTION_REQUIRED: "Suscripcion requerida", APPROVED: "Configura tu zona", READY_TO_WORK: "Listo para trabajar" };

async function compress(file: File) { const source = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); const image = new Image(); image.src = source; await new Promise((resolve, reject) => { image.onload = resolve; image.onerror = reject; }); const scale = Math.min(1, 1200 / Math.max(image.width, image.height)); const canvas = document.createElement("canvas"); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height); return canvas.toDataURL("image/jpeg", 0.72); }

export default function RiderAccountPage() {
  const [activation, setActivation] = useState<Activation | null>(null); const [profile, setProfile] = useState<Profile>({}); const [images, setImages] = useState<Images>({}); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [zone, setZone] = useState<{ department: string; lat: number; lng: number } | null>(null); const user = getSession()?.user;
  const load = () => Promise.all([api<Activation>("/riders/me/activation"), api<Profile>("/riders/me")]).then(([nextActivation, nextProfile]) => { setActivation(nextActivation); setProfile(nextProfile); setImages(Object.fromEntries(nextActivation.documents.map((document) => [document.type, { frontImage: document.frontImage || undefined, backImage: document.backImage || undefined }]))); }).catch((error) => setMessage(error.message));
  useEffect(() => { load(); }, []);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await api("/riders/me/onboarding/profile", { method: "PATCH", body: JSON.stringify(profile) }); setEditing(false); setMessage("Perfil guardado. Continua con tus documentos."); await load(); } catch (error) { setMessage((error as Error).message); } finally { setSaving(false); } };
  const chooseImage = async (type: DocumentType, side: "frontImage" | "backImage", file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) { setMessage("Selecciona una imagen valida."); return; } try { const value = await compress(file); if (value.length > 700000) { setMessage("La imagen sigue siendo muy grande. Usa una foto mas simple."); return; } setImages((current) => ({ ...current, [type]: { ...current[type], [side]: value } })); } catch { setMessage("No se pudo procesar la imagen."); } };
  const submitDocuments = async () => { const documents = types.map((type) => ({ type, frontImage: images[type]?.frontImage, backImage: images[type]?.backImage })); if (documents.some((document) => !document.frontImage || !document.backImage)) { setMessage("Carga frente y reverso de los tres documentos antes de enviar."); return; } setSaving(true); try { await api("/riders/me/documents/submit", { method: "POST", body: JSON.stringify({ documents }) }); setMessage("Expediente enviado. Queda pendiente de validacion."); await load(); } catch (error) { setMessage((error as Error).message); } finally { setSaving(false); } };
  const detectZone = () => navigator.geolocation?.getCurrentPosition(async (position) => { try { const detected = await api<{ department: string; lat: number; lng: number }>("/riders/me/work-zone/detect", { method: "POST", body: JSON.stringify({ lat: position.coords.latitude, lng: position.coords.longitude }) }); setZone(detected); } catch (error) { setMessage((error as Error).message); } }, () => setMessage("Necesitamos permiso de ubicacion para detectar tu departamento."), { enableHighAccuracy: true, timeout: 10000 });
  const reviewLocked = Boolean(activation?.documentsSubmittedAt && activation.status === "UNDER_REVIEW");
  return <Guard roles={["RIDER"]}><MobileAppShell role="RIDER"><h1 className="mt-4 text-2xl font-bold">Activacion de rider</h1><p className="muted">Completa cada paso una sola vez. Te diremos exactamente que falta.</p><section className="mt-3 rounded-3xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-orange-400">Estado actual</p><b className="mt-1 block text-xl">{statusNames[activation?.status || "PROFILE_INCOMPLETE"]}</b><p className="mt-2 text-sm text-slate-300">{activation?.nextAction || "Cargando estado..."}</p></section>
    <section className="card mt-3"><div className="flex items-center justify-between"><div><b>1. Perfil y vehiculo</b><p className="muted">Tu tarjeta de presentacion como rider.</p></div>{activation?.profileComplete && !editing ? <button className="border py-2 text-sm" onClick={() => setEditing(true)}>Editar</button> : null}</div>{activation?.profileComplete && !editing ? <div className="mt-3 rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase text-orange-400">Moto registrada</p><b className="mt-1 block text-lg">{profile.vehicleModel}</b><p className="mt-1 text-sm text-slate-300">Placa {profile.vehiclePlate} · Licencia terminada en {(profile.driverLicense || "").slice(-4)}</p></div> : <form className="mt-3 space-y-2" onSubmit={saveProfile}><input value={profile.nationalId || ""} onChange={(event) => setProfile({ ...profile, nationalId: event.target.value })} placeholder="Numero de cedula" required /><input value={profile.driverLicense || ""} onChange={(event) => setProfile({ ...profile, driverLicense: event.target.value })} placeholder="Numero de licencia" required /><input value={profile.vehiclePlate || ""} onChange={(event) => setProfile({ ...profile, vehiclePlate: event.target.value })} placeholder="Placa del vehiculo" required /><input value={profile.vehicleModel || ""} onChange={(event) => setProfile({ ...profile, vehicleModel: event.target.value })} placeholder="Marca y modelo" required /><button className="primary w-full" disabled={saving}>{saving ? "Guardando..." : "Guardar perfil"}</button></form>}</section>
    <section className="card mt-3"><b>2. Expediente documental</b><p className="muted mt-1">Carga frente y reverso. El expediente se envia una sola vez al terminar.</p>{types.map((type) => { const document = activation?.documents.find((item) => item.type === type); return <div className="mt-3 rounded-2xl border p-3" key={type}><div className="flex justify-between"><b>{documentNames[type]}</b><span className="text-xs font-bold text-slate-500">{document?.status || "PENDIENTE"}</span></div>{document?.rejectionReason ? <p className="mt-1 text-sm text-red-700">Correccion: {document.rejectionReason}</p> : null}<div className="mt-3 grid grid-cols-2 gap-2">{(["frontImage", "backImage"] as const).map((side) => <label className="relative grid min-h-24 cursor-pointer place-items-center overflow-hidden rounded-xl border border-dashed bg-slate-50 text-center text-xs font-semibold" key={side}>{images[type]?.[side] ? <img className="h-24 w-full object-cover" src={images[type]?.[side]} alt={`${documentNames[type]} ${side}`} /> : <span>{side === "frontImage" ? "Frente" : "Reverso"}<br /><small>Camara o galeria</small></span>}{!reviewLocked ? <input className="absolute inset-0 h-full opacity-0" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => chooseImage(type, side, event.target.files?.[0])} /> : null}</label>)}</div></div>; })}{!reviewLocked ? <button className="primary mt-4 w-full" disabled={saving} onClick={submitDocuments}>{saving ? "Enviando expediente..." : "Enviar expediente a validacion"}</button> : <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Expediente enviado. No puedes modificarlo mientras esta en revision.</p>}</section>
    <section className="card mt-3"><b>3. Zona de trabajo</b><p className="muted mt-1">Detectaremos automaticamente el departamento donde estas.</p>{activation?.workZoneConfigured ? <div className="mt-3 rounded-xl bg-emerald-50 p-3 text-emerald-800"><b>{activation.workZoneDepartment}</b><p className="text-sm">Zona confirmada</p></div> : <>{zone ? <div className="mt-3 rounded-xl bg-orange-50 p-3"><b>Departamento detectado: {zone.department}</b><button className="primary mt-3 w-full" onClick={async () => { await api("/riders/me/work-zone", { method: "PATCH", body: JSON.stringify(zone) }); await load(); }}>Confirmar esta zona</button></div> : <button className="border mt-3 w-full" onClick={detectZone}>Detectar mi departamento</button>}</>}</section>
    <section className="card mt-3"><div className="flex items-center justify-between"><div><b>4. Suscripcion</b><p className="muted">Necesaria despues de aprobar identidad.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${activation?.subscriptionActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{activation?.subscriptionActive ? "Activa" : "Pendiente"}</span></div><Link className="primary mt-3 block w-full text-center" href="/rider/subscription">Ver planes y pagos</Link></section>{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}<p className="muted mt-5 text-center">Cuenta: {user?.email}</p></MobileAppShell></Guard>;
}
