"use client";

import { useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Rider = { id: string; name: string; email: string; riderProfile: { approval: string; onboardingStatus?: string; subscriptions: { status: string }[] } };
type Document = { id: string; type: string; status: string; reference?: string | null; rejectionReason?: string | null };
export default function AdminRidersPage() { const [riders, setRiders] = useState<Rider[]>([]); const [selected, setSelected] = useState<string | null>(null); const [documents, setDocuments] = useState<Document[]>([]); const [message, setMessage] = useState(""); const load = () => api<Rider[]>("/admin/riders").then(setRiders).catch((error) => setMessage(error.message)); useEffect(() => { load(); }, []); const select = async (id: string) => { setSelected(id); try { setDocuments(await api<Document[]>(`/admin/riders/${id}/documents`)); } catch (error) { setMessage((error as Error).message); } }; const review = async (document: Document, status: string) => { const reason = status === "APPROVED" ? undefined : window.prompt("Motivo o correccion solicitada") || undefined; if (status !== "APPROVED" && !reason) return; await api(`/admin/riders/${selected}/documents/${document.id}`, { method: "PATCH", body: JSON.stringify({ status, reason }) }); if (selected) await select(selected); }; return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><h1 className="mt-4 text-2xl font-bold">Riders</h1><p className="muted">Revisa documentos antes de aprobar la cuenta.</p>{riders.map((rider) => <article className="card mt-3" key={rider.id}><button className="w-full p-0 text-left" onClick={() => select(rider.id)}><b>{rider.name}</b><p className="muted">{rider.email} · {rider.riderProfile.onboardingStatus || rider.riderProfile.approval}</p></button>{selected === rider.id ? <section className="mt-3 rounded-xl bg-slate-50 p-3"><b>Documentos</b>{documents.map((document) => <div className="mt-2 rounded-xl border bg-white p-3" key={document.id}><div className="flex justify-between"><span>{document.type}</span><b className="text-xs">{document.status}</b></div>{document.reference ? <a className="mt-1 block break-all text-sm text-orange-600 underline" target="_blank" rel="noreferrer" href={document.reference}>Abrir referencia</a> : null}{document.rejectionReason ? <p className="text-sm text-red-700">{document.rejectionReason}</p> : null}<div className="mt-2 flex gap-2"><button className="primary flex-1" onClick={() => review(document, "APPROVED")}>Aprobar</button><button className="border flex-1" onClick={() => review(document, "REQUIRES_CORRECTION")}>Corregir</button></div></div>)}{!documents.length ? <p className="muted mt-2">Aun no envio documentos.</p> : null}<button className="primary mt-3 w-full" onClick={async () => { await api(`/admin/riders/${rider.id}/status`, { method: "PATCH", body: JSON.stringify({ approval: "APPROVED" }) }); setMessage("Rider aprobado."); await load(); }}>Aprobar cuenta rider</button></section> : null}</article>)}{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>; }
