import * as Location from "expo-location";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Linking, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { api, connectSocket, getRoute, getSocket, isActiveTrip, login, logout, register, restoreSession, searchPlaces, setSession, tripPrice, type Advertisement, type Offer, type Place, type Quote, type Readiness, type Role, type Session, type Trip } from "../src/api";
import { TripMap } from "../src/components/TripMap";
import { RiderAccountScreen } from "../src/components/RiderAccountScreen";
import { theme } from "../src/theme";

const DEFAULT_PLACE: Place = { lat: 12.1364, lng: -86.2514, address: "Managua, Nicaragua" };
const ACTIVE = ["REQUESTED", "ACCEPTED", "RIDER_ON_THE_WAY", "RIDER_ARRIVED", "IN_PROGRESS"];
type Tab = "home" | "trip" | "places" | "history" | "account" | "work" | "earnings";

function Button({ title, onPress, tone = "primary", disabled = false }: { title: string; onPress: () => void; tone?: "primary" | "secondary" | "danger"; disabled?: boolean }) {
  return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, styles[`button_${tone}`], disabled && styles.buttonDisabled]}><Text style={[styles.buttonText, tone !== "primary" && styles.buttonTextDark]}>{title}</Text></Pressable>;
}
function Field({ label, value, onChangeText, placeholder, secret = false, numeric = false, visible = false, onToggleVisible }: { label: string; value: string; onChangeText: (next: string) => void; placeholder?: string; secret?: boolean; numeric?: boolean; visible?: boolean; onToggleVisible?: () => void }) {
  return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><View style={styles.inputWrap}><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#8F9AAF" secureTextEntry={secret && !visible} keyboardType={numeric ? "numeric" : "default"} autoCapitalize="none" autoCorrect={false} style={[styles.input, secret && styles.inputWithAction]} />{secret && onToggleVisible ? <Pressable accessibilityRole="button" accessibilityLabel={visible ? "Ocultar contraseña" : "Mostrar contraseña"} onPress={onToggleVisible} hitSlop={10} style={styles.passwordToggle}><Text style={styles.passwordToggleText}>{visible ? "◉" : "◌"}</Text></Pressable> : null}</View></View>;
}function Notice({ text }: { text: string }) { return text ? <View style={styles.notice}><Text style={styles.noticeText}>{text}</Text></View> : null; }
function StatusPill({ text, active = false }: { text: string; active?: boolean }) { return <View style={[styles.statusPill, active && styles.statusPillActive]}><Text style={[styles.statusPillText, active && styles.statusPillTextActive]}>{text}</Text></View>; }

function Auth({ onSession }: { onSession: (session: Session) => void }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [role, setRole] = useState<Exclude<Role, "ADMIN">>("CLIENT");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const submit = async () => {
    if (!email.trim() || !password) return setMessage("Ingresa tu correo y contraseña.");
    if (mode === "register" && !name.trim()) return setMessage("Ingresa tu nombre completo.");
    setBusy(true); setMessage("");
    try { const session = mode === "login" ? await login(email.trim(), password) : await register(role, name.trim(), email.trim(), password); await setSession(session); onSession(session); }
    catch (error) { setMessage((error as Error).message); } finally { setBusy(false); }
  };
  return <SafeAreaView style={styles.authSafe}><ScrollView contentContainerStyle={styles.authPage} keyboardShouldPersistTaps="handled">
    <View style={styles.authBanner}><Text style={styles.eyebrow}>MOTOYA</Text><Text style={styles.authHero}>Muévete rápido.{"\n"}<Text style={styles.orangeText}>Llega seguro.</Text></Text><Text style={styles.authSubtitle}>Una forma simple de pedir una moto o trabajar con independencia.</Text><View style={styles.routeDecoration}><Text style={styles.routeDecorationText}>● · · · ⚑</Text></View></View>
    <Text style={styles.eyebrow}>{mode === "login" ? "BIENVENIDO DE NUEVO" : "EMPIEZA HOY"}</Text><Text style={styles.authTitle}>{mode === "login" ? "Ingresa a tu cuenta" : "Crea tu cuenta"}</Text><Text style={styles.authSubtitle}>{mode === "login" ? "Usa tus datos para continuar de forma segura." : "Elige cómo quieres usar MotoYa."}</Text>
    <View style={styles.authCard}>{mode === "register" ? <><View style={styles.roleSwitch}><Pressable onPress={() => setRole("CLIENT")} style={[styles.roleOption, role === "CLIENT" && styles.roleOptionActive]}><Text style={[styles.roleText, role === "CLIENT" && styles.roleTextActive]}>Pasajero</Text></Pressable><Pressable onPress={() => setRole("RIDER")} style={[styles.roleOption, role === "RIDER" && styles.roleOptionActive]}><Text style={[styles.roleText, role === "RIDER" && styles.roleTextActive]}>Rider</Text></Pressable></View><Field label="Nombre completo" value={name} onChangeText={setName} placeholder="Como aparece en tu cédula" /></> : null}<Field label="Correo" value={email} onChangeText={setEmail} placeholder="nombre@correo.com" /><Field label="Contraseña" value={password} onChangeText={setPassword} placeholder="Tu contraseña" secret visible={showPassword} onToggleVisible={() => setShowPassword(value => !value)} /><Notice text={message} /><Button title={busy ? "Conectando…" : mode === "login" ? "Entrar a MotoYa  →" : `Continuar como ${role === "CLIENT" ? "pasajero" : "rider"}  →`} onPress={() => void submit()} disabled={busy} /></View>
    <Pressable onPress={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); setShowPassword(false); }}><Text style={styles.authFooter}>{mode === "login" ? "Primera vez en MotoYa? " : "Ya tienes una cuenta? "}<Text style={styles.orangeText}>{mode === "login" ? "Crea tu cuenta" : "Inicia sesión"}</Text></Text></Pressable>
  </ScrollView></SafeAreaView>;
}

function Header({ session, onLogout }: { session: Session; onLogout: () => void }) { return <View style={styles.header}><View><Text style={styles.headerBrand}>Moto<Text style={styles.orangeText}>Ya</Text></Text><Text style={styles.headerRole}>{session.user.role === "CLIENT" ? "PASAJERO" : "RIDER"}</Text></View><Pressable onPress={onLogout} style={styles.avatar}><Text style={styles.avatarText}>{session.user.name.slice(0, 2).toUpperCase()}</Text></Pressable></View>; }
function Tabs({ role, selected, onChange }: { role: Role; selected: Tab; onChange: (tab: Tab) => void }) {
  const items: Array<[Tab, string, string]> = role === "CLIENT" ? [["home", "⌂", "Inicio"], ["trip", "⌁", "Viaje"], ["places", "⌖", "Lugares"], ["history", "◴", "Historial"], ["account", "♙", "Cuenta"]] : [["work", "⌁", "Trabajo"], ["earnings", "◈", "Ganancias"], ["history", "◴", "Historial"], ["account", "♙", "Cuenta"]];
  return <View style={styles.tabs}>{items.map(([tab, icon, label]) => <Pressable key={tab} onPress={() => onChange(tab)} style={[styles.tab, selected === tab && styles.tabActive]}><Text style={[styles.tabIcon, selected === tab && styles.tabIconActive]}>{icon}</Text><Text style={[styles.tabLabel, selected === tab && styles.tabLabelActive]}>{label}</Text></Pressable>)}</View>;
}
function Shell({ session, tab, onTab, onLogout, children }: { session: Session; tab: Tab; onTab: (tab: Tab) => void; onLogout: () => void; children: React.ReactNode }) { return <SafeAreaView style={styles.safe}><Header session={session} onLogout={onLogout} /><View style={styles.main}>{children}</View><Tabs role={session.user.role} selected={tab} onChange={onTab} /></SafeAreaView>; }

function TripMeta({ trip }: { trip: Trip }) { return <View style={styles.tripMeta}><Text style={styles.tripAddress}>{trip.originAddress}</Text><Text style={styles.tripArrow}>↓</Text><Text style={styles.tripAddress}>{trip.destinationAddress}</Text><View style={styles.tripMetaFooter}><Text style={styles.metaText}>{trip.distanceKm.toFixed(1)} km · {trip.estimatedDurationMin} min</Text><Text style={styles.tripPrice}>{trip.currency} {tripPrice(trip)}</Text></View></View>; }

function useRoute(from?: Place | null, to?: Place | null) {
  const [route, setRoute] = useState<Place[]>([]);
  useEffect(() => { let live = true; if (!from || !to) { setRoute([]); return; } void getRoute(from, to).then(result => { if (live) setRoute(result.points); }).catch(() => { if (live) setRoute([from, to]); }); return () => { live = false; }; }, [from?.lat, from?.lng, to?.lat, to?.lng]);
  return route;
}
function useTripRealtime(trip: Trip | null, onTrip: (trip: Trip) => void, onOffer?: (offer: Offer) => void) {
  useEffect(() => {
    if (!trip) return;
    let active = true; const refresh = () => { void api<Trip>(`/trips/${trip.id}`).then(next => active && onTrip(next)).catch(() => undefined); };
    const interval = setInterval(refresh, 10_000); refresh();
    void connectSocket().then(socket => { if (!socket) return; socket.on("trip:status-updated", onTrip); socket.on("trip:accepted", onTrip); socket.on("trip:tracking-updated", refresh); socket.on("trip:location-updated", refresh); if (onOffer) socket.on("trip:offer", onOffer); });
    return () => { active = false; clearInterval(interval); const socket = getSocket(); socket?.off("trip:status-updated", onTrip); socket?.off("trip:accepted", onTrip); socket?.off("trip:tracking-updated", refresh); socket?.off("trip:location-updated", refresh); if (onOffer) socket?.off("trip:offer", onOffer); };
  }, [trip?.id]);
}

function ClientHome({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("home"); const [places, setPlaces] = useState<Place[]>([]); const [ads, setAds] = useState<Advertisement[]>([]); const [message, setMessage] = useState(""); const [activeTrip, setActiveTrip] = useState<Trip | null>(null);
  const [origin, setOrigin] = useState<Place>(DEFAULT_PLACE); const [destination, setDestination] = useState<Place | null>(null); const [locating, setLocating] = useState(false);
  const load = useCallback(async () => { try { const [saved, advertisements, trips] = await Promise.all([api<Array<Place & { label: string }>>("/places"), api<Advertisement[]>("/advertisements"), api<Trip[]>("/trips")]); setPlaces(saved); setAds(advertisements); setActiveTrip(trips.find(item => ACTIVE.includes(item.status)) || null); } catch (error) { setMessage((error as Error).message); } }, []);
  useEffect(() => { void load(); void connectSocket(); }, []);
  const locate = async () => { setLocating(true); try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") return setMessage("Permite la ubicación para usar el origen actual."); const point = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setOrigin({ lat: point.coords.latitude, lng: point.coords.longitude, address: "Ubicación actual" }); setMessage("Ubicación actualizada. Ya puedes elegir el destino."); } catch { setMessage("No fue posible obtener tu ubicación. Puedes corregir el origen manualmente."); } finally { setLocating(false); } };
  useEffect(() => { void locate(); }, []);
  useTripRealtime(activeTrip, next => { if (isActiveTrip(next.status)) setActiveTrip(next); else { setActiveTrip(null); setMessage(next.status === "COMPLETED" ? "Viaje finalizado. Gracias por viajar con MotoYa." : "El viaje fue cancelado."); } });
  const content = () => {
    if (tab === "trip") return <ClientTrip session={session} active={activeTrip} onActive={setActiveTrip} origin={origin} destination={destination} onOrigin={setOrigin} onDestination={setDestination} saved={places} onMessage={setMessage} />;
    if (tab === "places") return <SavedPlaces places={places} onSelect={place => { setDestination(place); setTab("trip"); }} onRefresh={load} onMessage={setMessage} />;
    if (tab === "history") return <TripHistory role="CLIENT" onMessage={setMessage} />;
    if (tab === "account") return <ClientAccount session={session} onLogout={onLogout} />;
    return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><Text style={styles.eyebrow}>MOTOYA · PASAJERO</Text><Text style={styles.pageTitle}>¡Hola, {session.user.name.split(" ")[0]}!</Text><Text style={styles.pageSubtitle}>Pide una moto, consulta tus lugares o revisa tus viajes.</Text>{ads.length ? <View style={styles.homeAds}><Text style={styles.homeSectionEyebrow}>NOVEDADES</Text><Text style={styles.homeSectionTitle}>Lo nuevo para ti</Text><AdCarousel ads={ads} /></View> : null}<Pressable onPress={() => setTab("trip")} style={styles.searchHero}><View style={styles.searchGlyph}><Text style={styles.searchGlyphText}>⌁</Text></View><View style={{ flex: 1 }}><Text style={styles.searchHeroTitle}>Buscar un viaje</Text><Text style={styles.searchHeroText}>Rápido, seguro y cercano</Text></View><Text style={styles.searchHeroArrow}>→</Text></Pressable><View style={styles.passengerZone}><View style={styles.zoneIcon}><Text style={styles.zoneIconText}>⌖</Text></View><View style={{ flex: 1 }}><Text style={styles.passengerZoneLabel}>ZONA DE SERVICIO</Text><Text style={styles.passengerZoneTitle}>{origin.address}</Text><Text style={styles.passengerZoneText}>Este será el origen de tu próximo viaje.</Text></View><Pressable onPress={() => void locate()} disabled={locating} style={styles.locateButton}><Text style={styles.locateButtonText}>{locating ? "…" : "Actualizar"}</Text></Pressable></View><Text style={styles.sectionTitle}>Accesos rápidos</Text><View style={styles.quickGrid}><QuickCard icon="⌁" title="Nuevo viaje" subtitle="Elige origen y destino" onPress={() => setTab("trip")} /><QuickCard icon="⌖" title="Lugares" subtitle="Casa, trabajo y favoritos" onPress={() => setTab("places")} /><QuickCard icon="◴" title="Historial" subtitle="Consulta tus viajes" onPress={() => setTab("history")} /></View>{activeTrip ? <Pressable onPress={() => setTab("trip")} style={styles.activeStrip}><Text style={styles.activeStripTitle}>Tienes un viaje activo</Text><Text style={styles.activeStripText}>Ver seguimiento en vivo →</Text></Pressable> : null}</ScrollView>;
  };
  return <Shell session={session} tab={tab} onTab={setTab} onLogout={onLogout}><Notice text={message} />{content()}</Shell>;
}
function AdCarousel({ ads }: { ads: Advertisement[] }) { const [index, setIndex] = useState(0); const ad = ads[index % ads.length]; return <View><Pressable onPress={() => setIndex(current => (current + 1) % ads.length)} style={[styles.ad, { backgroundColor: ad.backgroundColor }]}><Text style={[styles.adEyebrow, { color: ad.textColor }]}>MOTOYA TE INFORMA</Text><Text style={[styles.adTitle, { color: ad.textColor }]}>{ad.title}</Text>{ad.description ? <Text style={[styles.adText, { color: ad.textColor }]}>{ad.description}</Text> : null}<Text style={[styles.adAction, { color: ad.textColor }]}>{ad.actionLabel || "Ver novedad"}  →</Text></Pressable><View style={styles.dots}>{ads.map((item, itemIndex) => <View key={item.id} style={[styles.dot, itemIndex === index % ads.length && styles.dotActive]} />)}</View></View>; }
function QuickCard({ icon, title, subtitle, onPress }: { icon: string; title: string; subtitle: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.quickCard}><Text style={styles.quickIcon}>{icon}</Text><Text style={styles.quickTitle}>{title}</Text><Text style={styles.quickSub}>{subtitle}</Text></Pressable>; }

function ClientTrip({ active, onActive, origin, destination, onOrigin, onDestination, saved, onMessage }: { session: Session; active: Trip | null; onActive: (trip: Trip | null) => void; origin: Place; destination: Place | null; onOrigin: (place: Place) => void; onDestination: (place: Place | null) => void; saved: Place[]; onMessage: (message: string) => void }) {
  const [stage, setStage] = useState<"ROUTE" | "QUOTE" | "REVIEW">("ROUTE");
  const [query, setQuery] = useState(destination?.address || ""); const [results, setResults] = useState<Place[]>([]); const [selection, setSelection] = useState<"destination" | "stop">("destination");
  const [quote, setQuote] = useState<Quote | null>(null); const [fare, setFare] = useState(""); const [notes, setNotes] = useState(""); const [stops, setStops] = useState<Place[]>([]); const [offers, setOffers] = useState<Offer[]>([]); const [busy, setBusy] = useState(false); const [panelOpen, setPanelOpen] = useState(true);
  const tripOrigin = active ? { lat: active.originLat, lng: active.originLng, address: active.originAddress } : origin;
  const tripDestination = active ? { lat: active.destinationLat, lng: active.destinationLng, address: active.destinationAddress } : destination;
  const riderPosition = active?.riderLat != null && active?.riderLng != null ? { lat: active.riderLat, lng: active.riderLng, address: "Ubicacion del rider" } : null;
  const riderApproaching = active?.status === "ACCEPTED" || active?.status === "RIDER_ON_THE_WAY" || active?.status === "RIDER_ARRIVED";
  const route = useRoute(riderApproaching && riderPosition ? riderPosition : tripOrigin, riderApproaching ? tripOrigin : tripDestination);
  useTripRealtime(active, next => { if (isActiveTrip(next.status)) onActive(next); else onActive(null); }, offer => setOffers(current => current.some(item => item.id === offer.id) ? current : [offer, ...current]));
  useEffect(() => { if (!active || active.status !== "REQUESTED") return; void api<Offer[]>(`/trips/${active.id}/offers`).then(setOffers).catch(() => undefined); }, [active?.id, active?.status]);
  const search = async () => { if (query.trim().length < 3) return onMessage("Escribe al menos tres caracteres para buscar."); setBusy(true); try { setResults(await searchPlaces(query)); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const selectPlace = (place: Place) => { if (selection === "stop") { if (stops.length >= 3) return onMessage("Puedes agregar hasta tres paradas."); setStops(current => [...current, place]); } else { onDestination(place); setQuote(null); setFare(""); } setQuery(place.address); setResults([]); setSelection("destination"); };
  const estimate = async () => { if (!destination) return onMessage("Selecciona un destino para calcular la tarifa."); setBusy(true); try { setQuote(await api<Quote>("/trips/estimate", { method: "POST", body: JSON.stringify({ origin, destination, stops, serviceCode: "MOTO" }) })); setStage("QUOTE"); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const amount = fare ? Number(fare) : undefined;
  const continueToReview = () => { if (!quote) return; if (amount && (amount < quote.minimumFare || amount > quote.maximumFare)) return onMessage(`Propón una tarifa entre ${quote.minimumFare} y ${quote.maximumFare} ${quote.currency}.`); setStage("REVIEW"); };
  const request = async () => { if (!destination || !quote) return; setBusy(true); try { const trip = await api<Trip>("/trips", { method: "POST", body: JSON.stringify({ origin, destination, stops, serviceCode: "MOTO", proposedPrice: amount, notes: notes.trim() || undefined }) }); onActive(trip); setStage("ROUTE"); setQuote(null); setPanelOpen(true); onMessage("Solicitud enviada a riders cercanos."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const acceptOffer = (offer: Offer) => Alert.alert("Aceptar oferta", `¿Asignar el viaje a ${offer.rider.name} por ${offer.currency} ${offer.amount}?`, [{ text: "Revisar", style: "cancel" }, { text: "Aceptar", onPress: () => void (async () => { if (!active) return; setBusy(true); try { onActive(await api<Trip>(`/trips/${active.id}/offers/${offer.id}/accept`, { method: "POST" })); setOffers([]); onMessage("Rider asignado. Ya va hacia tu origen."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } })() }]);
  const rejectOffer = async (offer: Offer) => { if (!active) return; try { await api(`/trips/${active.id}/offers/${offer.id}/reject`, { method: "POST" }); setOffers(current => current.filter(item => item.id !== offer.id)); } catch (error) { onMessage((error as Error).message); } };
  const cancel = () => { if (!active) return; Alert.alert("Cancelar viaje", "¿Deseas cancelar esta solicitud?", [{ text: "No", style: "cancel" }, { text: "Si, cancelar", style: "destructive", onPress: () => void api(`/trips/${active.id}/cancel`, { method: "POST", body: JSON.stringify({ reason: "Cancelado por el pasajero" }) }).then(() => onActive(null)).catch(error => onMessage((error as Error).message)) }]); };
  const complete = async () => { if (!active) return; setBusy(true); try { const completed = await api<Trip>(`/trips/${active.id}/complete`, { method: "POST" }); onActive(null); onMessage(`Viaje finalizado. Pago en efectivo: ${completed.currency} ${tripPrice(completed)}.`); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  if (active) return <View style={styles.fullScreen}><TripMap trip={active} route={route} label={active.status === "REQUESTED" ? "Buscando riders cercanos" : active.status === "IN_PROGRESS" ? "Tu rider te lleva al destino" : "Tu rider va hacia tu ubicacion"} height={panelOpen ? 355 : 560} /><View style={[styles.bottomPanel, !panelOpen && styles.bottomPanelCollapsed]}><Pressable onPress={() => setPanelOpen(value => !value)} style={styles.panelHandle}><View style={styles.handle} /><Text style={styles.panelHandleText}>{panelOpen ? "Ocultar informacion del viaje" : "Ver informacion del viaje"}</Text><Text style={styles.panelHandleText}>{panelOpen ? "⌄" : "⌃"}</Text></Pressable>{panelOpen ? <><Text style={styles.eyebrow}>VIAJE ACTUAL · {active.status.replaceAll("_", " ")}</Text><Text style={styles.panelTitle}>{active.status === "REQUESTED" ? "Buscando riders cercanos" : active.status === "RIDER_ARRIVED" ? "Tu rider ya llego" : active.status === "IN_PROGRESS" ? "Vas rumbo al destino" : "Tu rider esta en camino"}</Text>{active.rider ? <Text style={styles.panelSub}>{active.rider.name} · {active.rider.riderProfile?.vehicleModel || "Moto"} · {active.rider.riderProfile?.vehiclePlate || "placa pendiente"}</Text> : <Text style={styles.panelSub}>Recibiras una oferta o aceptacion cuando haya disponibilidad.</Text>}<TripMeta trip={active} />{active.status === "REQUESTED" ? <>{offers.length ? offers.map(offer => <View style={styles.offerCard} key={offer.id}><View><Text style={styles.offerName}>{offer.rider.name}</Text><Text style={styles.offerPrice}>{offer.currency} {offer.amount}</Text></View><View><Button title={busy ? "..." : "Elegir"} onPress={() => acceptOffer(offer)} disabled={busy} /><Pressable onPress={() => void rejectOffer(offer)}><Text style={styles.placeDelete}>Rechazar</Text></Pressable></View></View>) : <Text style={styles.liveLabel}>Buscando riders operativos en tu zona…</Text>}<Button title="Cancelar solicitud" onPress={cancel} tone="secondary" /></> : active.status === "IN_PROGRESS" ? <Button title={busy ? "Finalizando…" : "Confirmar llegada y pago"} onPress={() => void complete()} disabled={busy} /> : <><Text style={styles.liveLabel}>● Ubicacion del rider actualizada en vivo</Text><Button title="Cancelar viaje" onPress={cancel} tone="secondary" /></>}</> : null}</View></View>;
  if (stage === "QUOTE" && quote) return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>VIAJE MOTO · PASO 2 DE 3</Text><Text style={styles.pageTitle}>Elige tu tarifa</Text><TripMap origin={origin} destination={destination || undefined} route={route} label="Ruta estimada" /><View style={styles.quoteCard}><Text style={styles.eyebrow}>MOTO · 1 PASAJERO · EFECTIVO</Text><Text style={styles.quotePrice}>{quote.currency} {fare || quote.estimatedPrice}</Text><Text style={styles.quoteDescription}>{quote.distanceKm.toFixed(1)} km · {quote.estimatedDurationMin} min · precio estimado</Text><Field label={`Tarifa propuesta opcional (${quote.minimumFare} a ${quote.maximumFare})`} value={fare} onChangeText={setFare} placeholder={`Usar ${quote.estimatedPrice}`} numeric /><Button title="Continuar a confirmacion" onPress={continueToReview} /></View><Button title="Volver a editar ruta" tone="secondary" onPress={() => setStage("ROUTE")} /></ScrollView>;
  if (stage === "REVIEW" && quote) return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>CONFIRMACION · PASO 3 DE 3</Text><Text style={styles.pageTitle}>Revisa tu viaje</Text><View style={styles.card}><TripMeta trip={{ id: "preview", status: "PREVIEW", originAddress: origin.address, destinationAddress: destination?.address || "", originLat: origin.lat, originLng: origin.lng, destinationLat: destination?.lat || 0, destinationLng: destination?.lng || 0, estimatedPrice: String(quote.estimatedPrice), currency: quote.currency, distanceKm: quote.distanceKm, estimatedDurationMin: quote.estimatedDurationMin, proposedPrice: amount ? String(amount) : null }} /><Text style={styles.accountHintDark}>Moto · 1 pasajero · Pago en efectivo al rider</Text>{stops.map((stop, index) => <Text key={`${stop.lat}-${stop.lng}`} style={styles.placeAddress}>Parada {index + 1}: {stop.address}</Text>)}{notes ? <Text style={styles.placeAddress}>Instrucciones: {notes}</Text> : null}</View><View style={styles.quoteCard}><Text style={styles.eyebrow}>TARIFA A PUBLICAR</Text><Text style={styles.quotePrice}>{quote.currency} {amount || quote.estimatedPrice}</Text><Text style={styles.quoteDescription}>El precio puede cambiar si modificas la ruta.</Text></View><Button title={busy ? "Publicando…" : "Confirmar y pedir moto"} onPress={() => void request()} disabled={busy} /><Button title="Volver a tarifa" tone="secondary" onPress={() => setStage("QUOTE")} /></ScrollView>;
  return <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>VIAJE MOTO · PASO 1 DE 3</Text><Text style={styles.pageTitle}>¿A donde te llevamos?</Text><Text style={styles.pageSubtitle}>Confirma origen, destino y detalles antes de conocer la tarifa.</Text><View style={styles.routeCard}><Text style={styles.routeLabel}>ORIGEN</Text><TextInput value={origin.address} onChangeText={address => { onOrigin({ ...origin, address }); setQuote(null); }} style={styles.routeInput} /><Text style={styles.routeConnector}>│</Text><Text style={styles.routeLabel}>DESTINO</Text><TextInput value={query} onChangeText={setQuery} placeholder="Buscar destino" placeholderTextColor="#8F9AAF" style={styles.routeInput} /><Button title={busy ? "Buscando…" : "Buscar destino"} onPress={() => void search()} tone="secondary" disabled={busy} />{results.map(result => <Pressable key={`${result.lat}-${result.lng}`} onPress={() => selectPlace(result)} style={styles.result}><Text style={styles.resultTitle}>{result.address}</Text></Pressable>)}{saved.length ? <View style={styles.savedLine}><Text style={styles.savedLabel}>Lugares guardados</Text>{saved.slice(0, 3).map(place => <Pressable key={`${place.lat}-${place.lng}`} onPress={() => selectPlace(place)}><Text style={styles.savedChip}>{place.label || place.address}</Text></Pressable>)}</View> : null}</View><TripMap origin={origin} destination={destination || undefined} route={route} editable onMapPress={selectPlace} label="Toca el mapa para ajustar el destino" />{destination ? <View style={styles.card}><View style={styles.rowBetween}><Text style={styles.placeTitle}>Paradas intermedias</Text><Pressable onPress={() => { setSelection("stop"); setQuery(""); setResults([]); }}><Text style={styles.placeEdit}>Agregar parada</Text></Pressable></View>{selection === "stop" ? <><TextInput value={query} onChangeText={setQuery} placeholder="Busca una parada" placeholderTextColor="#8F9AAF" style={styles.input} /><Button title="Buscar parada" onPress={() => void search()} tone="secondary" /></> : null}{stops.map((stop, index) => <View key={`${stop.lat}-${stop.lng}`} style={styles.rowBetween}><Text style={styles.placeAddress}>{index + 1}. {stop.address}</Text><Pressable onPress={() => setStops(current => current.filter((_, item) => item !== index))}><Text style={styles.placeDelete}>Quitar</Text></Pressable></View>)}<Field label="Instrucciones para el rider" value={notes} onChangeText={setNotes} placeholder="Ej. Estoy frente a la farmacia" /></View> : null}<Button title={busy ? "Calculando…" : "Ver tarifa de Moto"} onPress={() => void estimate()} disabled={busy || !destination} /></ScrollView>;
}
function SavedPlaces({ places, onSelect, onRefresh, onMessage }: { places: Array<Place & { label?: string }>; onSelect: (place: Place) => void; onRefresh: () => Promise<void>; onMessage: (message: string) => void }) {
  const [label, setLabel] = useState(""); const [address, setAddress] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const save = async () => { if (!label.trim() || !address.trim()) return onMessage("Ingresa un alias y una dirección para guardar el lugar."); setBusy(true); try { const results = await searchPlaces(address); const place = results[0]; if (!place) throw new Error("No encontramos esa dirección."); await api(`/places/${encodeURIComponent(editing || label.trim())}`, { method: "PUT", body: JSON.stringify({ ...place }) }); setLabel(""); setAddress(""); setEditing(null); await onRefresh(); onMessage("Destino guardado."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const remove = (place: Place & { label?: string }) => Alert.alert("Eliminar lugar", `¿Eliminar ${place.label || "este lugar"}?`, [{ text: "No", style: "cancel" }, { text: "Eliminar", style: "destructive", onPress: () => void api(`/places/${encodeURIComponent(place.label || "")}`, { method: "DELETE" }).then(onRefresh).catch(error => onMessage((error as Error).message)) }]);
  return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>LUGARES</Text><Text style={styles.pageTitle}>Destinos guardados</Text><Text style={styles.pageSubtitle}>Guarda casa, trabajo o cualquier punto con un nombre propio.</Text><View style={styles.card}><Field label="Alias" value={label} onChangeText={setLabel} placeholder="Ej. Gimnasio" /><Field label="Dirección" value={address} onChangeText={setAddress} placeholder="Busca una dirección" /><Button title={busy ? "Guardando…" : editing ? "Actualizar lugar" : "Guardar lugar"} onPress={() => void save()} disabled={busy} />{editing ? <Button title="Cancelar edición" tone="secondary" onPress={() => { setEditing(null); setLabel(""); setAddress(""); }} /> : null}</View>{places.map(place => <View key={`${place.label}-${place.lat}-${place.lng}`} style={styles.placeCard}><Pressable onPress={() => onSelect(place)} style={{ flex: 1, flexDirection: "row", alignItems: "center", gap: 12 }}><View style={styles.placeIcon}><Text>⌖</Text></View><View style={{ flex: 1 }}><Text style={styles.placeTitle}>{place.label || "Lugar guardado"}</Text><Text style={styles.placeAddress}>{place.address}</Text></View></Pressable><View><Pressable onPress={() => { setEditing(place.label || ""); setLabel(place.label || ""); setAddress(place.address); }}><Text style={styles.placeEdit}>Editar</Text></Pressable><Pressable onPress={() => remove(place)}><Text style={styles.placeDelete}>Eliminar</Text></Pressable></View></View>)}</ScrollView>;
}
function TripHistory({ role, onMessage }: { role: Role; onMessage: (message: string) => void }) { const [trips, setTrips] = useState<Trip[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { void api<Trip[]>("/trips").then(setTrips).catch(error => onMessage((error as Error).message)).finally(() => setLoading(false)); }, []); return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>HISTORIAL</Text><Text style={styles.pageTitle}>Tus viajes</Text><Text style={styles.pageSubtitle}>Consulta los trayectos y pagos en efectivo registrados.</Text>{loading ? <ActivityIndicator color={theme.orange} /> : trips.map(trip => <View style={styles.historyCard} key={trip.id}><View style={styles.rowBetween}><StatusPill text={trip.status.replaceAll("_", " ")} active={trip.status === "COMPLETED"} /><Text style={styles.historyPrice}>{trip.currency} {tripPrice(trip)}</Text></View><Text style={styles.historyAddress}>{trip.originAddress}</Text><Text style={styles.historyArrow}>↓</Text><Text style={styles.historyAddress}>{trip.destinationAddress}</Text></View>)}{!loading && !trips.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>Aún no hay viajes</Text><Text style={styles.pageSubtitle}>Tu actividad aparecerá aquí cuando realices el primer viaje.</Text></View> : null}</ScrollView>; }
function Account({ session, onLogout }: { session: Session; onLogout: () => void }) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>CUENTA</Text><Text style={styles.pageTitle}>Hola, {session.user.name.split(" ")[0]}</Text><View style={styles.accountHero}><Text style={styles.accountRole}>{session.user.role === "CLIENT" ? "PASAJERO" : "RIDER"}</Text><Text style={styles.accountEmail}>{session.user.email}</Text><Text style={styles.accountHint}>{session.user.role === "CLIENT" ? "Tu cuenta está activa para solicitar viajes." : "Gestiona documentos, zona y suscripción desde la web mientras migramos estas secciones."}</Text></View><Button title="Cerrar sesión" tone="secondary" onPress={onLogout} /></ScrollView>; }

function ClientAccount({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [profile, setProfile] = useState<{ phone?: string | null; status?: string; clientProfile?: { activationStatus?: string } | null } | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { void api<{ phone?: string | null; status?: string; clientProfile?: { activationStatus?: string } | null }>("/auth/me").then(setProfile).catch(error => setMessage((error as Error).message)); }, []);
  return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>CUENTA</Text><Text style={styles.pageTitle}>Hola, {session.user.name.split(" ")[0]}</Text><View style={styles.accountHero}><Text style={styles.accountRole}>PASAJERO</Text><Text style={styles.accountEmail}>{session.user.email}</Text><Text style={styles.accountHint}>Tu cuenta está activa para solicitar viajes. La verificación de identidad es opcional por ahora.</Text></View><View style={styles.card}><Text style={styles.placeTitle}>Estado de activación</Text><View style={styles.rowBetween}><StatusPill text={profile?.clientProfile?.activationStatus || profile?.status || "ACTIVA"} active /><Text style={styles.placeAddress}>{profile?.phone || "Teléfono pendiente"}</Text></View><Text style={styles.accountHintDark}>Puedes guardar destinos, solicitar viajes y administrar tu historial desde la aplicación.</Text></View><Notice text={message} /><Button title="Cerrar sesión" tone="secondary" onPress={onLogout} /></ScrollView>;
}

function RiderHome({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("work"); const [available, setAvailable] = useState(false); const [readiness, setReadiness] = useState<Readiness>({ ready: false }); const [current, setCurrent] = useState<Place | null>(null); const [requests, setRequests] = useState<Trip[]>([]); const [activeTrip, setActiveTrip] = useState<Trip | null>(null); const [message, setMessage] = useState(""); const [requestOpen, setRequestOpen] = useState(false);
  const load = useCallback(async () => { try { const [profile, ready, trips] = await Promise.all([api<{ available: boolean }>("/riders/me"), api<Readiness>("/riders/me/readiness"), api<Trip[]>("/trips")]); setAvailable(profile.available); setReadiness(ready); const active = trips.find(item => ACTIVE.includes(item.status)); setActiveTrip(active || null); if (ready.ready && profile.available && !active) setRequests(await api<Trip[]>("/riders/available-trips")); } catch (error) { setMessage((error as Error).message); } }, []);
  useEffect(() => { let live = true; const receive = () => void load(); void load(); void connectSocket().then(socket => { if (live) socket?.on("trip:requested", receive); }); return () => { live = false; getSocket()?.off("trip:requested", receive); }; }, []);
  useTripRealtime(activeTrip, next => { if (isActiveTrip(next.status)) setActiveTrip(next); else { setActiveTrip(null); void load(); } });
  useEffect(() => { let subscription: Location.LocationSubscription | null = null; if (!available && !activeTrip) return; void Location.requestForegroundPermissionsAsync().then(permission => { if (permission.status !== "granted") { setMessage("Activa el permiso de ubicación para trabajar."); return; } return Location.watchPositionAsync({ accuracy: Location.Accuracy.High, timeInterval: 8_000, distanceInterval: 8 }, location => { const point = { lat: location.coords.latitude, lng: location.coords.longitude, address: "Tu ubicación", accuracy: location.coords.accuracy ?? undefined, heading: location.coords.heading ?? undefined, capturedAt: new Date(location.timestamp).toISOString() }; setCurrent(point); const path = activeTrip ? `/trips/${activeTrip.id}/location` : "/riders/me/location"; void api(path, { method: "PATCH", body: JSON.stringify(point) }).catch(() => undefined); }).then(next => { subscription = next; }); }).catch(() => setMessage("No se pudo activar el GPS.")); return () => subscription?.remove(); }, [available, activeTrip?.id]);
  const toggle = async () => { try { await api("/riders/me/availability", { method: "PATCH", body: JSON.stringify({ available: !available }) }); await load(); } catch (error) { setMessage((error as Error).message); } };
  const content = () => { if (tab === "earnings") return <RiderEarnings onMessage={setMessage} />; if (tab === "history") return <TripHistory role="RIDER" onMessage={setMessage} />; if (tab === "account") return <RiderAccountScreen session={session} onMessage={setMessage} />; return <RiderWork available={available} ready={readiness} current={current} active={activeTrip} requests={requests} onToggle={toggle} onActive={setActiveTrip} onRequests={() => setRequestOpen(true)} onManageZone={() => setTab("account")} onMessage={setMessage} />; };
  return <Shell session={session} tab={tab} onTab={setTab} onLogout={onLogout}><Notice text={message} />{content()}<RequestsModal visible={requestOpen} requests={requests} onClose={() => setRequestOpen(false)} onActive={setActiveTrip} onMessage={setMessage} /></Shell>;
}
function RiderWork({ available, ready, current, active, requests, onToggle, onActive, onRequests, onManageZone, onMessage }: { available: boolean; ready: Readiness; current: Place | null; active: Trip | null; requests: Trip[]; onToggle: () => void; onActive: (trip: Trip | null) => void; onRequests: () => void; onManageZone: () => void; onMessage: (message: string) => void }) {
  const routeTarget = active?.status === "IN_PROGRESS" ? { lat: active.destinationLat, lng: active.destinationLng, address: active.destinationAddress } : active ? { lat: active.originLat, lng: active.originLng, address: active.originAddress } : null;
  const route = useRoute(current, routeTarget); const [panelOpen, setPanelOpen] = useState(true); const [busy, setBusy] = useState(false);
  const nextFor = (status: string) => status === "ACCEPTED" ? "RIDER_ON_THE_WAY" : status === "RIDER_ON_THE_WAY" ? "RIDER_ARRIVED" : status === "RIDER_ARRIVED" ? "IN_PROGRESS" : null;
  const actionFor = (status: string) => status === "ACCEPTED" ? "Iniciar ruta al pasajero" : status === "RIDER_ON_THE_WAY" ? "Recoger pasajero" : status === "RIDER_ARRIVED" ? "Iniciar viaje al destino" : "";
  const advance = async (next?: string) => { if (!active) return; const status = next || nextFor(active.status); if (!status) return; setBusy(true); try { const updated = await api<Trip>(`/trips/${active.id}/status`, { method: "PATCH", body: JSON.stringify({ status, location: current ? { lat: current.lat, lng: current.lng, accuracy: (current as Place & { accuracy?: number }).accuracy } : undefined }) }); onActive(updated); setPanelOpen(true); onMessage(updated.status === "IN_PROGRESS" ? "Pasajero a bordo. Ya vas rumbo al destino." : updated.status === "RIDER_ARRIVED" ? "Recogida confirmada. Inicia el viaje al destino." : "Ruta al pasajero iniciada."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const cancel = () => { if (!active) return; Alert.alert("Cancelar por incidencia", "El viaje se liberará nuevamente si aún no iniciaste la ruta. ¿Continuar?", [{ text: "No", style: "cancel" }, { text: "Cancelar viaje", style: "destructive", onPress: () => void api(`/trips/${active.id}/cancel`, { method: "POST", body: JSON.stringify({ reason: "Incidencia reportada por rider" }) }).then(() => onActive(null)).catch(error => onMessage((error as Error).message)) }]); };
  const finish = async () => { if (!active) return; setBusy(true); try { const completed = await api<Trip>(`/trips/${active.id}/complete`, { method: "POST" }); onActive(null); onMessage(`Viaje finalizado. Cobro en efectivo: ${completed.currency} ${tripPrice(completed)}.`); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  if (!ready.ready) return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>ZONA DE TRABAJO</Text><Text style={styles.pageTitle}>Aún no puedes conectarte</Text><View style={styles.blockersCard}><Text style={styles.blockersTitle}>Completa estos requisitos</Text>{ready.blockers?.map(blocker => <Text key={blocker.code} style={styles.blocker}>• {blocker.message}</Text>) || <Text style={styles.blocker}>Revisa tu cuenta desde la aplicación.</Text>}<Button title="Gestionar mi cuenta y zona" onPress={onManageZone} /></View></ScrollView>;
  if (active) return <View style={styles.fullScreen}><TripMap trip={active} currentLocation={current} route={route} label={active.status === "IN_PROGRESS" ? "Llevas al pasajero a su destino" : active.status === "RIDER_ARRIVED" ? "Pasajero a bordo" : active.status === "ACCEPTED" ? "Oferta aceptada" : "Vas a recoger al pasajero"} height={panelOpen ? 355 : 560} onOriginPress={active.status === "RIDER_ON_THE_WAY" ? () => void advance("RIDER_ARRIVED") : undefined} onDestinationPress={active.status === "RIDER_ARRIVED" ? () => void advance("IN_PROGRESS") : undefined} /><View style={[styles.bottomPanel, !panelOpen && styles.bottomPanelCollapsed]}><Pressable onPress={() => setPanelOpen(value => !value)} style={styles.panelHandle}><View style={styles.handle} /><Text style={styles.panelHandleText}>{panelOpen ? "Ocultar información del viaje" : active.status === "IN_PROGRESS" ? "Llevas al pasajero a su destino" : "Ver información del viaje"}</Text><Text style={styles.panelHandleText}>{panelOpen ? "⌄" : "⌃"}</Text></Pressable>{panelOpen ? <><Text style={styles.eyebrow}>VIAJE ACTIVO · {active.status.replaceAll("_", " ")}</Text><Text style={styles.panelTitle}>{active.status === "IN_PROGRESS" ? "Llevas al pasajero a su destino" : active.status === "RIDER_ARRIVED" ? "Pasajero a bordo" : active.status === "ACCEPTED" ? "Oferta aceptada" : "Ve a recoger al pasajero"}</Text><Text style={styles.panelSub}>{active.client?.name || "Pasajero"} · {active.currency} {tripPrice(active)}</Text><TripMeta trip={active} />{nextFor(active.status) ? <Button title={busy ? "Actualizando…" : actionFor(active.status)} onPress={() => void advance()} disabled={busy} /> : <Button title={busy ? "Finalizando…" : "Finalizar viaje y cobrar efectivo"} onPress={() => void finish()} disabled={busy} />}{active.status !== "IN_PROGRESS" ? <Button title="Cancelar viaje" tone="secondary" onPress={cancel} /> : <Button title="Cancelar por incidencia" tone="danger" onPress={cancel} />}</> : null}</View></View>;
  return <View style={styles.fullScreen}><TripMap currentLocation={current || DEFAULT_PLACE} label={available ? "Estás conectado y recibes viajes" : "Conéctate para recibir solicitudes"} height={375} /><View style={styles.bottomPanel}><View style={styles.panelHandle}><View style={styles.handle} /></View><Text style={styles.eyebrow}>{available ? "RECIBIENDO VIAJES" : "ZONA DE TRABAJO"}</Text><Text style={styles.panelTitle}>{available ? "Estás conectado" : "Estás desconectado"}</Text><Text style={styles.panelSub}>{available ? "Las solicitudes dentro de tu zona aparecerán aquí y en Solicitudes disponibles." : "Conéctate cuando estés listo para trabajar."}</Text><View style={styles.riderZoneCard}><View style={styles.riderZoneIcon}><Text style={styles.riderZoneIconText}>⌖</Text></View><View style={{ flex: 1 }}><Text style={styles.riderZoneLabel}>ZONA OPERATIVA</Text><Text style={styles.riderZoneName}>{ready.workZone?.department || "Zona sin configurar"}</Text><Text style={styles.riderZoneText}>{ready.subscription?.plan ? `${ready.subscription.plan} · ${ready.subscription.daysRemaining} días restantes` : "Plan pendiente"}</Text></View><Pressable onPress={onManageZone} style={styles.zoneManage}><Text style={styles.zoneManageText}>Gestionar</Text></Pressable></View>{ready.dailyQuota ? <View style={styles.quotaCard}><View style={styles.rowBetween}><Text style={styles.quotaLabel}>CUPO DIARIO · {ready.subscription?.plan || "Plan"}</Text><Text style={styles.quotaBadge}>{ready.dailyQuota.remaining}/{ready.dailyQuota.limit}</Text></View><Text style={styles.quotaTitle}>{ready.dailyQuota.remaining} viajes disponibles</Text><Text style={styles.quotaText}>{ready.dailyQuota.completed} de {ready.dailyQuota.limit} completados hoy</Text><View style={styles.quotaTrack}><View style={[styles.quotaProgress, { width: `${Math.min(100, (ready.dailyQuota.remaining / Math.max(1, ready.dailyQuota.limit)) * 100)}%` }]} /></View></View> : null}{available ? <Pressable onPress={onRequests} style={styles.availablePill}><Text style={styles.availablePillText}>Solicitudes disponibles</Text><Text style={styles.availableCount}>{requests.length}</Text></Pressable> : null}<Button title={available ? "Desconectarme" : "Conectarme"} onPress={onToggle} /></View></View>;
}
function RequestsModal({ visible, requests, onClose, onActive, onMessage }: { visible: boolean; requests: Trip[]; onClose: () => void; onActive: (trip: Trip) => void; onMessage: (message: string) => void }) {
  const [selected, setSelected] = useState<Trip | null>(null); const [counter, setCounter] = useState(""); const [busy, setBusy] = useState(false); const [decisionReady, setDecisionReady] = useState(false);
  useEffect(() => { if (!selected) { setDecisionReady(false); return; } const timer = setTimeout(() => setDecisionReady(true), 450); return () => clearTimeout(timer); }, [selected?.id]);
  const accept = () => { if (!selected || !decisionReady) return onMessage("Revisa la solicitud antes de aceptar la tarifa."); Alert.alert("Aceptar tarifa", `¿Aceptar ${selected.currency} ${tripPrice(selected)} por este viaje?`, [{ text: "Revisar", style: "cancel" }, { text: "Aceptar tarifa", onPress: () => void (async () => { setBusy(true); try { const trip = await api<Trip>(`/trips/${selected.id}/accept`, { method: "POST", body: JSON.stringify({}) }); onActive(trip); onClose(); setSelected(null); onMessage("Tarifa aceptada. Inicia la ruta al pasajero cuando estés listo."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } })() }]); };
  const counterOffer = async () => { if (!selected || !decisionReady || !Number(counter)) return onMessage("Ingresa una contraoferta válida."); setBusy(true); try { await api(`/trips/${selected.id}/offers`, { method: "POST", body: JSON.stringify({ amount: Number(counter) }) }); setCounter(""); setSelected(null); onClose(); onMessage("Contraoferta enviada. Espera la respuesta del pasajero."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalShade}><View style={styles.requestSheet}><View style={styles.sheetHandle} /><Text style={styles.eyebrow}>SOLICITUDES DISPONIBLES</Text>{selected ? <><Text style={styles.sheetTitle}>Viaje cercano</Text><TripMeta trip={selected} /><View style={styles.counterBox}><Text style={styles.counterTitle}>Propón otra tarifa si lo necesitas</Text><View style={styles.counterRow}><TextInput keyboardType="numeric" value={counter} onChangeText={setCounter} placeholder="Monto en córdobas" placeholderTextColor="#8F9AAF" style={[styles.input, styles.counterInput]} /><Pressable disabled={busy || !decisionReady || !counter} onPress={() => void counterOffer()} style={[styles.sendCounter, (busy || !decisionReady || !counter) && styles.buttonDisabled]}><Text style={styles.sendCounterText}>{busy ? "…" : "Contraofertar"}</Text></Pressable></View></View><Button title={busy ? "Procesando…" : decisionReady ? "Aceptar tarifa" : "Revisando solicitud…"} onPress={accept} disabled={busy || !decisionReady} /><Button title="Volver a solicitudes" tone="secondary" onPress={() => { setSelected(null); setCounter(""); }} /></> : <><Text style={styles.sheetTitle}>Solicitudes cercanas</Text>{requests.map(request => <Pressable style={styles.requestCard} key={request.id} onPress={() => { setSelected(request); setCounter(""); }}><Text style={styles.requestCardTitle}>{request.originAddress}</Text><Text style={styles.requestCardText}>→ {request.destinationAddress}</Text><Text style={styles.requestCardPrice}>{request.currency} {tripPrice(request)} · {request.distanceKm.toFixed(1)} km · {request.estimatedDurationMin} min</Text></Pressable>)}{!requests.length ? <Text style={styles.pageSubtitle}>No hay solicitudes cercanas por ahora.</Text> : null}<Button title="Cerrar" tone="secondary" onPress={onClose} /></>}</View></View></Modal>;
}function RiderEarnings({ onMessage }: { onMessage: (message: string) => void }) { const [trips, setTrips] = useState<Trip[]>([]); useEffect(() => { void api<Trip[]>("/trips").then(setTrips).catch(error => onMessage((error as Error).message)); }, []); const completed = trips.filter(trip => trip.status === "COMPLETED"); const total = completed.reduce((sum, trip) => sum + Number(trip.finalPrice || trip.proposedPrice || trip.estimatedPrice || 0), 0); return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>GANANCIAS</Text><Text style={styles.pageTitle}>Tu actividad</Text><View style={styles.earningsHero}><Text style={styles.earningsLabel}>Total de viajes completados</Text><Text style={styles.earningsValue}>{completed.length}</Text><Text style={styles.earningsLabel}>Ganancia registrada en efectivo</Text><Text style={styles.earningsMoney}>NIO {total.toFixed(2)}</Text></View><Text style={styles.sectionTitle}>Últimos viajes</Text>{completed.slice(0, 8).map(trip => <View style={styles.historyCard} key={trip.id}><Text style={styles.historyAddress}>{trip.destinationAddress}</Text><Text style={styles.historyPrice}>{trip.currency} {tripPrice(trip)}</Text></View>)}</ScrollView>; }

export default function Index() {
  const [session, setCurrentSession] = useState<Session | null | undefined>(undefined);
  useEffect(() => { void restoreSession().then(setCurrentSession); }, []);
  const handleLogout = () => { void logout().finally(() => setCurrentSession(null)); };
  if (session === undefined) return <SafeAreaView style={styles.splash}><ActivityIndicator color={theme.orange} size="large" /><Text style={styles.splashText}>Preparando MotoYa…</Text></SafeAreaView>;
  if (!session) return <Auth onSession={setCurrentSession} />;
  if (session.user.role === "ADMIN") return <SafeAreaView style={styles.safe}><Header session={session} onLogout={handleLogout} /><View style={styles.adminPlaceholder}><Text style={styles.eyebrow}>BACK-OFFICE</Text><Text style={styles.pageTitle}>Administración solo en web</Text><Text style={styles.pageSubtitle}>Por seguridad, aprobaciones, pagos, planes y configuración no se administran desde la aplicación móvil. Ingresa al portal web de MotoYa para continuar.</Text><Button title="Abrir administración web" onPress={() => void Linking.openURL("https://motoya-web-55ei.onrender.com/admin")} /><Button title="Cerrar sesión" tone="secondary" onPress={handleLogout} /></View></SafeAreaView>;
  return session.user.role === "RIDER" ? <RiderHome session={session} onLogout={handleLogout} /> : <ClientHome session={session} onLogout={handleLogout} />;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.canvas }, main: { flex: 1 }, scroll: { padding: 18, paddingBottom: 104 },
  authSafe: { flex: 1, backgroundColor: theme.ink }, authPage: { padding: 20, paddingTop: 38, paddingBottom: 42 }, authBanner: { backgroundColor: theme.panel, borderRadius: 28, padding: 22, marginBottom: 32, overflow: "hidden" }, routeDecoration: { alignSelf: "flex-end", borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8, marginTop: 12, backgroundColor: "#1E2D50" }, routeDecorationText: { color: theme.orange, fontWeight: "900" }, eyebrow: { color: theme.orange, fontWeight: "900", fontSize: 12, letterSpacing: 1.3 }, authHero: { color: theme.white, fontSize: 32, lineHeight: 37, fontWeight: "900", marginTop: 10 }, orangeText: { color: theme.orange }, authSubtitle: { color: "#B9C3D6", fontSize: 15, lineHeight: 22, marginTop: 8 }, authTitle: { color: theme.white, fontWeight: "900", fontSize: 30, marginTop: 8 }, authCard: { marginTop: 24, backgroundColor: "#11182B", borderColor: "#28334C", borderWidth: 1, borderRadius: 26, padding: 16 }, authFooter: { color: "#C9D0DE", textAlign: "center", marginTop: 22, fontSize: 14 },
  roleSwitch: { flexDirection: "row", backgroundColor: "#222B42", borderRadius: 15, padding: 4, gap: 4, marginBottom: 6 }, roleOption: { flex: 1, alignItems: "center", borderRadius: 12, paddingVertical: 12 }, roleOptionActive: { backgroundColor: theme.orange }, roleText: { fontWeight: "800", color: "#C6CDDC" }, roleTextActive: { color: theme.white },
  header: { height: 72, paddingHorizontal: 18, backgroundColor: theme.panel, flexDirection: "row", alignItems: "center", justifyContent: "space-between", elevation: 4 }, headerBrand: { color: theme.white, fontWeight: "900", fontSize: 23, textAlign: "center" }, headerRole: { color: "#A5B1C8", fontSize: 9, letterSpacing: 1.2, fontWeight: "900", textAlign: "center", marginTop: 1 }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#30221F", borderWidth: 1, borderColor: "#87512F", alignItems: "center", justifyContent: "center" }, avatarText: { color: theme.orange, fontWeight: "900", fontSize: 12 },
  pageTitle: { color: theme.text, fontSize: 28, fontWeight: "900", lineHeight: 34, marginTop: 4 }, pageSubtitle: { color: theme.muted, fontSize: 15, lineHeight: 21, marginTop: 5 }, sectionTitle: { color: theme.text, fontWeight: "900", fontSize: 18, marginTop: 24, marginBottom: 12 },
  searchHero: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 18, backgroundColor: theme.panel, borderRadius: 25, padding: 17, shadowColor: theme.orange, shadowOpacity: .17, shadowRadius: 14, elevation: 4 }, searchGlyph: { width: 42, height: 42, borderRadius: 16, backgroundColor: "#35251D", alignItems: "center", justifyContent: "center" }, searchGlyphText: { color: theme.orange, fontSize: 23, fontWeight: "900" }, searchHeroTitle: { color: theme.white, fontSize: 18, fontWeight: "900" }, searchHeroText: { color: "#C4CDDC", fontSize: 13, marginTop: 3 }, searchHeroArrow: { color: theme.orange, fontSize: 24, fontWeight: "800" }, quickGrid: { flexDirection: "row", gap: 8 }, quickCard: { flex: 1, minHeight: 132, borderRadius: 21, padding: 12, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line }, quickIcon: { color: theme.orange, fontSize: 23 }, quickTitle: { color: theme.text, fontSize: 14, fontWeight: "900", marginTop: 15 }, quickSub: { color: theme.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, activeStrip: { marginTop: 18, borderRadius: 17, padding: 15, backgroundColor: "#E6F8EF" }, homeAds: { marginTop: 20 }, homeSectionEyebrow: { color: theme.orange, fontSize: 11, fontWeight: "900", letterSpacing: 1.1 }, homeSectionTitle: { color: theme.text, fontSize: 21, fontWeight: "900", marginTop: 2 }, passengerZone: { marginTop: 16, flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 20, padding: 14, backgroundColor: "#E7F7F5", borderWidth: 1, borderColor: "#C8EDE8" }, zoneIcon: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#087B78" }, zoneIconText: { color: theme.white, fontSize: 22, fontWeight: "900" }, passengerZoneLabel: { color: "#087B78", fontSize: 10, fontWeight: "900", letterSpacing: .9 }, passengerZoneTitle: { color: theme.text, fontWeight: "900", marginTop: 2, fontSize: 14 }, passengerZoneText: { color: theme.muted, marginTop: 3, fontSize: 11, lineHeight: 15 }, locateButton: { paddingVertical: 9, paddingHorizontal: 10, borderRadius: 12, backgroundColor: theme.white, borderWidth: 1, borderColor: "#BDE6E1" }, locateButtonText: { color: "#087B78", fontSize: 11, fontWeight: "900" }, activeStripTitle: { color: "#087044", fontWeight: "900" }, activeStripText: { color: "#087044", marginTop: 3 },
  ad: { minHeight: 174, borderRadius: 25, padding: 18, marginTop: 18, overflow: "hidden" }, adEyebrow: { fontWeight: "900", fontSize: 11, letterSpacing: 1 }, adTitle: { fontWeight: "900", fontSize: 26, marginTop: 9 }, adText: { fontSize: 14, marginTop: 5, maxWidth: "76%" }, adAction: { fontWeight: "900", marginTop: 19 }, dots: { flexDirection: "row", justifyContent: "center", gap: 7, marginTop: 10 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#CAD3E0" }, dotActive: { backgroundColor: theme.orange, width: 17 },
  field: { marginTop: 12 }, fieldLabel: { color: theme.muted, fontSize: 12, fontWeight: "800", marginBottom: 6 }, input: { minHeight: 48, color: theme.text, borderWidth: 1, borderColor: "#D6DEEA", backgroundColor: theme.white, borderRadius: 14, paddingHorizontal: 13, fontSize: 15 }, inputWrap: { position: "relative" }, inputWithAction: { paddingRight: 52 }, passwordToggle: { position: "absolute", right: 5, top: 4, width: 42, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#EEF3FA" }, passwordToggleText: { color: theme.panel, fontSize: 23, fontWeight: "900" }, button: { marginTop: 14, minHeight: 52, borderRadius: 16, paddingHorizontal: 16, alignItems: "center", justifyContent: "center" }, button_primary: { backgroundColor: theme.orange }, button_secondary: { backgroundColor: theme.white, borderWidth: 1, borderColor: "#D6DEEA" }, button_danger: { backgroundColor: "#651E26" }, buttonText: { color: theme.white, fontWeight: "900", fontSize: 15 }, buttonTextDark: { color: theme.text }, buttonDisabled: { opacity: .48 }, notice: { margin: 12, padding: 12, borderRadius: 14, backgroundColor: "#352231" }, noticeText: { color: "#FFD2C1", fontSize: 13, lineHeight: 18 },
  routeCard: { marginTop: 18, borderRadius: 24, padding: 16, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line }, routeLabel: { color: theme.muted, fontSize: 11, letterSpacing: .8, fontWeight: "900", marginTop: 4 }, routeInput: { color: theme.text, fontSize: 16, fontWeight: "800", paddingVertical: 5 }, routeConnector: { color: "#BCD1E5", fontSize: 20, marginVertical: 0 }, result: { paddingVertical: 12, borderTopWidth: 1, borderTopColor: theme.line }, resultTitle: { color: theme.text, fontWeight: "700" }, savedLine: { marginTop: 12, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 }, savedLabel: { color: theme.muted, fontWeight: "800", width: "100%" }, savedChip: { color: "#106B62", backgroundColor: "#E2F7F2", borderRadius: 12, paddingHorizontal: 10, paddingVertical: 7, fontWeight: "800", maxWidth: 150 }, quoteCard: { borderRadius: 25, backgroundColor: theme.panel, padding: 18, marginTop: 6 }, quotePrice: { color: theme.white, fontSize: 32, fontWeight: "900", marginTop: 4 }, quoteDescription: { color: "#BEC9D9", marginTop: 3 },
  card: { backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line, borderRadius: 22, padding: 16, marginTop: 16 }, placeCard: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: theme.card, padding: 14, borderRadius: 19, borderWidth: 1, borderColor: theme.line, marginTop: 12 }, placeIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#FFF1E6", justifyContent: "center", alignItems: "center" }, placeTitle: { color: theme.text, fontWeight: "900", fontSize: 16 }, placeAddress: { color: theme.muted, fontSize: 12, marginTop: 3 }, placeArrow: { color: theme.orange, fontWeight: "900", fontSize: 18 }, placeEdit: { color: theme.orange, fontSize: 12, fontWeight: "900", paddingVertical: 4 }, placeDelete: { color: "#B12931", fontSize: 12, fontWeight: "900", paddingVertical: 4 }, accountHintDark: { color: theme.muted, fontSize: 13, lineHeight: 19, marginTop: 12 },
  fullScreen: { flex: 1, backgroundColor: theme.canvas }, bottomPanel: { marginTop: -18, padding: 18, paddingBottom: 20, borderTopLeftRadius: 30, borderTopRightRadius: 30, backgroundColor: theme.panel, zIndex: 5 }, bottomPanelCollapsed: { paddingBottom: 13 }, panelHandle: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 28 }, handle: { width: 35, height: 4, borderRadius: 4, backgroundColor: "#A9B5CA", marginRight: "auto" }, panelHandleText: { color: theme.white, fontSize: 12, fontWeight: "800" }, panelTitle: { color: theme.white, fontSize: 24, fontWeight: "900", marginTop: 6 }, panelSub: { color: "#C2CCDC", marginTop: 4, fontSize: 14, lineHeight: 20 }, tripMeta: { backgroundColor: theme.panelSoft, borderRadius: 16, padding: 13, marginTop: 15 }, tripAddress: { color: theme.white, fontWeight: "700", lineHeight: 19 }, tripArrow: { color: theme.orange, marginVertical: 5, fontSize: 18 }, tripMetaFooter: { marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, metaText: { color: "#BBC6D9", fontSize: 12 }, tripPrice: { color: "#FFBC83", fontSize: 18, fontWeight: "900" }, offerCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#2D3853" }, offerName: { color: theme.white, fontWeight: "900" }, offerPrice: { color: "#FFBC83", fontWeight: "900", marginTop: 3 }, liveLabel: { color: "#5BE1A2", fontWeight: "800", marginTop: 15 },
  statusPill: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: "#FFF1E6" }, statusPillActive: { backgroundColor: "#E3F8EC" }, statusPillText: { color: "#B35316", fontSize: 10, fontWeight: "900" }, statusPillTextActive: { color: "#087044" }, historyCard: { borderRadius: 20, padding: 15, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line, marginTop: 12 }, rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, historyPrice: { color: theme.green, fontWeight: "900", fontSize: 16 }, historyAddress: { color: theme.text, fontWeight: "800", marginTop: 10, lineHeight: 20 }, historyArrow: { color: theme.orange, fontSize: 18, marginVertical: 2 }, empty: { alignItems: "center", padding: 28, marginTop: 22 }, emptyTitle: { color: theme.text, fontWeight: "900", fontSize: 19 },
  accountHero: { backgroundColor: theme.panel, borderRadius: 25, padding: 20, marginTop: 18 }, accountRole: { color: theme.orange, fontSize: 12, fontWeight: "900", letterSpacing: 1 }, accountEmail: { color: theme.white, fontSize: 19, fontWeight: "800", marginTop: 9 }, accountHint: { color: "#C3CDDD", marginTop: 12, lineHeight: 21 }, blockersCard: { backgroundColor: "#FFF7EE", borderRadius: 23, padding: 18, marginTop: 20 }, blockersTitle: { color: theme.text, fontWeight: "900", fontSize: 18 }, blocker: { color: "#6B4A35", marginTop: 10, lineHeight: 20 }, availablePill: { marginTop: 15, padding: 12, borderRadius: 15, backgroundColor: "#202C45", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, availablePillText: { color: theme.white, fontWeight: "800" }, availableCount: { color: theme.white, fontWeight: "900", backgroundColor: theme.violet, minWidth: 25, textAlign: "center", paddingVertical: 4, borderRadius: 12 }, riderZoneCard: { marginTop: 15, padding: 14, borderRadius: 19, backgroundColor: "#172A55", flexDirection: "row", alignItems: "center", gap: 11 }, riderZoneIcon: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#273E78" }, riderZoneIconText: { color: "#8BEEC8", fontSize: 22, fontWeight: "900" }, riderZoneLabel: { color: "#9AB0D7", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, riderZoneName: { color: theme.white, fontSize: 17, fontWeight: "900", marginTop: 3 }, riderZoneText: { color: "#C4D1E8", fontSize: 11, marginTop: 3 }, zoneManage: { paddingVertical: 8, paddingHorizontal: 9, borderWidth: 1, borderColor: "#526A9C", borderRadius: 10 }, zoneManageText: { color: theme.white, fontSize: 10, fontWeight: "900" }, quotaCard: { marginTop: 12, padding: 14, borderRadius: 18, backgroundColor: "#121A34", borderWidth: 1, borderColor: "#2E3B5A" }, quotaLabel: { color: "#FFB77E", fontSize: 10, fontWeight: "900", letterSpacing: .6 }, quotaBadge: { color: theme.white, backgroundColor: "#283147", borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4, fontWeight: "900", fontSize: 12 }, quotaTitle: { color: theme.white, fontSize: 20, fontWeight: "900", marginTop: 6 }, quotaText: { color: "#BEC9DB", fontSize: 12, marginTop: 3 }, quotaTrack: { height: 7, borderRadius: 7, backgroundColor: "#26314B", overflow: "hidden", marginTop: 12 }, quotaProgress: { height: "100%", borderRadius: 7, backgroundColor: "#FF9C3F" },
  tabs: { minHeight: 72, backgroundColor: "#070B1C", paddingHorizontal: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-around" }, tab: { minWidth: 56, alignItems: "center", justifyContent: "center", paddingVertical: 7, borderRadius: 16 }, tabActive: { backgroundColor: "#3B2115" }, tabIcon: { color: "#9AA7BF", fontSize: 21, lineHeight: 22 }, tabIconActive: { color: theme.orange }, tabLabel: { color: "#9AA7BF", fontSize: 10, marginTop: 3, fontWeight: "700" }, tabLabelActive: { color: "#FFB77E" },
  modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.5)" }, requestSheet: { maxHeight: "86%", padding: 20, paddingBottom: 32, backgroundColor: theme.canvas, borderTopLeftRadius: 32, borderTopRightRadius: 32 }, sheetHandle: { width: 40, height: 4, borderRadius: 3, backgroundColor: "#CBD5E3", alignSelf: "center", marginBottom: 18 }, sheetTitle: { color: theme.text, fontSize: 25, fontWeight: "900", marginTop: 5 }, requestCard: { borderWidth: 1, borderColor: theme.line, backgroundColor: theme.card, borderRadius: 17, padding: 14, marginTop: 12 }, requestCardTitle: { color: theme.text, fontWeight: "900", fontSize: 16 }, requestCardText: { color: theme.muted, marginTop: 4, lineHeight: 18 }, requestCardPrice: { color: theme.green, fontWeight: "900", marginTop: 10 }, counterBox: { backgroundColor: "#F3F6FB", borderRadius: 16, padding: 12, marginTop: 13 }, counterTitle: { color: theme.text, fontWeight: "800", marginBottom: 9 }, counterRow: { flexDirection: "row", gap: 8 }, counterInput: { flex: 1 }, sendCounter: { backgroundColor: theme.panel, borderRadius: 13, paddingHorizontal: 14, alignItems: "center", justifyContent: "center" }, sendCounterText: { color: theme.white, fontWeight: "800" },
  earningsHero: { backgroundColor: theme.panel, borderRadius: 26, padding: 21, marginTop: 18 }, earningsLabel: { color: "#BFCADD", fontWeight: "700", fontSize: 13 }, earningsValue: { color: theme.white, fontSize: 44, fontWeight: "900", marginTop: 3, marginBottom: 16 }, earningsMoney: { color: "#62E5A5", fontSize: 28, fontWeight: "900", marginTop: 4 }, splash: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: theme.ink }, splashText: { color: theme.white, marginTop: 15, fontWeight: "800" }, adminPlaceholder: { flex: 1, padding: 20, backgroundColor: theme.canvas },
});