import * as Location from "expo-location";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { api, connectSocket, getRoute, getSocket, isActiveTrip, login, logout, register, restoreSession, searchPlaces, setSession, tripPrice, type Advertisement, type Offer, type Place, type Quote, type Readiness, type Role, type Session, type Trip } from "../src/api";
import { TripMap } from "../src/components/TripMap";
import { theme } from "../src/theme";

const DEFAULT_PLACE: Place = { lat: 12.1364, lng: -86.2514, address: "Managua, Nicaragua" };
const ACTIVE = ["REQUESTED", "ACCEPTED", "RIDER_ON_THE_WAY", "RIDER_ARRIVED", "IN_PROGRESS"];
type Tab = "home" | "trip" | "places" | "history" | "account" | "work" | "earnings";

function Button({ title, onPress, tone = "primary", disabled = false }: { title: string; onPress: () => void; tone?: "primary" | "secondary" | "danger"; disabled?: boolean }) {
  return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, styles[`button_${tone}`], disabled && styles.buttonDisabled]}><Text style={[styles.buttonText, tone !== "primary" && styles.buttonTextDark]}>{title}</Text></Pressable>;
}
function Field({ label, value, onChangeText, placeholder, secret = false, numeric = false }: { label: string; value: string; onChangeText: (next: string) => void; placeholder?: string; secret?: boolean; numeric?: boolean }) {
  return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#8F9AAF" secureTextEntry={secret} keyboardType={numeric ? "numeric" : "default"} autoCapitalize="none" style={styles.input} /></View>;
}
function Notice({ text }: { text: string }) { return text ? <View style={styles.notice}><Text style={styles.noticeText}>{text}</Text></View> : null; }
function StatusPill({ text, active = false }: { text: string; active?: boolean }) { return <View style={[styles.statusPill, active && styles.statusPillActive]}><Text style={[styles.statusPillText, active && styles.statusPillTextActive]}>{text}</Text></View>; }

function Auth({ onSession }: { onSession: (session: Session) => void }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [role, setRole] = useState<Exclude<Role, "ADMIN">>("CLIENT");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const submit = async () => {
    if (!email.trim() || !password) return setMessage("Ingresa tu correo y contraseña.");
    if (mode === "register" && !name.trim()) return setMessage("Ingresa tu nombre completo.");
    setBusy(true); setMessage("");
    try { const session = mode === "login" ? await login(email.trim(), password) : await register(role, name.trim(), email.trim(), password); await setSession(session); onSession(session); }
    catch (error) { setMessage((error as Error).message); } finally { setBusy(false); }
  };
  return <SafeAreaView style={styles.authSafe}><ScrollView contentContainerStyle={styles.authPage} keyboardShouldPersistTaps="handled">
    <View style={styles.authBanner}><Text style={styles.eyebrow}>MOTOYA</Text><Text style={styles.authHero}>Muévete rápido.{"\n"}<Text style={styles.orangeText}>Llega seguro.</Text></Text><Text style={styles.authSubtitle}>Una forma simple de pedir una moto o trabajar con independencia.</Text><View style={styles.routeDecoration}><Text style={styles.routeDecorationText}>● · · · ⚑</Text></View></View>
    <Text style={styles.eyebrow}>{mode === "login" ? "BIENVENIDO DE NUEVO" : "EMPIEZA HOY"}</Text><Text style={styles.authTitle}>{mode === "login" ? "Ingresa a tu cuenta" : "Crea tu cuenta"}</Text><Text style={styles.authSubtitle}>{mode === "login" ? "Usa tus datos para continuar de forma segura." : "Elige cómo quieres usar MotoYa."}</Text>
    <View style={styles.authCard}>{mode === "register" ? <><View style={styles.roleSwitch}><Pressable onPress={() => setRole("CLIENT")} style={[styles.roleOption, role === "CLIENT" && styles.roleOptionActive]}><Text style={[styles.roleText, role === "CLIENT" && styles.roleTextActive]}>Pasajero</Text></Pressable><Pressable onPress={() => setRole("RIDER")} style={[styles.roleOption, role === "RIDER" && styles.roleOptionActive]}><Text style={[styles.roleText, role === "RIDER" && styles.roleTextActive]}>Rider</Text></Pressable></View><Field label="Nombre completo" value={name} onChangeText={setName} placeholder="Como aparece en tu cédula" /></> : null}<Field label="Correo" value={email} onChangeText={setEmail} placeholder="nombre@correo.com" /><Field label="Contraseña" value={password} onChangeText={setPassword} placeholder="Tu contraseña" secret /><Notice text={message} /><Button title={busy ? "Conectando…" : mode === "login" ? "Entrar a MotoYa  →" : `Continuar como ${role === "CLIENT" ? "pasajero" : "rider"}  →`} onPress={() => void submit()} disabled={busy} /></View>
    <Pressable onPress={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); }}><Text style={styles.authFooter}>{mode === "login" ? "Primera vez en MotoYa? " : "Ya tienes una cuenta? "}<Text style={styles.orangeText}>{mode === "login" ? "Crea tu cuenta" : "Inicia sesión"}</Text></Text></Pressable>
  </ScrollView></SafeAreaView>;
}

function Header({ session, onLogout }: { session: Session; onLogout: () => void }) { return <View style={styles.header}><View><Text style={styles.headerBrand}>Moto<Text style={styles.orangeText}>Ya</Text></Text><Text style={styles.headerRole}>{session.user.role === "CLIENT" ? "PASAJERO" : "RIDER"}</Text></View><Pressable onPress={onLogout} style={styles.avatar}><Text style={styles.avatarText}>{session.user.name.slice(0, 2).toUpperCase()}</Text></Pressable></View>; }
function Tabs({ role, selected, onChange }: { role: Role; selected: Tab; onChange: (tab: Tab) => void }) {
  const items: Array<[Tab, string, string]> = role === "CLIENT" ? [["home", "⌂", "Inicio"], ["trip", "⌁", "Viaje"], ["places", "⌖", "Lugares"], ["history", "◴", "Historial"], ["account", "♙", "Cuenta"]] : [["work", "⌁", "Trabajo"], ["earnings", "◈", "Ganancias"], ["history", "◴", "Historial"], ["account", "♙", "Cuenta"]];
  return <View style={styles.tabs}>{items.map(([tab, icon, label]) => <Pressable key={tab} onPress={() => onChange(tab)} style={[styles.tab, selected === tab && styles.tabActive]}><Text style={[styles.tabIcon, selected === tab && styles.tabIconActive]}>{icon}</Text><Text style={[styles.tabLabel, selected === tab && styles.tabLabelActive]}>{label}</Text></Pressable>)}</View>;
}
function Shell({ session, tab, onTab, onLogout, children }: { session: Session; tab: Tab; onTab: (tab: Tab) => void; onLogout: () => void; children: React.ReactNode }) { return <SafeAreaView style={styles.safe}><Header session={session} onLogout={onLogout} /><View style={styles.main}>{children}</View><Tabs role={session.user.role} selected={tab} onChange={onTab} /></SafeAreaView>; }

function TripMeta({ trip }: { trip: Trip }) { return <View style={styles.tripMeta}><Text style={styles.tripAddress}>{trip.originAddress}</Text><Text style={styles.tripArrow}>↓</Text><Text style={styles.tripAddress}>{trip.destinationAddress}</Text><View style={styles.tripMetaFooter}><Text style={styles.metaText}>{trip.distanceKm.toFixed(1)} km · {trip.estimatedDurationMin} min</Text><Text style={styles.tripPrice}>{trip.currency} {tripPrice(trip)}</Text></View></View>; }

function useRoute(from?: Place | null, to?: Place | null) {
  const [route, setRoute] = useState<Place[]>([]);
  useEffect(() => { let live = true; if (!from || !to) { setRoute([]); return; } void getRoute(from, to).then(result => { if (live) setRoute(result.points); }).catch(() => { if (live) setRoute([from, to]); }); return () => { live = false; }; }, [from?.lat, from?.lng, to?.lat, to?.lng]);
  return route;
}
function useTripRealtime(trip: Trip | null, onTrip: (trip: Trip) => void, onOffer?: (offer: Offer) => void) {
  useEffect(() => {
    if (!trip) return;
    let active = true; const refresh = () => { void api<Trip>(`/trips/${trip.id}`).then(next => active && onTrip(next)).catch(() => undefined); };
    const interval = setInterval(refresh, 10_000); refresh();
    void connectSocket().then(socket => { if (!socket) return; socket.on("trip:status-updated", onTrip); socket.on("trip:accepted", onTrip); socket.on("trip:tracking-updated", refresh); socket.on("trip:location-updated", refresh); if (onOffer) socket.on("trip:offer", onOffer); });
    return () => { active = false; clearInterval(interval); const socket = getSocket(); socket?.off("trip:status-updated", onTrip); socket?.off("trip:accepted", onTrip); socket?.off("trip:tracking-updated", refresh); socket?.off("trip:location-updated", refresh); if (onOffer) socket?.off("trip:offer", onOffer); };
  }, [trip?.id]);
}

function ClientHome({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("home"); const [places, setPlaces] = useState<Place[]>([]); const [ads, setAds] = useState<Advertisement[]>([]); const [message, setMessage] = useState(""); const [activeTrip, setActiveTrip] = useState<Trip | null>(null);
  const [origin, setOrigin] = useState<Place>(DEFAULT_PLACE); const [destination, setDestination] = useState<Place | null>(null);
  const load = useCallback(async () => { try { const [saved, advertisements, trips] = await Promise.all([api<Array<Place & { label: string }>>("/places"), api<Advertisement[]>("/advertisements"), api<Trip[]>("/trips")]); setPlaces(saved); setAds(advertisements); setActiveTrip(trips.find(item => ACTIVE.includes(item.status)) || null); } catch (error) { setMessage((error as Error).message); } }, []);
  useEffect(() => { void load(); void connectSocket(); }, []);
  const locate = async () => { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") return setMessage("Permite la ubicación para usar el origen actual."); const point = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setOrigin({ lat: point.coords.latitude, lng: point.coords.longitude, address: "Mi ubicación actual" }); } catch { setMessage("No fue posible obtener tu ubicación. Puedes corregir el origen manualmente."); } };
  useEffect(() => { void locate(); }, []);
  useTripRealtime(activeTrip, next => { if (isActiveTrip(next.status)) setActiveTrip(next); else { setActiveTrip(null); setMessage(next.status === "COMPLETED" ? "Viaje finalizado. Gracias por viajar con MotoYa." : "El viaje fue cancelado."); } });
  const content = () => {
    if (tab === "trip") return <ClientTrip session={session} active={activeTrip} onActive={setActiveTrip} origin={origin} destination={destination} onOrigin={setOrigin} onDestination={setDestination} saved={places} onMessage={setMessage} />;
    if (tab === "places") return <SavedPlaces places={places} onSelect={place => { setDestination(place); setTab("trip"); }} onRefresh={load} onMessage={setMessage} />;
    if (tab === "history") return <TripHistory role="CLIENT" onMessage={setMessage} />;
    if (tab === "account") return <Account session={session} onLogout={onLogout} />;
    return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>MOTOYA · PASAJERO</Text><Text style={styles.pageTitle}>¿A dónde te llevamos?</Text><Text style={styles.pageSubtitle}>Elige tu destino, recibe una tarifa y solicita una moto.</Text>{ads.length ? <AdCarousel ads={ads} /> : null}<Pressable onPress={() => setTab("trip")} style={styles.searchHero}><View style={styles.searchGlyph}><Text style={styles.searchGlyphText}>⌁</Text></View><View style={{ flex: 1 }}><Text style={styles.searchHeroTitle}>Buscar un viaje</Text><Text style={styles.searchHeroText}>Rápido, seguro y cercano</Text></View><Text style={styles.searchHeroArrow}>→</Text></Pressable><Text style={styles.sectionTitle}>Accesos rápidos</Text><View style={styles.quickGrid}><QuickCard icon="⌖" title="Lugares" subtitle="Casa, trabajo y favoritos" onPress={() => setTab("places")} /><QuickCard icon="◴" title="Mis viajes" subtitle="Consulta tu historial" onPress={() => setTab("history")} /></View>{activeTrip ? <Pressable onPress={() => setTab("trip")} style={styles.activeStrip}><Text style={styles.activeStripTitle}>Tienes un viaje activo</Text><Text style={styles.activeStripText}>Ver seguimiento en vivo →</Text></Pressable> : null}</ScrollView>;
  };
  return <Shell session={session} tab={tab} onTab={setTab} onLogout={onLogout}><Notice text={message} />{content()}</Shell>;
}
function AdCarousel({ ads }: { ads: Advertisement[] }) { const [index, setIndex] = useState(0); const ad = ads[index % ads.length]; return <View><Pressable onPress={() => setIndex(current => (current + 1) % ads.length)} style={[styles.ad, { backgroundColor: ad.backgroundColor }]}><Text style={[styles.adEyebrow, { color: ad.textColor }]}>MOTOYA TE INFORMA</Text><Text style={[styles.adTitle, { color: ad.textColor }]}>{ad.title}</Text>{ad.description ? <Text style={[styles.adText, { color: ad.textColor }]}>{ad.description}</Text> : null}<Text style={[styles.adAction, { color: ad.textColor }]}>{ad.actionLabel || "Ver novedad"}  →</Text></Pressable><View style={styles.dots}>{ads.map((item, itemIndex) => <View key={item.id} style={[styles.dot, itemIndex === index % ads.length && styles.dotActive]} />)}</View></View>; }
function QuickCard({ icon, title, subtitle, onPress }: { icon: string; title: string; subtitle: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.quickCard}><Text style={styles.quickIcon}>{icon}</Text><Text style={styles.quickTitle}>{title}</Text><Text style={styles.quickSub}>{subtitle}</Text></Pressable>; }

function ClientTrip({ active, onActive, origin, destination, onOrigin, onDestination, saved, onMessage }: { session: Session; active: Trip | null; onActive: (trip: Trip | null) => void; origin: Place; destination: Place | null; onOrigin: (place: Place) => void; onDestination: (place: Place | null) => void; saved: Place[]; onMessage: (message: string) => void }) {
  const [query, setQuery] = useState(destination?.address || ""); const [results, setResults] = useState<Place[]>([]); const [quote, setQuote] = useState<Quote | null>(null); const [fare, setFare] = useState(""); const [notes, setNotes] = useState(""); const [offers, setOffers] = useState<Offer[]>([]); const [busy, setBusy] = useState(false); const [panelOpen, setPanelOpen] = useState(true);
  const tripOrigin = active ? { lat: active.originLat, lng: active.originLng, address: active.originAddress } : origin;
  const tripDestination = active ? { lat: active.destinationLat, lng: active.destinationLng, address: active.destinationAddress } : destination;
  const riderPosition = active?.riderLat != null && active?.riderLng != null
    ? { lat: active.riderLat, lng: active.riderLng, address: "Ubicación del rider" }
    : null;
  const riderIsApproaching = active?.status === "ACCEPTED" || active?.status === "RIDER_ON_THE_WAY" || active?.status === "RIDER_ARRIVED";
  const route = useRoute(riderIsApproaching && riderPosition ? riderPosition : tripOrigin, riderIsApproaching ? tripOrigin : tripDestination);
  useTripRealtime(active, next => { if (isActiveTrip(next.status)) onActive(next); else onActive(null); }, offer => setOffers(current => current.some(item => item.id === offer.id) ? current : [offer, ...current]));
  useEffect(() => { if (!active || active.status !== "REQUESTED") return; void api<Offer[]>(`/trips/${active.id}/offers`).then(setOffers).catch(() => undefined); }, [active?.id, active?.status]);
  const search = async () => { if (query.trim().length < 3) return onMessage("Escribe al menos tres caracteres para buscar un destino."); setBusy(true); try { setResults(await searchPlaces(query)); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const selectDestination = (place: Place) => { onDestination(place); setQuery(place.address); setResults([]); setQuote(null); };
  const estimate = async () => { if (!destination) return onMessage("Selecciona un destino para calcular la tarifa."); setBusy(true); try { setQuote(await api<Quote>("/trips/estimate", { method: "POST", body: JSON.stringify({ origin, destination, serviceCode: "MOTO" }) })); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const request = async () => { if (!destination || !quote) return; const proposedPrice = fare ? Number(fare) : undefined; if (proposedPrice && (proposedPrice < quote.minimumFare || proposedPrice > quote.maximumFare)) return onMessage(`Propón una tarifa entre ${quote.minimumFare} y ${quote.maximumFare} ${quote.currency}.`); setBusy(true); try { onActive(await api<Trip>("/trips", { method: "POST", body: JSON.stringify({ origin, destination, serviceCode: "MOTO", proposedPrice, notes: notes.trim() || undefined }) })); setQuote(null); setPanelOpen(true); onMessage("Solicitud enviada. Buscaremos riders cercanos."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const acceptOffer = async (offer: Offer) => { if (!active) return; setBusy(true); try { onActive(await api<Trip>(`/trips/${active.id}/offers/${offer.id}/accept`, { method: "POST" })); setOffers([]); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const cancel = async () => { if (!active) return; Alert.alert("Cancelar viaje", "¿Deseas cancelar esta solicitud?", [{ text: "No", style: "cancel" }, { text: "Sí, cancelar", style: "destructive", onPress: () => void api(`/trips/${active.id}/cancel`, { method: "POST", body: JSON.stringify({ reason: "Cancelado por el pasajero" }) }).then(() => onActive(null)).catch(error => onMessage((error as Error).message)) }]); };
  const confirmArrival = async () => { if (!active) return; try { const completed = await api<Trip>(`/trips/${active.id}/complete`, { method: "POST" }); onActive(null); onMessage(`Viaje finalizado. Pago en efectivo: ${completed.currency} ${tripPrice(completed)}.`); } catch (error) { onMessage((error as Error).message); } };
  if (active) return <View style={styles.fullScreen}><TripMap trip={active} route={route} label={active.status === "REQUESTED" ? "Buscando riders cercanos" : active.status === "IN_PROGRESS" ? "Tu rider te lleva al destino" : "Tu rider va hacia tu ubicación"} height={panelOpen ? 350 : 560} /><View style={[styles.bottomPanel, !panelOpen && styles.bottomPanelCollapsed]}><Pressable onPress={() => setPanelOpen(!panelOpen)} style={styles.panelHandle}><View style={styles.handle} /><Text style={styles.panelHandleText}>{panelOpen ? "Ocultar información del viaje" : "Ver información del viaje"}</Text><Text style={styles.panelHandleText}>{panelOpen ? "⌄" : "⌃"}</Text></Pressable>{panelOpen ? <><Text style={styles.eyebrow}>VIAJE ACTUAL · {active.status.replaceAll("_", " ")}</Text><Text style={styles.panelTitle}>{active.status === "REQUESTED" ? "Buscando riders cercanos" : active.status === "IN_PROGRESS" ? "Vas rumbo al destino" : "Tu rider está en camino"}</Text>{active.rider ? <Text style={styles.panelSub}>{active.rider.name} · {active.rider.riderProfile?.vehicleModel || "Moto"} · {active.rider.riderProfile?.vehiclePlate || "placa pendiente"}</Text> : <Text style={styles.panelSub}>Recibirás una oferta o aceptación cuando haya disponibilidad.</Text>}<TripMeta trip={active} />{active.status === "REQUESTED" ? <>{offers.map(offer => <View style={styles.offerCard} key={offer.id}><View><Text style={styles.offerName}>{offer.rider.name}</Text><Text style={styles.offerPrice}>{offer.currency} {offer.amount}</Text></View><Button title={busy ? "Procesando…" : "Elegir"} onPress={() => void acceptOffer(offer)} disabled={busy} /></View>)}<Button title="Cancelar solicitud" onPress={cancel} tone="secondary" /></> : active.status === "IN_PROGRESS" ? <Button title="Confirmar llegada y pagar efectivo" onPress={() => void confirmArrival()} /> : <Button title="Cancelar viaje" onPress={cancel} tone="secondary" />}</> : null}</View></View>;
  return <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>NUEVO VIAJE</Text><Text style={styles.pageTitle}>¿A dónde te llevamos?</Text><Text style={styles.pageSubtitle}>Confirma origen, elige destino y conoce el precio antes de pedir.</Text><View style={styles.routeCard}><Text style={styles.routeLabel}>ORIGEN</Text><TextInput value={origin.address} onChangeText={address => { onOrigin({ ...origin, address }); setQuote(null); }} style={styles.routeInput} /><Text style={styles.routeConnector}>│</Text><Text style={styles.routeLabel}>DESTINO</Text><TextInput value={query} onChangeText={setQuery} placeholder="Buscar destino" placeholderTextColor="#8F9AAF" style={styles.routeInput} /><Button title={busy ? "Buscando…" : "Buscar destino"} onPress={() => void search()} tone="secondary" disabled={busy} />{results.map(result => <Pressable key={`${result.lat}-${result.lng}`} onPress={() => selectDestination(result)} style={styles.result}><Text style={styles.resultTitle}>{result.address}</Text></Pressable>)}{saved.length ? <View style={styles.savedLine}><Text style={styles.savedLabel}>Tus lugares</Text>{saved.slice(0, 3).map(place => <Pressable key={`${place.lat}-${place.lng}`} onPress={() => selectDestination(place)}><Text style={styles.savedChip}>{place.label || place.address}</Text></Pressable>)}</View> : null}</View><TripMap origin={origin} destination={destination || undefined} route={route} editable onMapPress={selectDestination} label="Toca el mapa si quieres ajustar el destino" /><Field label="Instrucciones para el rider" value={notes} onChangeText={setNotes} placeholder="Ej. Estoy frente a la farmacia" /><Button title={busy ? "Calculando…" : "Ver tarifa de Moto"} onPress={() => void estimate()} disabled={busy} />{quote ? <View style={styles.quoteCard}><Text style={styles.eyebrow}>MOTO · EFECTIVO</Text><Text style={styles.quotePrice}>{quote.currency} {fare || quote.estimatedPrice}</Text><Text style={styles.quoteDescription}>{quote.distanceKm.toFixed(1)} km · {quote.estimatedDurationMin} min · tarifa sugerida</Text><Field label={`Puedes proponer entre ${quote.minimumFare} y ${quote.maximumFare}`} value={fare} onChangeText={setFare} placeholder="Monto opcional" numeric /><Button title={busy ? "Enviando…" : "Solicitar viaje"} onPress={() => void request()} disabled={busy} /></View> : null}</ScrollView>;
}

function SavedPlaces({ places, onSelect, onRefresh, onMessage }: { places: Array<Place & { label?: string }>; onSelect: (place: Place) => void; onRefresh: () => Promise<void>; onMessage: (message: string) => void }) {
  const [label, setLabel] = useState(""); const [address, setAddress] = useState(""); const [busy, setBusy] = useState(false);
  const save = async () => { if (!label.trim() || !address.trim()) return onMessage("Ingresa un alias y una dirección para guardar el lugar."); setBusy(true); try { const results = await searchPlaces(address); const place = results[0]; if (!place) throw new Error("No encontramos esa dirección."); await api(`/places/${encodeURIComponent(label.trim())}`, { method: "PUT", body: JSON.stringify({ ...place }) }); setLabel(""); setAddress(""); await onRefresh(); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>LUGARES</Text><Text style={styles.pageTitle}>Destinos guardados</Text><Text style={styles.pageSubtitle}>Guarda casa, trabajo o cualquier punto con un nombre propio.</Text><View style={styles.card}><Field label="Alias" value={label} onChangeText={setLabel} placeholder="Ej. Gimnasio" /><Field label="Dirección" value={address} onChangeText={setAddress} placeholder="Busca una dirección" /><Button title={busy ? "Guardando…" : "Guardar lugar"} onPress={() => void save()} disabled={busy} /></View>{places.map(place => <Pressable key={`${place.label}-${place.lat}-${place.lng}`} onPress={() => onSelect(place)} style={styles.placeCard}><View style={styles.placeIcon}><Text>⌖</Text></View><View style={{ flex: 1 }}><Text style={styles.placeTitle}>{place.label || "Lugar guardado"}</Text><Text style={styles.placeAddress}>{place.address}</Text></View><Text style={styles.placeArrow}>→</Text></Pressable>)}</ScrollView>;
}
function TripHistory({ role, onMessage }: { role: Role; onMessage: (message: string) => void }) { const [trips, setTrips] = useState<Trip[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { void api<Trip[]>("/trips").then(setTrips).catch(error => onMessage((error as Error).message)).finally(() => setLoading(false)); }, []); return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>HISTORIAL</Text><Text style={styles.pageTitle}>Tus viajes</Text><Text style={styles.pageSubtitle}>Consulta los trayectos y pagos en efectivo registrados.</Text>{loading ? <ActivityIndicator color={theme.orange} /> : trips.map(trip => <View style={styles.historyCard} key={trip.id}><View style={styles.rowBetween}><StatusPill text={trip.status.replaceAll("_", " ")} active={trip.status === "COMPLETED"} /><Text style={styles.historyPrice}>{trip.currency} {tripPrice(trip)}</Text></View><Text style={styles.historyAddress}>{trip.originAddress}</Text><Text style={styles.historyArrow}>↓</Text><Text style={styles.historyAddress}>{trip.destinationAddress}</Text></View>)}{!loading && !trips.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>Aún no hay viajes</Text><Text style={styles.pageSubtitle}>Tu actividad aparecerá aquí cuando realices el primer viaje.</Text></View> : null}</ScrollView>; }
function Account({ session, onLogout }: { session: Session; onLogout: () => void }) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>CUENTA</Text><Text style={styles.pageTitle}>Hola, {session.user.name.split(" ")[0]}</Text><View style={styles.accountHero}><Text style={styles.accountRole}>{session.user.role === "CLIENT" ? "PASAJERO" : "RIDER"}</Text><Text style={styles.accountEmail}>{session.user.email}</Text><Text style={styles.accountHint}>{session.user.role === "CLIENT" ? "Tu cuenta está activa para solicitar viajes." : "Gestiona documentos, zona y suscripción desde la web mientras migramos estas secciones."}</Text></View><Button title="Cerrar sesión" tone="secondary" onPress={onLogout} /></ScrollView>; }

function RiderHome({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [tab, setTab] = useState<Tab>("work"); const [available, setAvailable] = useState(false); const [readiness, setReadiness] = useState<Readiness>({ ready: false }); const [current, setCurrent] = useState<Place | null>(null); const [requests, setRequests] = useState<Trip[]>([]); const [activeTrip, setActiveTrip] = useState<Trip | null>(null); const [message, setMessage] = useState(""); const [requestOpen, setRequestOpen] = useState(false);
  const load = useCallback(async () => { try { const [profile, ready, trips] = await Promise.all([api<{ available: boolean }>("/riders/me"), api<Readiness>("/riders/me/readiness"), api<Trip[]>("/trips")]); setAvailable(profile.available); setReadiness(ready); const active = trips.find(item => ACTIVE.includes(item.status)); setActiveTrip(active || null); if (ready.ready && profile.available && !active) setRequests(await api<Trip[]>("/riders/available-trips")); } catch (error) { setMessage((error as Error).message); } }, []);
  useEffect(() => { let live = true; const receive = () => void load(); void load(); void connectSocket().then(socket => { if (live) socket?.on("trip:requested", receive); }); return () => { live = false; getSocket()?.off("trip:requested", receive); }; }, []);
  useTripRealtime(activeTrip, next => { if (isActiveTrip(next.status)) setActiveTrip(next); else { setActiveTrip(null); void load(); } });
  useEffect(() => { let subscription: Location.LocationSubscription | null = null; if (!available && !activeTrip) return; void Location.requestForegroundPermissionsAsync().then(permission => { if (permission.status !== "granted") { setMessage("Activa el permiso de ubicación para trabajar."); return; } return Location.watchPositionAsync({ accuracy: Location.Accuracy.High, timeInterval: 8_000, distanceInterval: 8 }, location => { const point = { lat: location.coords.latitude, lng: location.coords.longitude, address: "Tu ubicación", accuracy: location.coords.accuracy ?? undefined, heading: location.coords.heading ?? undefined, capturedAt: new Date(location.timestamp).toISOString() }; setCurrent(point); const path = activeTrip ? `/trips/${activeTrip.id}/location` : "/riders/me/location"; void api(path, { method: "PATCH", body: JSON.stringify(point) }).catch(() => undefined); }).then(next => { subscription = next; }); }).catch(() => setMessage("No se pudo activar el GPS.")); return () => subscription?.remove(); }, [available, activeTrip?.id]);
  const toggle = async () => { try { await api("/riders/me/availability", { method: "PATCH", body: JSON.stringify({ available: !available }) }); await load(); } catch (error) { setMessage((error as Error).message); } };
  const content = () => { if (tab === "earnings") return <RiderEarnings onMessage={setMessage} />; if (tab === "history") return <TripHistory role="RIDER" onMessage={setMessage} />; if (tab === "account") return <Account session={session} onLogout={onLogout} />; return <RiderWork available={available} ready={readiness} current={current} active={activeTrip} requests={requests} onToggle={toggle} onActive={setActiveTrip} onRequests={() => setRequestOpen(true)} onMessage={setMessage} />; };
  return <Shell session={session} tab={tab} onTab={setTab} onLogout={onLogout}><Notice text={message} />{content()}<RequestsModal visible={requestOpen} requests={requests} onClose={() => setRequestOpen(false)} onActive={setActiveTrip} onMessage={setMessage} /></Shell>;
}
function RiderWork({ available, ready, current, active, requests, onToggle, onActive, onRequests, onMessage }: { available: boolean; ready: Readiness; current: Place | null; active: Trip | null; requests: Trip[]; onToggle: () => void; onActive: (trip: Trip | null) => void; onRequests: () => void; onMessage: (message: string) => void }) {
  const routeTarget = active?.status === "IN_PROGRESS" ? { lat: active.destinationLat, lng: active.destinationLng, address: active.destinationAddress } : active ? { lat: active.originLat, lng: active.originLng, address: active.originAddress } : null;
  const route = useRoute(current, routeTarget);
  const [panelOpen, setPanelOpen] = useState(true);
  const advance = async () => { if (!active) return; try { const nextStatus = active.status === "RIDER_ON_THE_WAY" ? "RIDER_ARRIVED" : active.status === "RIDER_ARRIVED" ? "IN_PROGRESS" : null; if (!nextStatus) return; onActive(await api<Trip>(`/trips/${active.id}/status`, { method: "PATCH", body: JSON.stringify({ status: nextStatus, location: current ? { lat: current.lat, lng: current.lng } : undefined }) })); } catch (error) { onMessage((error as Error).message); } };
  const cancel = async () => { if (!active) return; try { await api(`/trips/${active.id}/cancel`, { method: "POST", body: JSON.stringify({ reason: "Incidencia reportada por rider" }) }); onActive(null); } catch (error) { onMessage((error as Error).message); } };
  if (!ready.ready) return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>ZONA DE TRABAJO</Text><Text style={styles.pageTitle}>Aún no puedes conectarte</Text><View style={styles.blockersCard}><Text style={styles.blockersTitle}>Completa estos requisitos</Text>{ready.blockers?.map(blocker => <Text key={blocker.code} style={styles.blocker}>• {blocker.message}</Text>) || <Text style={styles.blocker}>Revisa tu cuenta desde la web.</Text>}</View></ScrollView>;
  if (active) return <View style={styles.fullScreen}><TripMap trip={active} currentLocation={current} route={route} label={active.status === "IN_PROGRESS" ? "Llevas al pasajero a su destino" : "Vas a recoger al pasajero"} height={panelOpen ? 355 : 560} /><View style={[styles.bottomPanel, !panelOpen && styles.bottomPanelCollapsed]}><Pressable onPress={() => setPanelOpen(!panelOpen)} style={styles.panelHandle}><View style={styles.handle} /><Text style={styles.panelHandleText}>{panelOpen ? "Ocultar información del viaje" : "Ver información del viaje"}</Text><Text style={styles.panelHandleText}>{panelOpen ? "⌄" : "⌃"}</Text></Pressable>{panelOpen ? <><Text style={styles.eyebrow}>VIAJE ACTIVO · {active.status.replaceAll("_", " ")}</Text><Text style={styles.panelTitle}>{active.status === "IN_PROGRESS" ? "Llevas al pasajero a su destino" : "Ve a recoger al pasajero"}</Text><Text style={styles.panelSub}>{active.client?.name || "Pasajero"} · {active.currency} {tripPrice(active)}</Text><TripMeta trip={active} />{active.status === "RIDER_ON_THE_WAY" ? <Button title="Recoger pasajero" onPress={() => void advance()} /> : active.status === "RIDER_ARRIVED" ? <Button title="Iniciar viaje al destino" onPress={() => void advance()} /> : <Text style={styles.liveLabel}>● Compartiendo ubicación en vivo</Text>}<Button title="Cancelar por incidencia" tone="danger" onPress={() => void cancel()} /></> : null}</View></View>;
  return <View style={styles.fullScreen}><TripMap currentLocation={current || DEFAULT_PLACE} label={available ? "Estás conectado y recibes viajes" : "Conéctate para recibir solicitudes"} height={410} /><View style={styles.bottomPanel}><View style={styles.panelHandle}><View style={styles.handle} /></View><Text style={styles.eyebrow}>{available ? "RECIBIENDO VIAJES" : "ZONA DE TRABAJO"}</Text><Text style={styles.panelTitle}>{available ? "Estás conectado" : "Estás desconectado"}</Text><Text style={styles.panelSub}>{available ? "Las solicitudes dentro de tu zona aparecerán aquí." : "Conéctate cuando estés listo para trabajar."}</Text>{available ? <Pressable onPress={onRequests} style={styles.availablePill}><Text style={styles.availablePillText}>Solicitudes disponibles</Text><Text style={styles.availableCount}>{requests.length}</Text></Pressable> : null}<Button title={available ? "Desconectarme" : "Conectarme"} onPress={onToggle} /></View></View>;
}
function RequestsModal({ visible, requests, onClose, onActive, onMessage }: { visible: boolean; requests: Trip[]; onClose: () => void; onActive: (trip: Trip) => void; onMessage: (message: string) => void }) {
  const [selected, setSelected] = useState<Trip | null>(null); const [counter, setCounter] = useState(""); const [busy, setBusy] = useState(false);
  const accept = async () => { if (!selected) return; setBusy(true); try { const trip = await api<Trip>(`/trips/${selected.id}/accept`, { method: "POST", body: JSON.stringify({}) }); onActive(trip); onClose(); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  const counterOffer = async () => { if (!selected || !Number(counter)) return onMessage("Ingresa una contraoferta válida."); setBusy(true); try { await api(`/trips/${selected.id}/offers`, { method: "POST", body: JSON.stringify({ amount: Number(counter) }) }); setCounter(""); setSelected(null); onClose(); onMessage("Contraoferta enviada. Espera la respuesta del pasajero."); } catch (error) { onMessage((error as Error).message); } finally { setBusy(false); } };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalShade}><View style={styles.requestSheet}><View style={styles.sheetHandle} /><Text style={styles.eyebrow}>SOLICITUDES DISPONIBLES</Text>{selected ? <><Text style={styles.sheetTitle}>Viaje cercano</Text><TripMeta trip={selected} /><View style={styles.counterBox}><Text style={styles.counterTitle}>O envía una contraoferta</Text><View style={styles.counterRow}><TextInput keyboardType="numeric" value={counter} onChangeText={setCounter} placeholder="Monto en córdobas" placeholderTextColor="#8F9AAF" style={[styles.input, styles.counterInput]} /><Pressable onPress={() => void counterOffer()} style={styles.sendCounter}><Text style={styles.sendCounterText}>Enviar</Text></Pressable></View></View><Button title={busy ? "Procesando…" : "Aceptar tarifa"} onPress={() => void accept()} disabled={busy} /><Button title="Volver a solicitudes" tone="secondary" onPress={() => setSelected(null)} /></> : <><Text style={styles.sheetTitle}>Elige una solicitud</Text>{requests.map(request => <Pressable style={styles.requestCard} key={request.id} onPress={() => setSelected(request)}><Text style={styles.requestCardTitle}>{request.originAddress}</Text><Text style={styles.requestCardText}>{request.destinationAddress}</Text><Text style={styles.requestCardPrice}>{request.currency} {tripPrice(request)} · {request.distanceKm.toFixed(1)} km</Text></Pressable>)}{!requests.length ? <Text style={styles.pageSubtitle}>No hay solicitudes cercanas por ahora.</Text> : null}<Button title="Cerrar" tone="secondary" onPress={onClose} /></>}</View></View></Modal>;
}
function RiderEarnings({ onMessage }: { onMessage: (message: string) => void }) { const [trips, setTrips] = useState<Trip[]>([]); useEffect(() => { void api<Trip[]>("/trips").then(setTrips).catch(error => onMessage((error as Error).message)); }, []); const completed = trips.filter(trip => trip.status === "COMPLETED"); const total = completed.reduce((sum, trip) => sum + Number(trip.finalPrice || trip.proposedPrice || trip.estimatedPrice || 0), 0); return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.eyebrow}>GANANCIAS</Text><Text style={styles.pageTitle}>Tu actividad</Text><View style={styles.earningsHero}><Text style={styles.earningsLabel}>Total de viajes completados</Text><Text style={styles.earningsValue}>{completed.length}</Text><Text style={styles.earningsLabel}>Ganancia registrada en efectivo</Text><Text style={styles.earningsMoney}>NIO {total.toFixed(2)}</Text></View><Text style={styles.sectionTitle}>Últimos viajes</Text>{completed.slice(0, 8).map(trip => <View style={styles.historyCard} key={trip.id}><Text style={styles.historyAddress}>{trip.destinationAddress}</Text><Text style={styles.historyPrice}>{trip.currency} {tripPrice(trip)}</Text></View>)}</ScrollView>; }

export default function Index() {
  const [session, setCurrentSession] = useState<Session | null | undefined>(undefined);
  useEffect(() => { void restoreSession().then(setCurrentSession); }, []);
  const handleLogout = () => { void logout().finally(() => setCurrentSession(null)); };
  if (session === undefined) return <SafeAreaView style={styles.splash}><ActivityIndicator color={theme.orange} size="large" /><Text style={styles.splashText}>Preparando MotoYa…</Text></SafeAreaView>;
  if (!session) return <Auth onSession={setCurrentSession} />;
  if (session.user.role === "ADMIN") return <SafeAreaView style={styles.safe}><Header session={session} onLogout={handleLogout} /><View style={styles.adminPlaceholder}><Text style={styles.pageTitle}>Administración</Text><Text style={styles.pageSubtitle}>Las aprobaciones y configuración del back-office continúan en la plataforma web mientras terminamos la fase administrativa nativa.</Text><Button title="Cerrar sesión" tone="secondary" onPress={handleLogout} /></View></SafeAreaView>;
  return session.user.role === "RIDER" ? <RiderHome session={session} onLogout={handleLogout} /> : <ClientHome session={session} onLogout={handleLogout} />;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.canvas }, main: { flex: 1 }, scroll: { padding: 18, paddingBottom: 104 },
  authSafe: { flex: 1, backgroundColor: theme.ink }, authPage: { padding: 20, paddingTop: 38, paddingBottom: 42 }, authBanner: { backgroundColor: theme.panel, borderRadius: 28, padding: 22, marginBottom: 32, overflow: "hidden" }, routeDecoration: { alignSelf: "flex-end", borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8, marginTop: 12, backgroundColor: "#1E2D50" }, routeDecorationText: { color: theme.orange, fontWeight: "900" }, eyebrow: { color: theme.orange, fontWeight: "900", fontSize: 12, letterSpacing: 1.3 }, authHero: { color: theme.white, fontSize: 32, lineHeight: 37, fontWeight: "900", marginTop: 10 }, orangeText: { color: theme.orange }, authSubtitle: { color: "#B9C3D6", fontSize: 15, lineHeight: 22, marginTop: 8 }, authTitle: { color: theme.white, fontWeight: "900", fontSize: 30, marginTop: 8 }, authCard: { marginTop: 24, backgroundColor: "#11182B", borderColor: "#28334C", borderWidth: 1, borderRadius: 26, padding: 16 }, authFooter: { color: "#C9D0DE", textAlign: "center", marginTop: 22, fontSize: 14 },
  roleSwitch: { flexDirection: "row", backgroundColor: "#222B42", borderRadius: 15, padding: 4, gap: 4, marginBottom: 6 }, roleOption: { flex: 1, alignItems: "center", borderRadius: 12, paddingVertical: 12 }, roleOptionActive: { backgroundColor: theme.orange }, roleText: { fontWeight: "800", color: "#C6CDDC" }, roleTextActive: { color: theme.white },
  header: { height: 72, paddingHorizontal: 18, backgroundColor: theme.panel, flexDirection: "row", alignItems: "center", justifyContent: "space-between", elevation: 4 }, headerBrand: { color: theme.white, fontWeight: "900", fontSize: 23, textAlign: "center" }, headerRole: { color: "#A5B1C8", fontSize: 9, letterSpacing: 1.2, fontWeight: "900", textAlign: "center", marginTop: 1 }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#30221F", borderWidth: 1, borderColor: "#87512F", alignItems: "center", justifyContent: "center" }, avatarText: { color: theme.orange, fontWeight: "900", fontSize: 12 },
  pageTitle: { color: theme.text, fontSize: 28, fontWeight: "900", lineHeight: 34, marginTop: 4 }, pageSubtitle: { color: theme.muted, fontSize: 15, lineHeight: 21, marginTop: 5 }, sectionTitle: { color: theme.text, fontWeight: "900", fontSize: 18, marginTop: 24, marginBottom: 12 },
  searchHero: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 18, backgroundColor: theme.panel, borderRadius: 25, padding: 17, shadowColor: theme.orange, shadowOpacity: .17, shadowRadius: 14, elevation: 4 }, searchGlyph: { width: 42, height: 42, borderRadius: 16, backgroundColor: "#35251D", alignItems: "center", justifyContent: "center" }, searchGlyphText: { color: theme.orange, fontSize: 23, fontWeight: "900" }, searchHeroTitle: { color: theme.white, fontSize: 18, fontWeight: "900" }, searchHeroText: { color: "#C4CDDC", fontSize: 13, marginTop: 3 }, searchHeroArrow: { color: theme.orange, fontSize: 24, fontWeight: "800" }, quickGrid: { flexDirection: "row", gap: 12 }, quickCard: { flex: 1, minHeight: 140, borderRadius: 21, padding: 14, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line }, quickIcon: { color: theme.orange, fontSize: 24 }, quickTitle: { color: theme.text, fontSize: 16, fontWeight: "900", marginTop: 16 }, quickSub: { color: theme.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, activeStrip: { marginTop: 18, borderRadius: 17, padding: 15, backgroundColor: "#E6F8EF" }, activeStripTitle: { color: "#087044", fontWeight: "900" }, activeStripText: { color: "#087044", marginTop: 3 },
  ad: { minHeight: 174, borderRadius: 25, padding: 18, marginTop: 18, overflow: "hidden" }, adEyebrow: { fontWeight: "900", fontSize: 11, letterSpacing: 1 }, adTitle: { fontWeight: "900", fontSize: 26, marginTop: 9 }, adText: { fontSize: 14, marginTop: 5, maxWidth: "76%" }, adAction: { fontWeight: "900", marginTop: 19 }, dots: { flexDirection: "row", justifyContent: "center", gap: 7, marginTop: 10 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#CAD3E0" }, dotActive: { backgroundColor: theme.orange, width: 17 },
  field: { marginTop: 12 }, fieldLabel: { color: theme.muted, fontSize: 12, fontWeight: "800", marginBottom: 6 }, input: { minHeight: 48, color: theme.text, borderWidth: 1, borderColor: "#D6DEEA", backgroundColor: theme.white, borderRadius: 14, paddingHorizontal: 13, fontSize: 15 }, button: { marginTop: 14, minHeight: 52, borderRadius: 16, paddingHorizontal: 16, alignItems: "center", justifyContent: "center" }, button_primary: { backgroundColor: theme.orange }, button_secondary: { backgroundColor: theme.white, borderWidth: 1, borderColor: "#D6DEEA" }, button_danger: { backgroundColor: "#651E26" }, buttonText: { color: theme.white, fontWeight: "900", fontSize: 15 }, buttonTextDark: { color: theme.text }, buttonDisabled: { opacity: .48 }, notice: { margin: 12, padding: 12, borderRadius: 14, backgroundColor: "#352231" }, noticeText: { color: "#FFD2C1", fontSize: 13, lineHeight: 18 },
  routeCard: { marginTop: 18, borderRadius: 24, padding: 16, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line }, routeLabel: { color: theme.muted, fontSize: 11, letterSpacing: .8, fontWeight: "900", marginTop: 4 }, routeInput: { color: theme.text, fontSize: 16, fontWeight: "800", paddingVertical: 5 }, routeConnector: { color: "#BCD1E5", fontSize: 20, marginVertical: 0 }, result: { paddingVertical: 12, borderTopWidth: 1, borderTopColor: theme.line }, resultTitle: { color: theme.text, fontWeight: "700" }, savedLine: { marginTop: 12, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 }, savedLabel: { color: theme.muted, fontWeight: "800", width: "100%" }, savedChip: { color: "#106B62", backgroundColor: "#E2F7F2", borderRadius: 12, paddingHorizontal: 10, paddingVertical: 7, fontWeight: "800", maxWidth: 150 }, quoteCard: { borderRadius: 25, backgroundColor: theme.panel, padding: 18, marginTop: 6 }, quotePrice: { color: theme.white, fontSize: 32, fontWeight: "900", marginTop: 4 }, quoteDescription: { color: "#BEC9D9", marginTop: 3 },
  card: { backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line, borderRadius: 22, padding: 16, marginTop: 16 }, placeCard: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: theme.card, padding: 14, borderRadius: 19, borderWidth: 1, borderColor: theme.line, marginTop: 12 }, placeIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#FFF1E6", justifyContent: "center", alignItems: "center" }, placeTitle: { color: theme.text, fontWeight: "900", fontSize: 16 }, placeAddress: { color: theme.muted, fontSize: 12, marginTop: 3 }, placeArrow: { color: theme.orange, fontWeight: "900", fontSize: 18 },
  fullScreen: { flex: 1, backgroundColor: theme.canvas }, bottomPanel: { marginTop: -18, padding: 18, paddingBottom: 20, borderTopLeftRadius: 30, borderTopRightRadius: 30, backgroundColor: theme.panel, zIndex: 5 }, bottomPanelCollapsed: { paddingBottom: 13 }, panelHandle: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 28 }, handle: { width: 35, height: 4, borderRadius: 4, backgroundColor: "#A9B5CA", marginRight: "auto" }, panelHandleText: { color: theme.white, fontSize: 12, fontWeight: "800" }, panelTitle: { color: theme.white, fontSize: 24, fontWeight: "900", marginTop: 6 }, panelSub: { color: "#C2CCDC", marginTop: 4, fontSize: 14, lineHeight: 20 }, tripMeta: { backgroundColor: theme.panelSoft, borderRadius: 16, padding: 13, marginTop: 15 }, tripAddress: { color: theme.white, fontWeight: "700", lineHeight: 19 }, tripArrow: { color: theme.orange, marginVertical: 5, fontSize: 18 }, tripMetaFooter: { marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, metaText: { color: "#BBC6D9", fontSize: 12 }, tripPrice: { color: "#FFBC83", fontSize: 18, fontWeight: "900" }, offerCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#2D3853" }, offerName: { color: theme.white, fontWeight: "900" }, offerPrice: { color: "#FFBC83", fontWeight: "900", marginTop: 3 }, liveLabel: { color: "#5BE1A2", fontWeight: "800", marginTop: 15 },
  statusPill: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: "#FFF1E6" }, statusPillActive: { backgroundColor: "#E3F8EC" }, statusPillText: { color: "#B35316", fontSize: 10, fontWeight: "900" }, statusPillTextActive: { color: "#087044" }, historyCard: { borderRadius: 20, padding: 15, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.line, marginTop: 12 }, rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, historyPrice: { color: theme.green, fontWeight: "900", fontSize: 16 }, historyAddress: { color: theme.text, fontWeight: "800", marginTop: 10, lineHeight: 20 }, historyArrow: { color: theme.orange, fontSize: 18, marginVertical: 2 }, empty: { alignItems: "center", padding: 28, marginTop: 22 }, emptyTitle: { color: theme.text, fontWeight: "900", fontSize: 19 },
  accountHero: { backgroundColor: theme.panel, borderRadius: 25, padding: 20, marginTop: 18 }, accountRole: { color: theme.orange, fontSize: 12, fontWeight: "900", letterSpacing: 1 }, accountEmail: { color: theme.white, fontSize: 19, fontWeight: "800", marginTop: 9 }, accountHint: { color: "#C3CDDD", marginTop: 12, lineHeight: 21 }, blockersCard: { backgroundColor: "#FFF7EE", borderRadius: 23, padding: 18, marginTop: 20 }, blockersTitle: { color: theme.text, fontWeight: "900", fontSize: 18 }, blocker: { color: "#6B4A35", marginTop: 10, lineHeight: 20 }, availablePill: { marginTop: 15, padding: 12, borderRadius: 15, backgroundColor: "#202C45", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, availablePillText: { color: theme.white, fontWeight: "800" }, availableCount: { color: theme.white, fontWeight: "900", backgroundColor: theme.violet, minWidth: 25, textAlign: "center", paddingVertical: 4, borderRadius: 12 },
  tabs: { minHeight: 72, backgroundColor: "#070B1C", paddingHorizontal: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-around" }, tab: { minWidth: 56, alignItems: "center", justifyContent: "center", paddingVertical: 7, borderRadius: 16 }, tabActive: { backgroundColor: "#3B2115" }, tabIcon: { color: "#9AA7BF", fontSize: 21, lineHeight: 22 }, tabIconActive: { color: theme.orange }, tabLabel: { color: "#9AA7BF", fontSize: 10, marginTop: 3, fontWeight: "700" }, tabLabelActive: { color: "#FFB77E" },
  modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.5)" }, requestSheet: { maxHeight: "86%", padding: 20, paddingBottom: 32, backgroundColor: theme.canvas, borderTopLeftRadius: 32, borderTopRightRadius: 32 }, sheetHandle: { width: 40, height: 4, borderRadius: 3, backgroundColor: "#CBD5E3", alignSelf: "center", marginBottom: 18 }, sheetTitle: { color: theme.text, fontSize: 25, fontWeight: "900", marginTop: 5 }, requestCard: { borderWidth: 1, borderColor: theme.line, backgroundColor: theme.card, borderRadius: 17, padding: 14, marginTop: 12 }, requestCardTitle: { color: theme.text, fontWeight: "900", fontSize: 16 }, requestCardText: { color: theme.muted, marginTop: 4, lineHeight: 18 }, requestCardPrice: { color: theme.green, fontWeight: "900", marginTop: 10 }, counterBox: { backgroundColor: "#F3F6FB", borderRadius: 16, padding: 12, marginTop: 13 }, counterTitle: { color: theme.text, fontWeight: "800", marginBottom: 9 }, counterRow: { flexDirection: "row", gap: 8 }, counterInput: { flex: 1 }, sendCounter: { backgroundColor: theme.panel, borderRadius: 13, paddingHorizontal: 14, alignItems: "center", justifyContent: "center" }, sendCounterText: { color: theme.white, fontWeight: "800" },
  earningsHero: { backgroundColor: theme.panel, borderRadius: 26, padding: 21, marginTop: 18 }, earningsLabel: { color: "#BFCADD", fontWeight: "700", fontSize: 13 }, earningsValue: { color: theme.white, fontSize: 44, fontWeight: "900", marginTop: 3, marginBottom: 16 }, earningsMoney: { color: "#62E5A5", fontSize: 28, fontWeight: "900", marginTop: 4 }, splash: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: theme.ink }, splashText: { color: theme.white, marginTop: 15, fontWeight: "800" }, adminPlaceholder: { flex: 1, padding: 20, backgroundColor: theme.canvas },
});
