"use client";

import { useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Method = { code: "MOTO_EXPRESS" | "BANK_TRANSFER"; name: string; instructions: string; isActive: boolean; configuration?: Record<string, string> | null };
type Payment = { id: string; status: string; amount: string; currency: string; externalReference: string; customerReference?: string | null; proofReference?: string | null; metadata?: { bankName?: string } | null; order: { planNameSnapshot: string; rider: { user: { name: string } } }; method: { name: string } };

export default function AdminPaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]); const [methods, setMethods] = useState<Method[]>([]); const [message, setMessage] = useState("");
  const load = () => Promise.all([api<Payment[]>("/subscriptions/admin/payments"), api<Method[]>("/subscriptions/admin/methods")]).then(([nextPayments, nextMethods]) => { setPayments(nextPayments); setMethods(nextMethods); }).catch((error) => setMessage(error.message));
  useEffect(() => { load(); }, []);
  const review = async (id: string, approved: boolean) => { const reason = approved ? undefined : window.prompt("Motivo del rechazo") || undefined; if (!approved && !reason) return; await api(`/subscriptions/admin/payments/${id}/review`, { method: "POST", body: JSON.stringify({ approved, reason }) }); setMessage(approved ? "Pago aprobado." : "Pago rechazado."); load(); };
  const saveMethod = async (method: Method) => { await api(`/subscriptions/admin/methods/${method.code}`, { method: "PATCH", body: JSON.stringify({ name: method.name, instructions: method.instructions, configuration: method.configuration || {}, isActive: method.isActive }) }); setMessage("Datos de deposito guardados."); load(); };
  const update = (code: Method["code"], key: string, value: string) => setMethods((current) => current.map((method) => method.code === code ? { ...method, configuration: { ...method.configuration, [key]: value } } : method));
  return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><h1 className="mt-4 text-2xl font-black">Pagos y depositos</h1><p className="muted">Configura cuentas receptoras y revisa comprobantes privados.</p>
    <section className="mt-3 space-y-3">{methods.map((method) => <article className="card" key={method.code}><b>{method.code === "MOTO_EXPRESS" ? "Deposito" : "Transferencia bancaria"}</b><p className="muted mt-1">Estos datos se muestran al rider antes de adjuntar su comprobante.</p><input className="mt-3" value={method.configuration?.holderName || ""} onChange={(event) => update(method.code, "holderName", event.target.value)} placeholder="Nombre del titular" /><input className="mt-2" value={method.configuration?.bank || ""} onChange={(event) => update(method.code, "bank", event.target.value)} placeholder="Banco receptor" /><input className="mt-2" value={method.configuration?.account || ""} onChange={(event) => update(method.code, "account", event.target.value)} placeholder="Numero de cuenta" /><textarea className="mt-2" value={method.instructions} onChange={(event) => setMethods((current) => current.map((item) => item.code === method.code ? { ...item, instructions: event.target.value } : item))} placeholder="Instrucciones" /><button className="primary mt-3 w-full" onClick={() => saveMethod(method)}>Guardar datos de cuenta</button></article>)}</section>
    <h2 className="mt-5 text-lg font-bold">Comprobantes por revisar</h2>{payments.filter((payment) => payment.status === "PENDING_REVIEW").map((payment) => <article className="card mt-3" key={payment.id}><b>{payment.order.rider.user.name} · {payment.order.planNameSnapshot}</b><p>{payment.method.name} · {payment.currency} {payment.amount}</p><p className="muted">Referencia MotoYa: {payment.externalReference}</p><p className="muted">Banco de origen: {payment.metadata?.bankName || "No indicado"}</p>{payment.customerReference ? <p className="muted">Referencia cliente: {payment.customerReference}</p> : null}{payment.proofReference?.startsWith("data:image") ? <img className="mt-3 max-h-72 w-full rounded-xl object-contain" src={payment.proofReference} alt="Comprobante de pago" /> : <p className="mt-2 text-sm text-red-700">Sin comprobante valido.</p>}<div className="mt-3 flex gap-2"><button className="primary flex-1" onClick={() => review(payment.id, true)}>Aprobar</button><button className="border flex-1" onClick={() => review(payment.id, false)}>Rechazar</button></div></article>)}{!payments.some((payment) => payment.status === "PENDING_REVIEW") ? <p className="card mt-3">No hay pagos pendientes.</p> : null}{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>;
}
