"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { api, setSession, Session } from "@/lib/api";

export default function RegisterPage() {
  const router = useRouter(); const [role, setRole] = useState<"CLIENT" | "RIDER">("CLIENT"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (form: FormData) => { setLoading(true); setError(""); try { const session = await api<Session>(`/auth/register/${role.toLowerCase()}`, { method: "POST", body: JSON.stringify(Object.fromEntries(form.entries())) }); setSession(session); router.push(role === "RIDER" ? "/rider/account" : "/client/home"); } catch (reason) { setError((reason as Error).message); } finally { setLoading(false); } };
  return <main className="mx-auto min-h-dvh max-w-md bg-slate-50 p-5"><p className="mt-5 text-sm font-bold text-orange-500">MOTOYA</p><h1 className="mt-2 text-3xl font-bold">Crea tu cuenta</h1><p className="muted mt-2">Solo pedimos lo necesario para comenzar. Podras completar tu perfil despues.</p><div className="mt-6 grid grid-cols-2 rounded-2xl bg-slate-200 p-1"><button type="button" onClick={() => setRole("CLIENT")} className={role === "CLIENT" ? "bg-white text-slate-950 shadow-sm" : "text-slate-500"}>Pasajero</button><button type="button" onClick={() => setRole("RIDER")} className={role === "RIDER" ? "bg-white text-slate-950 shadow-sm" : "text-slate-500"}>Rider</button></div><section className="mt-4 rounded-2xl border border-orange-100 bg-orange-50 p-4 text-sm text-orange-950"><b>{role === "CLIENT" ? "Cuenta semi activa" : "Registro inicial de rider"}</b><p className="mt-1">{role === "CLIENT" ? "Podras explorar, guardar lugares y completar tu verificacion desde tu cuenta." : "Despues completaras vehiculo y documentos dentro de la aplicacion."}</p></section><form action={submit} className="mt-5 space-y-3"><input name="name" placeholder="Nombre completo" required /><input name="phone" inputMode="tel" placeholder="Telefono" required /><input name="email" type="email" placeholder="Correo" required /><input name="password" type="password" minLength={8} placeholder="Contrasena (minimo 8 caracteres)" required />{error ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}<button className="primary w-full" disabled={loading}>{loading ? "Creando cuenta..." : `Continuar como ${role === "RIDER" ? "rider" : "pasajero"}`}</button></form><p className="muted mt-5 text-center">Al continuar aceptas los terminos y la politica de privacidad.</p></main>;
}
