"use client";
import { useEffect, useState } from "react"; import { Guard } from "@/components/Guard"; import { MapPoint, MapView } from "@/components/MapView"; import { api } from "@/lib/api";
type Place = MapPoint & { address: string }; const managua: Place = { lat: 12.1364, lng: -86.2514, address: "Managua, Nicaragua" };
export default function Client(){ const [origin,setOrigin]=useState<Place>({...managua,address:"Selecciona tu origen"}); const [destination,setDestination]=useState<Place | null>(null); const [mode,setMode]=useState<"origin"|"destination">("origin"); const [quote,setQuote]=useState<{distanceKm:number;estimatedPrice:number;currency:string}|null>(); const [message,setMessage]=useState(""); useEffect(()=>{locate()},[]);
 const pick=(p:MapPoint)=>{const place={...p,address:`${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}`};if(mode==="origin"){setOrigin(place);setMode("destination");setMessage("Ahora toca el destino en el mapa.");}else{setDestination(place);setMessage("Destino seleccionado. Calcula la estimación.");}};
 const locate=()=>navigator.geolocation?.getCurrentPosition(p=>{setOrigin({lat:p.coords.latitude,lng:p.coords.longitude,address:"Mi ubicación actual"});setMode("destination");setMessage("Ubicación detectada. Ahora selecciona destino.");},()=>setMessage("No fue posible obtener tu ubicación. Selecciónala tocando el mapa."));
 const estimate=async()=>{if(!destination)return;try{setQuote(await api("/trips/estimate",{method:"POST",body:JSON.stringify({origin,destination})}));}catch(e){setMessage((e as Error).message)}};
 const request=async()=>{if(!destination)return;try{const t=await api<{id:string}>("/trips",{method:"POST",body:JSON.stringify({origin,destination})});setMessage(`Viaje solicitado. Código ${t.id}`);}catch(e){setMessage((e as Error).message)}};
 return <Guard roles={["CLIENT"]}><main className="mx-auto max-w-md p-4"><header className="flex items-center justify-between"><b className="text-xl text-orange-500">MotoYa</b><span className="muted">Pasajero</span></header><p className="mt-3 text-sm font-medium">{mode==="origin"?"Toca el mapa para elegir origen.":"Toca el mapa para elegir destino."}</p><section className="mt-3"><MapView origin={origin} destination={destination||undefined} focus={origin} onPick={pick}/></section><button onClick={locate} className="mt-3 w-full border">Usar mi ubicación actual</button><section className="mt-3 space-y-3"><input value={origin.address} onChange={e=>setOrigin({...origin,address:e.target.value})} placeholder="Punto de origen"/><input value={destination?.address||""} onChange={e=>destination&&setDestination({...destination,address:e.target.value})} placeholder="Punto de destino"/>{destination&&<button onClick={estimate} className="w-full border">Calcular estimación</button>}{quote&&<div className="card"><b>{quote.distanceKm} km · {quote.currency} {quote.estimatedPrice}</b><p className="muted">Precio estimado.</p></div>}<button onClick={request} className="primary w-full" disabled={!quote}>Solicitar moto</button>{message&&<p className="text-sm">{message}</p>}</section></main></Guard>}
