"use client";

import { useEffect, useMemo, useState } from "react";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Document = { id: string; type: string; status: string; expiresAt?: string | null; frontImage?: string | null; backImage?: string | null; rejectionReason?: string | null };
type Rider = { id: string; name: string; email: string; status: string; riderProfile: { approval: string; onboardingStatus: string; workZoneDepartment?: string | null; insuranceExpiresAt?: string | null; documents: Document[]; subscriptions: { expiresAt?: string | null }[] } };
const required = ["NATIONAL_ID", "DRIVER_LICENSE", "VEHICLE_REGISTRATION", "INSURANCE"];
const labels: Record<string, string> = { NATIONAL_ID: "Cedula", DRIVER_LICENSE: "Licencia", VEHICLE_REGISTRATION: "Tarjeta de circulacion", INSURANCE: "Seguro" };
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString("es-NI") : "Sin fecha";

export default function ApprovalsPage() {
  const [riders, setRiders] = useState<Rider[]>([]); const [selected, setSelected] = useState<Rider | null>(null); const [filter, setFilter] = useState("UNDER_REVIEW"); const [message, setMessage] = useState("");
  const load = () => api<Rider[]>(`/admin/approvals?status=${encodeURIComponent(filter)}`).then((items) => { setRiders(items); setSelected((current) => items.find((item) => item.id === current?.id) || items[0] || null); }).catch((error) => setMessage(error.message));
  useEffect(() => { load(); }, [filter]);
  const eligible = useMemo(() => { if (!selected) return false; const insurance = selected.riderProfile.documents.find((document) => document.type === "INSURANCE"); return required.every((type) => selected.riderProfile.documents.find((document) => document.type === type)?.status === "APPROVED") && Boolean(insurance?.expiresAt && new Date(insurance.expiresAt) > new Date()); }, [selected]);
  async function review(document: Document, status: "APPROVED" | "REQUIRES_CORRECTION") { if (!selected) return; const reason = status === "APPROVED" ? undefined : window.prompt("Indica claramente la correccion requerida") || undefined; if (status !== "APPROVED" && !reason) return; try { await api(`/admin/riders/${selected.id}/documents/${document.id}`, { method: "PATCH", body: JSON.stringify({ status, reason }) }); setMessage(status === "APPROVED" ? "Documento aprobado." : "Correccion solicitada."); await load(); } catch (cause) { setMessage((cause as Error).message); } }
  async function approveRider() { if (!selected || !eligible) return; try { await api(`/admin/riders/${selected.id}/status`, { method: "PATCH", body: JSON.stringify({ approval: "APPROVED" }) }); setMessage("Rider aprobado. Falta activar plan y zona para operar."); await load(); } catch (cause) { setMessage((cause as Error).message); } }
  return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><section className="mt-4"><p className="text-sm font-bold text-orange-500">BACK-OFFICE</p><h1 className="text-2xl font-black">Centro de aprobaciones</h1><p className="muted">Los expedientes y evidencias solo son visibles para administracion.</p></section>
    <select className="mt-3" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="UNDER_REVIEW">En revision</option><option value="REQUIRES_CORRECTION">Correccion solicitada</option><option value="DOCUMENTS_PENDING">Pendientes</option><option value="SUBSCRIPTION_REQUIRED">Suscripcion</option><option value="READY_TO_WORK">Operativos</option></select>
    <section className="mt-3 space-y-2">{riders.map((rider) => <button className={`card w-full text-left ${selected?.id === rider.id ? "ring-2 ring-orange-500" : ""}`} onClick={() => setSelected(rider)} key={rider.id}><div className="flex items-start justify-between gap-2"><div><b>{rider.name}</b><p className="muted">{rider.email}</p></div><span className="rounded-full bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-700">{rider.riderProfile.onboardingStatus}</span></div><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-500">{rider.riderProfile.documents.filter((document) => document.status === "APPROVED").length}/4 documentos aprobados</span><span className="text-sm font-bold text-orange-600">Ver expediente ›</span></div></button>)}{!riders.length ? <p className="card">No hay riders en este estado.</p> : null}</section>
    {selected ? <section className="mt-3 rounded-3xl bg-slate-950 p-4 text-white"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold tracking-widest text-orange-400">EXPEDIENTE PRIVADO</p><h2 className="mt-1 text-xl font-bold">{selected.name}</h2><p className="text-sm text-slate-300">{selected.riderProfile.workZoneDepartment || "Zona pendiente"}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${eligible ? "bg-emerald-400/15 text-emerald-200" : "bg-amber-400/15 text-amber-200"}`}>{eligible ? "LISTO" : "INCOMPLETO"}</span></div><p className="mt-3 rounded-xl bg-white/5 p-3 text-sm text-slate-300">Seguro: {date(selected.riderProfile.insuranceExpiresAt)}. La cuenta solo se habilita cuando los cuatro documentos sean aprobados y el seguro siga vigente.</p>
      {required.map((type) => { const document = selected.riderProfile.documents.find((item) => item.type === type); const insuranceExpired = type === "INSURANCE" && (!document?.expiresAt || new Date(document.expiresAt) <= new Date()); return <article className="mt-3 rounded-2xl border border-white/10 bg-white/5 p-3" key={type}><div className="flex justify-between"><b>{labels[type]}</b><span className={`text-xs font-bold ${insuranceExpired ? "text-red-300" : "text-slate-300"}`}>{document?.status || "NO ENVIADO"}</span></div>{type === "INSURANCE" ? <p className={`mt-1 text-xs ${insuranceExpired ? "text-red-300" : "text-emerald-300"}`}>Vence: {date(document?.expiresAt)}</p> : null}<div className="mt-2 grid grid-cols-2 gap-2">{document?.frontImage ? <img className="h-32 w-full rounded-xl object-cover" src={document.frontImage} alt={`${labels[type]} frente`} /> : <div className="grid h-32 place-items-center rounded-xl bg-white/5 text-xs text-slate-400">Sin frente</div>}{document?.backImage ? <img className="h-32 w-full rounded-xl object-cover" src={document.backImage} alt={`${labels[type]} reverso`} /> : <div className="grid h-32 place-items-center rounded-xl bg-white/5 text-xs text-slate-400">Sin reverso</div>}</div>{document?.rejectionReason ? <p className="mt-2 text-sm text-red-300">Motivo: {document.rejectionReason}</p> : null}{document ? <div className="mt-3 flex gap-2"><button className="primary flex-1" disabled={insuranceExpired} onClick={() => review(document, "APPROVED")}>Aprobar</button><button className="flex-1 border border-white/20 bg-white/5" onClick={() => review(document, "REQUIRES_CORRECTION")}>Corregir</button></div> : null}</article>; })}
      <button className="primary mt-4 w-full" disabled={!eligible} onClick={approveRider}>{eligible ? "Aprobar cuenta rider" : "Completa el expediente para aprobar"}</button></section> : null}{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}
  </MobileAppShell></Guard>;
}
