"use client";
import { useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MapPoint, MapView } from "@/components/MapView";
import { api } from "@/lib/api";
import { MobileAppShell } from "@/components/MobileAppShell";
type Trip = { id: string; status: string; originAddress: string; originLat: number; originLng: number; destinationAddress: string; estimatedPrice: string; finalPrice?: string | null; proposedPrice?: string | null; currency: string };
export default function RiderPage() { const [profile, setProfile] = useState<{ approval: string; available: boolean } | null>(null); const [available, setAvailable] = useState<Trip[]>([]); const [history, setHistory] = useState<Trip[]>([]); const [position, setPosition] = useState<MapPoint>({ lat: 12.1364, lng: -86.2514 }); const [selected, setSelected] = useState<string>(); const [amount, setAmount] = useState(""); const [message, setMessage] = useState("");
  const load = () => Promise.all([api<typeof profile>("/riders/me"), api<Trip[]>("/riders/available-trips"), api<Trip[]>("/trips")]).then(([p, a, h]) => { setProfile(p); setAvailable(a); setHistory(h); }).catch((error) => setMessage(error.message)); useEffect(() => { load(); navigator.geolocation?.getCurrentPosition((point) => setPosition({ lat: point.coords.latitude, lng: point.coords.longitude })); }, []);
  const toggle = async () => { await api("/riders/me/availability", { method: "PATCH", body: JSON.stringify({ available: !profile?.available }) }); load(); }; const accept = async (id: string) => { await api(`/trips/${id}/accept`, { method: "POST" }); setMessage("Viaje aceptado."); load(); }; const counter = async (id: string) => { await api(`/trips/${id}/offers`, { method: "POST", body: JSON.stringify({ amount: Number(amount) }) }); setAmount(""); setMessage("Contraoferta enviada por 2 minutos."); };
  const trip = available.find((item) => item.id === selected); const earned = history.filter((item) => item.status === "COMPLETED").reduce((sum, item) => sum + Number(item.finalPrice || item.estimatedPrice), 0);
  return <Guard roles={["RIDER"]}><MobileAppShell role="RIDER"><section id="cuenta" className="card mt-3"><b>{profile?.approval === "APPROVED" ? "Cuenta aprobada" : "Cuenta pendiente de aprobación"}</b><button onClick={toggle} className="primary mt-3 w-full" disabled={profile?.approval !== "APPROVED"}>{profile?.available ? "Desactivarme" : "Activarme para viajes"}</button></section><section id="solicitudes" className="mt-3 scroll-mt-4"><p className="text-sm">Tu ubicación es azul. Las solicitudes disponibles son moradas.</p><MapView rider={position} focus={position} requests={available.map((item) => ({ id: item.id, lat: item.originLat, lng: item.originLng, title: item.originAddress, subtitle: item.destinationAddress }))} onRequestClick={setSelected} /></section>{trip && <article id="oferta" className="card mt-3 scroll-mt-4"><b>{trip.originAddress} → {trip.destinationAddress}</b><p className="muted">Estimado: {trip.currency} {trip.estimatedPrice}{trip.proposedPrice ? ` · Cliente propone ${trip.currency} ${trip.proposedPrice}` : ""}</p><button onClick={() => accept(trip.id)} className="primary mt-2 w-full">Aceptar tarifa</button><div className="mt-2 flex gap-2"><input type="number" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Contraoferta" /><button className="border" onClick={() => counter(trip.id)} disabled={!amount}>Enviar</button></div></article>}<section id="ganancias" className="card mt-3 scroll-mt-4"><b>Ganancias simuladas</b><p className="mt-1 text-2xl font-bold">NIO {earned.toFixed(2)}</p><p className="muted">Solo viajes completados.</p></section><section id="historial" className="card mt-3 scroll-mt-4"><b>Historial</b>{history.slice(0, 8).map((item) => <article className="mt-2 rounded-xl border p-2" key={item.id}><div className="flex justify-between"><span>{item.status}</span><b>{item.currency} {item.finalPrice || item.estimatedPrice}</b></div><p className="muted">{item.originAddress} → {item.destinationAddress}</p></article>)}{history.length === 0 && <p className="muted mt-2">Aún no tienes viajes.</p>}</section>{message && <p className="mt-3 text-sm" role="status">{message}</p>}</MobileAppShell></Guard>; }
