"use client";

import { useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MapPoint, MapView } from "@/components/MapView";
import { api } from "@/lib/api";
import { MobileAppShell } from "@/components/MobileAppShell";

type Profile = { approval: string; available: boolean; vehicleModel?: string | null; vehiclePlate?: string | null };
type Trip = { id: string; originAddress: string; originLat: number; originLng: number; destinationAddress: string; estimatedPrice: string; proposedPrice?: string | null; currency: string };

export default function RiderPage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [requests, setRequests] = useState<Trip[]>([]); const [position, setPosition] = useState<MapPoint>({ lat: 12.1364, lng: -86.2514 }); const [selected, setSelected] = useState<string>(); const [amount, setAmount] = useState(""); const [message, setMessage] = useState("");
  const load = () => Promise.all([api<Profile>("/riders/me"), api<Trip[]>("/riders/available-trips")]).then(([nextProfile, nextRequests]) => { setProfile(nextProfile); setRequests(nextRequests); }).catch((error) => setMessage(error.message));
  useEffect(() => { load(); navigator.geolocation?.getCurrentPosition((point) => setPosition({ lat: point.coords.latitude, lng: point.coords.longitude })); }, []);
  const toggleAvailability = async () => { try { await api("/riders/me/availability", { method: "PATCH", body: JSON.stringify({ available: !profile?.available }) }); await load(); } catch (error) { setMessage((error as Error).message); } };
  const selectedTrip = requests.find((item) => item.id === selected);
  const accept = async (id: string) => { try { await api(`/trips/${id}/accept`, { method: "POST" }); setMessage("Viaje aceptado."); await load(); } catch (error) { setMessage((error as Error).message); } };
  const counter = async (id: string) => { try { await api(`/trips/${id}/offers`, { method: "POST", body: JSON.stringify({ amount: Number(amount) }) }); setAmount(""); setMessage("Contraoferta enviada. Espera la respuesta del pasajero."); } catch (error) { setMessage((error as Error).message); } };
  const approved = profile?.approval === "APPROVED";
  return <Guard roles={["RIDER"]}><MobileAppShell role="RIDER"><section className="mt-4 overflow-hidden rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-400">Zona de trabajo</p><h1 className="mt-1 text-2xl font-bold">{profile?.available ? "Estas disponible" : "Estas desconectado"}</h1><p className="mt-1 text-sm text-slate-300">{approved ? "Controla tu disponibilidad para recibir viajes." : "Completa la aprobacion de tu cuenta para comenzar."}</p></div><span className={`h-3 w-3 rounded-full ${profile?.available ? "bg-emerald-400 shadow-[0_0_18px_#34d399]" : "bg-slate-500"}`} /></div><button className={`mt-5 w-full ${profile?.available ? "bg-white text-slate-950" : "bg-orange-500 text-white"}`} disabled={!approved} onClick={toggleAvailability}>{profile?.available ? "Pausar recepcion de viajes" : "Activarme para trabajar"}</button></section>
    <button className="card mt-3 w-full text-left" onClick={() => window.location.assign("/rider/account")}><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Estado del rider</p><b className={approved ? "text-emerald-700" : "text-amber-700"}>{approved ? "Cuenta validada" : "Validacion pendiente"}</b><p className="muted mt-1">{profile?.vehicleModel || "Vehiculo pendiente"}{profile?.vehiclePlate ? ` · ${profile.vehiclePlate}` : ""}</p></div><span className="rounded-full bg-slate-100 px-3 py-2 text-sm">Ver perfil</span></div></button>
    <section className="mt-4"><div className="mb-2 flex items-center justify-between"><div><h2 className="font-bold">Solicitudes cercanas</h2><p className="muted">Toca un pin para ver los detalles.</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-700">{requests.length} nuevas</span></div><MapView rider={position} focus={position} requests={requests.map((item) => ({ id: item.id, lat: item.originLat, lng: item.originLng, title: item.originAddress, subtitle: item.destinationAddress }))} onRequestClick={setSelected} /></section>
    {selectedTrip ? <article className="card mt-3"><b>{selectedTrip.originAddress} → {selectedTrip.destinationAddress}</b><p className="muted mt-1">Tarifa: {selectedTrip.currency} {selectedTrip.proposedPrice || selectedTrip.estimatedPrice}</p><button className="primary mt-3 w-full" onClick={() => accept(selectedTrip.id)}>Aceptar tarifa</button><div className="mt-2 flex gap-2"><input type="number" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Enviar contraoferta" /><button className="border" disabled={!amount} onClick={() => counter(selectedTrip.id)}>Enviar</button></div></article> : <section className="card mt-3 text-center"><b>{profile?.available ? "Esperando solicitudes" : "Activa tu disponibilidad"}</b><p className="muted mt-1">Tu mapa se mantiene centrado en tu zona de trabajo.</p></section>}
    {message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>;
}
