import { Prisma, TripStatus } from "@prisma/client";
import { prisma } from "../db.js";
import { fail } from "../lib/error.js";
import { haversineKm } from "../lib/geo.js";
import { getSettings } from "./settings.service.js";
const operatingCenter={lat:12.1364,lng:-86.2514};
const operatingRadiusKm=75;
function validateRoute(origin:{lat:number;lng:number},destination:{lat:number;lng:number}){const distance=haversineKm(origin,destination);if(distance<0.05)fail(422,"ORIGIN_EQUALS_DESTINATION","El origen y el destino deben ser diferentes.");if(haversineKm(operatingCenter,origin)>operatingRadiusKm||haversineKm(operatingCenter,destination)>operatingRadiusKm)fail(422,"OUTSIDE_OPERATING_AREA","Esta ubicación está fuera del área operativa actual de MotoYa.");return distance;}
const active=["REQUESTED","ACCEPTED","RIDER_ON_THE_WAY","RIDER_ARRIVED","IN_PROGRESS"] as TripStatus[];
const transitions:Partial<Record<TripStatus,TripStatus[]>>={REQUESTED:["ACCEPTED"],ACCEPTED:["RIDER_ON_THE_WAY","CANCELLED_BY_RIDER"],RIDER_ON_THE_WAY:["RIDER_ARRIVED","CANCELLED_BY_RIDER"],RIDER_ARRIVED:["IN_PROGRESS","CANCELLED_BY_RIDER"],IN_PROGRESS:["COMPLETED"]};
export async function estimate(origin:{lat:number;lng:number},destination:{lat:number;lng:number}){ const s=await getSettings(); const distanceKm=validateRoute(origin,destination); const amount=Math.max(Number(s.minimumFare),Number(s.baseFare)+distanceKm*Number(s.pricePerKm)); return {distanceKm,estimatedPrice:Number(amount.toFixed(2)),currency:s.currency}; }
export async function createTrip(clientId:string, origin:{lat:number;lng:number;address:string}, destination:{lat:number;lng:number;address:string}){ const exists=await prisma.trip.findFirst({where:{clientId,status:{in:active}}}); if(exists) fail(409,"CLIENT_HAS_ACTIVE_TRIP","Ya tienes un viaje activo."); const quote=await estimate(origin,destination); return prisma.$transaction(async tx=>{ const trip=await tx.trip.create({data:{clientId,originLat:origin.lat,originLng:origin.lng,originAddress:origin.address,destinationLat:destination.lat,destinationLng:destination.lng,destinationAddress:destination.address,distanceKm:quote.distanceKm,estimatedPrice:new Prisma.Decimal(quote.estimatedPrice),currency:quote.currency}}); await tx.tripStatusHistory.create({data:{tripId:trip.id,status:"REQUESTED",actorId:clientId}}); return trip; }); }
async function eligibleRider(tx:Prisma.TransactionClient,riderId:string){ const rider=await tx.riderProfile.findUnique({where:{userId:riderId},include:{subscriptions:{where:{status:"ACTIVE",expiresAt:{gt:new Date()}},take:1}}}); const settings=await getSettings(); const subscriptionRequired=settings.launchPhase!=="1"; if(!rider||rider.approval!=="APPROVED"||!rider.available||(subscriptionRequired&&rider.subscriptions.length===0)) fail(403,"RIDER_NOT_ELIGIBLE",subscriptionRequired?"Debes estar aprobado, disponible y con suscripción activa.":"Debes estar aprobado y disponible."); const busy=await tx.trip.findFirst({where:{riderId,status:{in:active.filter(s=>s!=="REQUESTED")}}}); if(busy) fail(409,"RIDER_HAS_ACTIVE_TRIP","Ya tienes un viaje activo."); }
export async function acceptTrip(tripId:string,riderId:string){ return prisma.$transaction(async tx=>{ await eligibleRider(tx,riderId); const updated=await tx.trip.updateMany({where:{id:tripId,status:"REQUESTED",riderId:null},data:{status:"ACCEPTED",riderId}}); if(updated.count!==1) fail(409,"TRIP_ALREADY_ACCEPTED","El viaje ya fue aceptado por otro rider."); await tx.tripStatusHistory.create({data:{tripId,status:"ACCEPTED",actorId:riderId}}); return tx.trip.findUniqueOrThrow({where:{id:tripId},include:{client:true,rider:true}}); }); }
export async function changeStatus(tripId:string,actorId:string,role:string,next:TripStatus){ const trip=await prisma.trip.findUnique({where:{id:tripId}}); if(!trip) fail(404,"TRIP_NOT_FOUND","Viaje no encontrado."); if(role!=="RIDER"||trip.riderId!==actorId) fail(403,"FORBIDDEN","No puedes actualizar este viaje."); if(!transitions[trip.status]?.includes(next)) fail(409,"INVALID_TRIP_TRANSITION","La transición de estado no está permitida."); return prisma.$transaction(async tx=>{ const result=await tx.trip.updateMany({where:{id:tripId,status:trip.status,riderId:actorId},data:{status:next}}); if(!result.count) fail(409,"TRIP_CHANGED","El viaje cambió, vuelve a intentarlo."); await tx.tripStatusHistory.create({data:{tripId,status:next,actorId}}); return tx.trip.findUniqueOrThrow({where:{id:tripId},include:{client:true,rider:true,histories:true}}); }); }
export async function cancelTrip(tripId:string,actorId:string,role:string){ const trip=await prisma.trip.findUnique({where:{id:tripId}}); if(!trip) fail(404,"TRIP_NOT_FOUND","Viaje no encontrado."); const status=role==="ADMIN"?"CANCELLED_BY_ADMIN":role==="CLIENT"&&trip.clientId===actorId?"CANCELLED_BY_CLIENT":role==="RIDER"&&trip.riderId===actorId?"CANCELLED_BY_RIDER":null; if(!status) fail(403,"FORBIDDEN","No puedes cancelar este viaje."); if(!active.includes(trip.status)||trip.status==="IN_PROGRESS") fail(409,"TRIP_CANNOT_BE_CANCELLED","El viaje ya no puede cancelarse."); return prisma.$transaction(async tx=>{ await tx.trip.update({where:{id:tripId},data:{status}}); await tx.tripStatusHistory.create({data:{tripId,status,actorId}}); return tx.trip.findUniqueOrThrow({where:{id:tripId},include:{client:true,rider:true}}); }); }
