import { Router } from "express";
import { Role } from "@prisma/client";
import { loginSchema, registerSchema } from "@motoya/shared";
import { prisma } from "../db.js";
import { hashPassword, hashToken, makeTokens, readRefresh, verifyPassword } from "../lib/auth.js";
import { fail } from "../lib/error.js";
import { authenticate } from "../middleware/auth.js";
export const authRouter=Router();
async function register(role:Role,body:unknown){ const data=registerSchema.parse(body); const exists=await prisma.user.findUnique({where:{email:data.email}}); if(exists) fail(409,"EMAIL_TAKEN","Este correo ya está registrado."); const user=await prisma.user.create({data:{name:data.name,email:data.email,passwordHash:await hashPassword(data.password),phone:data.phone,role,...(role==="CLIENT"?{clientProfile:{create:{}}}:{riderProfile:{create:{}}})}}); const tokens=makeTokens({id:user.id,role:user.role,email:user.email}); await prisma.refreshToken.create({data:{tokenHash:hashToken(tokens.refreshToken),userId:user.id,expiresAt:new Date(Date.now()+7*864e5)}}); return {user:{id:user.id,name:user.name,email:user.email,role:user.role},...tokens}; }
authRouter.post("/register/client",async(req,res)=>res.status(201).json(await register("CLIENT",req.body)));
authRouter.post("/register/rider",async(req,res)=>res.status(201).json(await register("RIDER",req.body)));
authRouter.post("/login",async(req,res)=>{const data=loginSchema.parse(req.body); const user=await prisma.user.findUnique({where:{email:data.email}}); if(!user||!(await verifyPassword(data.password,user.passwordHash))) fail(401,"INVALID_CREDENTIALS","Correo o contraseña incorrectos."); if(user.status!=="ACTIVE") fail(403,"ACCOUNT_INACTIVE","Tu cuenta no está activa."); const tokens=makeTokens({id:user.id,role:user.role,email:user.email}); await prisma.refreshToken.create({data:{tokenHash:hashToken(tokens.refreshToken),userId:user.id,expiresAt:new Date(Date.now()+7*864e5)}}); res.json({user:{id:user.id,name:user.name,email:user.email,role:user.role},...tokens});});
authRouter.post("/refresh",async(req,res)=>{const token=String(req.body.refreshToken||""); const payload=readRefresh(token); const record=await prisma.refreshToken.findUnique({where:{tokenHash:hashToken(token)}}); if(!record||record.revokedAt||record.expiresAt<new Date()) fail(401,"INVALID_REFRESH_TOKEN","Sesión expirada."); await prisma.refreshToken.update({where:{id:record.id},data:{revokedAt:new Date()}}); const user=await prisma.user.findUniqueOrThrow({where:{id:payload.id}}); const tokens=makeTokens({id:user.id,role:user.role,email:user.email}); await prisma.refreshToken.create({data:{tokenHash:hashToken(tokens.refreshToken),userId:user.id,expiresAt:new Date(Date.now()+7*864e5)}}); res.json(tokens);});
authRouter.post("/logout",async(req,res)=>{const token=String(req.body.refreshToken||""); if(token) await prisma.refreshToken.updateMany({where:{tokenHash:hashToken(token)},data:{revokedAt:new Date()}}); res.status(204).end();});
authRouter.get("/me",authenticate,async(req,res)=>res.json(await prisma.user.findUnique({where:{id:req.user!.id},include:{riderProfile:{include:{subscriptions:{orderBy:{createdAt:"desc"},take:1}}},clientProfile:true}})));
