import { z } from "zod";
import { prisma } from "../db.js";
import { authenticate, authorize } from "../middleware/auth.js";
import { haversineKm } from "../lib/geo.js";
import { fail } from "../lib/error.js";
import { safeRouter } from "../middleware/safe-router.js";
export const placesRouter=safeRouter(); placesRouter.use(authenticate,authorize("CLIENT"));
const labelSchema=z.string().trim().min(1).max(40);
const placeSchema=z.object({address:z.string().min(3),reference:z.string().trim().max(120).optional().nullable(),lat:z.number(),lng:z.number()});
placesRouter.get("/",async(req,res)=>res.json(await prisma.savedPlace.findMany({where:{userId:req.user!.id},orderBy:{createdAt:"asc"}})));
placesRouter.put("/:label",async(req,res)=>{const label=labelSchema.parse(req.params.label);const data=placeSchema.parse(req.body);if(haversineKm({lat:12.1364,lng:-86.2514},data)>75)fail(422,"OUTSIDE_OPERATING_AREA","No puedes guardar una ubicación fuera del área operativa actual.");res.json(await prisma.savedPlace.upsert({where:{userId_label:{userId:req.user!.id,label}},update:data,create:{userId:req.user!.id,label,...data}}));});
placesRouter.delete("/:label",async(req,res)=>{await prisma.savedPlace.delete({where:{userId_label:{userId:req.user!.id,label:req.params.label}}});res.status(204).end();});
