"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Document = { id: string; type: string; status: string; expiresAt?: string | null; frontImage?: string | null; backImage?: string | null; rejectionReason?: string | null };
type Rider = { id: string; name: string; email: string; phone?: string | null; riderProfile: { approval: string; onboardingStatus: string; nationalId?: string | null; driverLicense?: string | null; vehiclePlate?: string | null; vehicleModel?: string | null; insuranceExpiresAt?: string | null; workZoneDepartment?: string | null; documents: Document[]; subscriptions: { status: string; expiresAt?: string | null }[]; subscriptionOrders: { status: string; planNameSnapshot: string; priceSnapshot: string; currencySnapshot: string; payments: { id: string; status: string; externalReference: string; proofReference?: string | null; metadata?: { bankName?: string } | null; method: { name: string } }[] }[] } };
const required = ["NATIONAL_ID", "DRIVER_LICENSE", "VEHICLE_REGISTRATION", "INSURANCE"];
const labels: Record<string, string> = { NATIONAL_ID: "Cedula", DRIVER_LICENSE: "Licencia", VEHICLE_REGISTRATION: "Tarjeta de circulacion", INSURANCE: "Seguro" };
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleDateString("es-NI") : "Sin fecha";
const mask = (value?: string | null) => value ? `${value.slice(0, 4)}••••${value.slice(-3)}` : "Pendiente";

export default function ApprovalDetailPage() {
  const params = useParams<{ riderId: string }>(); const [rider, setRider] = useState<Rider | null>(null); const [message, setMessage] = useState("");
  const load = () => api<Rider>(`/admin/approvals/${params.riderId}`).then(setRider).catch((error) => setMessage(error.message));
  useEffect(() => { if (params.riderId) load(); }, [params.riderId]);
  const eligible = useMemo(() => { if (!rider) return false; const insurance = rider.riderProfile.documents.find((document) => document.type === "INSURANCE"); return required.every((type) => rider.riderProfile.documents.find((document) => document.type === type)?.status === "APPROVED") && Boolean(insurance?.expiresAt && new Date(insurance.expiresAt) > new Date()); }, [rider]);
  async function review(document: Document, status: "APPROVED" | "REQUIRES_CORRECTION") { if (!rider) return; const reason = status === "APPROVED" ? undefined : window.prompt("Indica la correccion requerida") || undefined; if (status !== "APPROVED" && !reason) return; try { await api(`/admin/riders/${rider.id}/documents/${document.id}`, { method: "PATCH", body: JSON.stringify({ status, reason }) }); setMessage(status === "APPROVED" ? "Documento aprobado." : "Correccion solicitada."); await load(); } catch (cause) { setMessage((cause as Error).message); } }
  async function approve() { if (!rider || !eligible) return; try { await api(`/admin/riders/${rider.id}/status`, { method: "PATCH", body: JSON.stringify({ approval: "APPROVED" }) }); setMessage("Rider aprobado. Aun requiere plan, zona y disponibilidad para operar."); await load(); } catch (cause) { setMessage((cause as Error).message); } }
  async function reviewPayment(paymentId: string, approved: boolean) { const reason = approved ? undefined : window.prompt("Motivo del rechazo") || undefined; if (!approved && !reason) return; try { await api(`/subscriptions/admin/payments/${paymentId}/review`, { method: "POST", body: JSON.stringify({ approved, reason }) }); setMessage(approved ? "Pago aprobado y suscripción activada." : "Pago rechazado."); await load(); } catch (cause) { setMessage((cause as Error).message); } }
  return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><Link className="mt-4 inline-block text-sm font-bold text-orange-600" href="/admin/approvals">← Solicitudes</Link>{!rider ? <p className="mt-5 card">Cargando expediente...</p> : <><section className="mt-3 rounded-3xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold tracking-widest text-orange-400">EXPEDIENTE PRIVADO</p><div className="mt-2 flex justify-between gap-3"><div><h1 className="text-2xl font-black">{rider.name}</h1><p className="text-sm text-slate-300">{rider.email} · {rider.riderProfile.workZoneDepartment || "Zona pendiente"}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${eligible ? "bg-emerald-400/15 text-emerald-200" : "bg-amber-400/15 text-amber-200"}`}>{eligible ? "LISTO" : "INCOMPLETO"}</span></div></section>
    <section className="mt-3 rounded-2xl bg-emerald-950 p-4 text-white"><h2 className="font-bold">Vehículo y cobertura</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><p className="rounded-xl bg-white/10 p-3"><span className="block text-xs text-emerald-200">Modelo</span>{rider.riderProfile.vehicleModel || "Pendiente"}</p><p className="rounded-xl bg-white/10 p-3"><span className="block text-xs text-emerald-200">Placa</span>{rider.riderProfile.vehiclePlate || "Pendiente"}</p><p className="rounded-xl bg-white/10 p-3"><span className="block text-xs text-emerald-200">Cédula</span>{mask(rider.riderProfile.nationalId)}</p><p className="rounded-xl bg-white/10 p-3"><span className="block text-xs text-emerald-200">Licencia</span>{mask(rider.riderProfile.driverLicense)}</p></div><p className={`mt-3 rounded-xl p-3 text-sm font-semibold ${rider.riderProfile.insuranceExpiresAt && new Date(rider.riderProfile.insuranceExpiresAt) > new Date() ? "bg-emerald-400/15 text-emerald-100" : "bg-red-500/15 text-red-200"}`}>Seguro vence: {formatDate(rider.riderProfile.insuranceExpiresAt)}</p></section>
    <section className="mt-3 space-y-3">{required.map((type) => { const document = rider.riderProfile.documents.find((item) => item.type === type); const expired = type === "INSURANCE" && (!document?.expiresAt || new Date(document.expiresAt) <= new Date()); const reviewed = document?.status === "APPROVED"; return <article className="rounded-2xl bg-slate-950 p-4 text-white" key={type}><div className="flex justify-between"><b>{labels[type]}</b><span className={expired ? "text-xs font-bold text-red-300" : reviewed ? "text-xs font-bold text-emerald-300" : "text-xs font-bold text-slate-300"}>{document?.status || "NO ENVIADO"}</span></div>{type === "INSURANCE" ? <p className={`mt-1 text-xs ${expired ? "text-red-300" : "text-emerald-300"}`}>Vence: {formatDate(document?.expiresAt)}</p> : null}<div className="mt-3 grid grid-cols-2 gap-2">{document?.frontImage ? <img className="h-36 w-full rounded-xl object-cover" src={document.frontImage} alt={`${labels[type]} frente`} /> : <div className="grid h-36 place-items-center rounded-xl bg-white/5 text-xs text-slate-400">Sin frente</div>}{document?.backImage ? <img className="h-36 w-full rounded-xl object-cover" src={document.backImage} alt={`${labels[type]} reverso`} /> : <div className="grid h-36 place-items-center rounded-xl bg-white/5 text-xs text-slate-400">Sin reverso</div>}</div>{document?.rejectionReason ? <p className="mt-2 text-sm text-red-300">Motivo: {document.rejectionReason}</p> : null}{document && !reviewed ? <div className="mt-3 flex gap-2"><button className="primary flex-1" disabled={expired} onClick={() => review(document, "APPROVED")}>Aprobar</button><button className="flex-1 border border-white/20 bg-white/5" onClick={() => review(document, "REQUIRES_CORRECTION")}>Corregir</button></div> : reviewed ? <p className="mt-3 rounded-xl bg-emerald-400/10 p-3 text-sm font-semibold text-emerald-200">Documento validado. No requiere otra acción.</p> : null}</article>; })}</section><section className="card mt-3"><p className="text-xs font-bold tracking-wider text-orange-500">SUSCRIPCIÓN</p><h2 className="mt-1 font-bold">{rider.riderProfile.subscriptions[0]?.status === "ACTIVE" ? "Plan activo" : "Plan pendiente"}</h2><p className="muted mt-1">{rider.riderProfile.subscriptions[0]?.expiresAt ? `Vence: ${formatDate(rider.riderProfile.subscriptions[0].expiresAt)}` : "El rider deberá elegir y pagar un plan después de ser aprobado."}</p></section><button className="primary mt-4 w-full" disabled={!eligible} onClick={approve}>{eligible ? "Aprobar cuenta rider" : "Completa el expediente para aprobar"}</button></>}{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>;
}
