"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
type Plan = { id: string; name: string; description: string; price: string; currency: string; durationDays: number; benefits: string[] };
type Method = { code: "MOTO_EXPRESS" | "BANK_TRANSFER"; name: string; instructions: string; configuration?: Record<string, string> | null };
type Created = { order: { planNameSnapshot: string; expiresAt: string }; payment: { id: string; externalReference: string; amount: string; currency: string; status: string }; method: Method };
export function RiderSubscriptionPayment() { const [plans, setPlans] = useState<Plan[]>([]); const [methods, setMethods] = useState<Method[]>([]); const [plan, setPlan] = useState<Plan | null>(null); const [method, setMethod] = useState<Method | null>(null); const [created, setCreated] = useState<Created | null>(null); const [bankName, setBankName] = useState(""); const [transferReference, setTransferReference] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([api<Plan[]>("/subscriptions/plans"), api<Method[]>("/subscriptions/methods")]).then(([p, m]) => { setPlans(p); setMethods(m); }).catch((error) => setMessage(error.message)); }, []);
  const create = async () => { if (!plan || !method) return; try { setCreated(await api<Created>("/subscriptions/orders", { method: "POST", body: JSON.stringify({ planId: plan.id, methodCode: method.code }) })); } catch (error) { setMessage((error as Error).message); } };
  const submit = async () => { if (!created || !method) return; try { if (method.code === "MOTO_EXPRESS") await api(`/subscriptions/payments/${created.payment.id}/mark-paid`, { method: "POST" }); else await api(`/subscriptions/payments/${created.payment.id}/transfer`, { method: "POST", body: JSON.stringify({ bankName, transferReference }) }); setMessage("Pago enviado a revisión. Te avisaremos cuando sea aprobado."); } catch (error) { setMessage((error as Error).message); } };
  return <section id="suscripcion" className="mt-3 scroll-mt-4"><div className="rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase tracking-wider text-orange-400">MotoSuscripción Express</p><h2 className="mt-1 text-xl font-bold">Elige tu plan mensual</h2><p className="mt-1 text-sm text-slate-300">Una suscripción activa te permite conectarte y recibir solicitudes.</p></div>{!created && <><section className="card mt-3"><b>1. Selecciona un plan</b><div className="mt-3 space-y-2">{plans.map((item) => <button key={item.id} onClick={() => setPlan(item)} className={`w-full border text-left ${plan?.id === item.id ? "ring-2 ring-orange-500" : ""}`}><div className="flex justify-between"><b>{item.name}</b><b>{item.currency} {item.price}</b></div><p className="muted">{item.description} · {item.durationDays} días</p></button>)}</div></section>{plan && <section className="card mt-3"><b>2. Método de pago</b><div className="mt-3 space-y-2">{methods.map((item) => <button key={item.code} onClick={() => setMethod(item)} className={`w-full border text-left ${method?.code === item.code ? "ring-2 ring-orange-500" : ""}`}><b>{item.name}</b><p className="muted">{item.instructions}</p></button>)}</div><button className="primary mt-3 w-full" disabled={!method} onClick={create}>Continuar</button></section>}</>}{created && <section className="card mt-3"><p className="text-xs font-bold uppercase text-orange-500">{created.method.name}</p><h3 className="mt-1 text-xl font-bold">{created.order.planNameSnapshot}</h3><p className="muted">Monto exacto: {created.payment.currency} {created.payment.amount}</p>{created.method.code === "MOTO_EXPRESS" ? <div className="mt-4 rounded-2xl bg-orange-500 p-4 text-center text-white"><p>Realiza el pago en MotoSuscripción Express</p><p className="mt-3 text-sm">Referencia</p><b className="text-3xl tracking-widest">{created.payment.externalReference}</b><p className="mt-3 text-sm">Válida hasta {new Date(created.order.expiresAt).toLocaleString("es-NI")}</p><button className="mt-4 w-full bg-white text-orange-600" onClick={submit}>Ya realicé el pago</button></div> : <div className="mt-3"><p className="muted">{created.method.instructions}</p><input className="mt-2" value={bankName} onChange={(e) => setBankName(e.target.value)} placeholder="Banco de origen" /><input className="mt-2" value={transferReference} onChange={(e) => setTransferReference(e.target.value)} placeholder="Número de transferencia" /><button className="primary mt-3 w-full" disabled={!bankName || !transferReference} onClick={submit}>Enviar transferencia a revisión</button></div>}<button className="mt-3 w-full border" onClick={() => { setCreated(null); setMethod(null); }}>Elegir otro plan</button></section>}{message && <p className="mt-3 text-sm" role="status">{message}</p>}</section>; }
