"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";

type Plan = { id: string; name: string; description: string; price: string; currency: string; durationDays: number; benefits: string[] };
type Subscription = { status: string; expiresAt?: string; plan?: { name: string; benefits: string[] } | null } | null;
type Order = { id: string; status: "PENDING_PAYMENT" | "PENDING_REVIEW" | "COMPLETED" | "EXPIRED" | "CANCELLED"; planNameSnapshot: string; priceSnapshot: string; currencySnapshot: string; payments: { externalReference: string; status: string; method: { name: string } }[] };
const planLimits: Record<string, { daily: number; tone: string }> = { Basico: { daily: 5, tone: "from-sky-700 to-blue-950" }, Estandar: { daily: 10, tone: "from-violet-700 to-indigo-950" }, Premium: { daily: 20, tone: "from-orange-500 to-amber-800" } };

export function RiderSubscriptionPayment() {
  const [plans, setPlans] = useState<Plan[]>([]); const [subscription, setSubscription] = useState<Subscription>(null); const [order, setOrder] = useState<Order | null>(null); const [renewing, setRenewing] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([api<Plan[]>("/subscriptions/plans"), api<Subscription>("/riders/me/subscription"), api<Order[]>("/subscriptions/orders")]).then(([nextPlans, nextSubscription, orders]) => { setPlans(nextPlans); setSubscription(nextSubscription); setOrder(orders.find((item) => item.status === "PENDING_PAYMENT" || item.status === "PENDING_REVIEW") || null); }).catch((error) => setMessage(error.message)); }, []);
  const days = subscription?.expiresAt ? Math.max(0, Math.ceil((new Date(subscription.expiresAt).getTime() - Date.now()) / 864e5)) : 0; const waiting = Boolean(order); const showPlans = !waiting && (!subscription || subscription.status !== "ACTIVE" || renewing);
  return <section className="mt-3"><div className="rounded-3xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-orange-400">Suscripción MotoYa</p><h2 className="mt-1 text-xl font-bold">{subscription?.status === "ACTIVE" ? subscription.plan?.name || "Plan activo" : waiting ? "Solicitud en proceso" : "Elige tu plan mensual"}</h2><p className="mt-2 text-sm text-slate-300">{subscription?.status === "ACTIVE" ? `${days} días restantes. Vence ${new Date(subscription.expiresAt!).toLocaleDateString("es-NI")}.` : waiting ? "No puedes seleccionar otro plan mientras esta solicitud esté en revisión." : "Elige un plan para continuar al pago."}</p></div>
    {waiting && order ? <section className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-wider text-amber-700">{order.status === "PENDING_REVIEW" ? "PAGO PENDIENTE DE VALIDACIÓN" : "PAGO PENDIENTE"}</p><h3 className="mt-1 font-bold">{order.planNameSnapshot} · {order.currencySnapshot} {order.priceSnapshot}</h3></div><span className="rounded-full bg-amber-200 px-2 py-1 text-xs font-bold">PENDIENTE</span></div><p className="mt-2 text-sm">Método: {order.payments[0]?.method.name || "Preparando pago"}</p><p className="mt-1 text-sm">Referencia: <b>{order.payments[0]?.externalReference || "—"}</b></p><p className="mt-3 text-xs text-amber-800">La administración revisará el comprobante. Si rechaza o vence la solicitud, podrás elegir otro plan.</p></section> : null}
    {subscription?.status === "ACTIVE" && !renewing && !waiting ? <button className="primary mt-3 w-full" onClick={() => setRenewing(true)}>Renovar o cambiar plan</button> : null}
    {showPlans ? <section className="mt-3"><p className="text-xs font-bold uppercase tracking-wider text-orange-500">Paso 1 de 2</p><h3 className="mt-1 font-bold">Selecciona tu nivel</h3><div className="mt-3 space-y-3">{plans.map((plan) => { const meta = planLimits[plan.name] || { daily: 5, tone: "from-slate-800 to-slate-950" }; return <Link key={plan.id} className={`block rounded-3xl bg-gradient-to-br ${meta.tone} p-4 text-white shadow-lg transition active:scale-[.98]`} href={`/rider/subscription/checkout?planId=${encodeURIComponent(plan.id)}`}><div className="flex justify-between gap-3"><div><b className="text-xl">{plan.name}</b><p className="mt-1 text-sm text-white/75">{plan.durationDays} días de vigencia</p></div><b className="rounded-xl bg-white/15 px-3 py-2">{plan.currency} {plan.price}</b></div><div className="mt-4 grid grid-cols-2 gap-2"><span className="rounded-xl bg-white/10 p-3 text-sm"><b className="block text-lg">{meta.daily}</b>viajes por día</span><span className="rounded-xl bg-white/10 p-3 text-sm"><b className="block text-lg">{meta.daily * plan.durationDays}</b>máximo mensual</span></div><p className="mt-3 text-sm text-white/85">{plan.description}</p><span className="mt-4 inline-block rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-950">Elegir este plan →</span></Link>; })}</div></section> : null}{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</section>;
}
