"use client";

import { useEffect, useState } from "react";
import { Guard } from "@/components/Guard";
import { MobileAppShell } from "@/components/MobileAppShell";
import { api } from "@/lib/api";

type Fares = { baseFare: string; pricePerKm: string; minimumFare: string; currency: string };
const initial: Fares = { baseFare: "", pricePerKm: "", minimumFare: "", currency: "NIO" };
export default function AdminFaresPage() { const [fares, setFares] = useState<Fares>(initial); const [message, setMessage] = useState(""); useEffect(() => { api<Record<string, string>>("/admin/settings").then((settings) => setFares({ baseFare: settings.baseFare || "", pricePerKm: settings.pricePerKm || "", minimumFare: settings.minimumFare || "", currency: settings.currency || "NIO" })).catch((error) => setMessage(error.message)); }, []); const save = async () => { try { const values = [fares.baseFare, fares.pricePerKm, fares.minimumFare].map(Number); if (values.some((value) => !Number.isFinite(value) || value < 0) || !fares.currency.trim()) { setMessage("Ingresa tarifas válidas."); return; } await api("/admin/settings", { method: "PATCH", body: JSON.stringify(fares) }); setMessage("Tarifas actualizadas. Las próximas estimaciones usarán estos valores."); } catch (error) { setMessage((error as Error).message); } }; const field = (key: keyof Fares, label: string, hint: string) => <label className="block"><span className="font-bold">{label}</span><span className="muted mt-1 block">{hint}</span><input className="mt-2" inputMode={key === "currency" ? "text" : "decimal"} value={fares[key]} onChange={(event) => setFares({ ...fares, [key]: event.target.value })} /></label>; return <Guard roles={["ADMIN"]}><MobileAppShell role="ADMIN"><section className="mt-4"><p className="text-xs font-bold tracking-[.16em] text-orange-500">VIAJES</p><h1 className="text-2xl font-black">Tarifas de Moto</h1><p className="muted">Se usan en la estimación de nuevos viajes. No cambian viajes ya solicitados.</p></section><section className="card mt-4 space-y-4 lg:max-w-xl">{field("baseFare", "Tarifa base", "Monto inicial antes de calcular distancia.")}{field("pricePerKm", "Tarifa por kilómetro", "Monto adicional por cada km estimado.")}{field("minimumFare", "Tarifa mínima", "Menor monto que puede mostrar la estimación.")}{field("currency", "Moneda", "Código de tres letras, por ejemplo NIO.")}<button className="primary w-full" onClick={save}>Guardar tarifas de viaje</button></section>{message ? <p className="mt-3 text-sm" role="status">{message}</p> : null}</MobileAppShell></Guard>; }
